import {useEffect,useMemo,useState} from 'react';
import {Ionicons} from '@expo/vector-icons';
import {Pressable,StyleSheet,TextInput,View} from 'react-native';
import {AppShell,shellStyles} from '../src/components/AppShell';
import {HeaderAction} from '../src/components/HeaderAction';
import {FormModal} from '../src/components/FormModal';
import {DateField,formatDateBR} from '../src/components/DateField';
import {AsyncState} from '../src/components/AsyncState';
import {Text} from '../src/i18n';
import {api} from '../src/api';
import {theme} from '../src/theme';

const types:any={appointment:['Atendimento','people-outline'],visit:['Visita','location-outline'],meeting:['Reunião','chatbubbles-outline'],deadline:['Prazo','flag-outline'],personal:['Pessoal','person-outline']};
export default function Calendar(){
 const[events,setEvents]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
 const[form,setForm]=useState<any>({title:'',type:'appointment',date:new Date().toISOString().slice(0,10),time:'09:00',location:'',description:'',reminderMinutes:60});
 const load=()=>{setLoading(true);setError('');api('/calendar').then(setEvents).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);
 const groups=useMemo(()=>events.reduce((a:any,e:any)=>{const day=e.startAt.slice(0,10);(a[day]??=[]).push(e);return a},{}),[events]);
 const save=async()=>{if(!form.title.trim())return;setSaving(true);try{await api('/calendar',{method:'POST',body:JSON.stringify({...form,startAt:`${form.date}T${form.time}:00`,allDay:false,recurrence:'none'})});setOpen(false);setForm({...form,title:'',location:'',description:''});load()}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 const today=new Date().toISOString().slice(0,10); const todayCount=events.filter(e=>e.startAt?.slice(0,10)===today).length; const upcoming=events.filter(e=>e.startAt?.slice(0,10)>today).length;
 return <AppShell title="Agenda" subtitle="Compromissos, visitas e prazos da operação" action={<HeaderAction label="Novo compromisso" icon="calendar-outline" onPress={()=>setOpen(true)}/>}>
  <View style={s.summaryRow}><CalendarSummary icon="calendar-outline" label="Compromissos" value={String(events.length)}/><CalendarSummary icon="today-outline" label="Hoje" value={String(todayCount)}/><CalendarSummary icon="time-outline" label="Próximos" value={String(upcoming)}/></View>
  {loading||error?<AsyncState loading={loading} error={error} onRetry={load}/>:events.length===0?<View style={s.empty}><Ionicons name="calendar-outline" size={32} color={theme.gold}/><Text style={s.emptyTitle}>Agenda livre</Text><Text style={s.emptyText}>Crie um compromisso para começar a organizar sua rotina.</Text></View>:Object.keys(groups).sort().map(day=><View key={day} style={s.day}><View style={s.dayHead}><Text style={s.dayNumber}>{new Date(day+'T12:00:00').getDate()}</Text><View><Text style={s.dayName}>{new Date(day+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long'})}</Text><Text style={s.dayDate}>{formatDateBR(day)}</Text></View></View><View style={s.events}>{groups[day].map((e:any)=>{const meta=types[e.type]||types.appointment;return <View key={e.id} style={s.event}><View style={s.eventIcon}><Ionicons name={meta[1]} size={18} color={theme.green}/></View><View style={{flex:1}}><Text style={s.eventTitle}>{e.title}</Text><Text style={s.eventMeta}>{new Date(e.startAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}{e.location?` · ${e.location}`:''}</Text></View><Text style={s.type}>{meta[0]}</Text></View>})}</View></View>)}
  <FormModal visible={open} title="Novo compromisso" subtitle="Adicione um item à agenda da equipe." onClose={()=>setOpen(false)} footer={<><Pressable style={s.cancel} onPress={()=>setOpen(false)}><Text>Cancelar</Text></Pressable><Pressable disabled={saving||!form.title.trim()} style={[shellStyles.button,(saving||!form.title.trim())&&{opacity:.5}]} onPress={save}><Text style={shellStyles.buttonText}>{saving?'Salvando...':'Salvar compromisso'}</Text></Pressable></>}><Text style={s.label}>TÍTULO *</Text><TextInput style={s.input} value={form.title} onChangeText={title=>setForm({...form,title})} placeholder="Ex.: Visita técnica com cliente"/><View style={s.row}><View style={{flex:1}}><DateField label="DATA" value={form.date} onChange={date=>setForm({...form,date})}/></View><View style={{width:120}}><Text style={s.label}>HORÁRIO</Text><TextInput style={s.input} value={form.time} onChangeText={time=>setForm({...form,time})} placeholder="09:00"/></View></View><Text style={s.label}>TIPO</Text><View style={s.chips}>{Object.entries(types).map(([value,m]:any)=><Pressable key={value} onPress={()=>setForm({...form,type:value})} style={[s.chip,form.type===value&&s.chipOn]}><Text style={[s.chipText,form.type===value&&s.chipTextOn]}>{m[0]}</Text></Pressable>)}</View><Text style={s.label}>LOCAL</Text><TextInput style={s.input} value={form.location} onChangeText={location=>setForm({...form,location})} placeholder="Endereço ou link"/><Text style={s.label}>OBSERVAÇÕES</Text><TextInput multiline style={[s.input,{height:86,textAlignVertical:'top'}]} value={form.description} onChangeText={description=>setForm({...form,description})}/></FormModal>
 </AppShell>
}
function CalendarSummary({icon,label,value}:{icon:string;label:string;value:string}){return <View style={s.summaryCard}><View style={s.summaryIcon}><Ionicons name={icon as any} size={17} color={theme.green2}/></View><View><Text style={s.summaryLabel}>{label}</Text><Text style={s.summaryValue}>{value}</Text></View></View>}
const s=StyleSheet.create({summaryRow:{flexDirection:'row',flexWrap:'wrap',gap:10,marginBottom:14},summaryCard:{minWidth:160,flex:1,backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:12,paddingHorizontal:14,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:10},summaryIcon:{width:34,height:34,borderRadius:9,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},summaryLabel:{fontSize:11,color:theme.muted},summaryValue:{fontFamily:'serif',fontSize:18,fontWeight:'800',color:theme.ink,marginTop:1},hero:{backgroundColor:theme.green,padding:22,borderRadius:18,marginBottom:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:theme.gold},heroTitle:{fontFamily:'serif',fontSize:24,fontWeight:'800',color:theme.white,marginTop:5},heroSub:{fontSize:12,color:'rgba(255,255,255,.65)',marginTop:4},heroIcon:{width:52,height:52,borderRadius:15,backgroundColor:'rgba(255,255,255,.09)',alignItems:'center',justifyContent:'center'},day:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:16,padding:16,marginBottom:12,flexDirection:'row',gap:18},dayHead:{width:130,flexDirection:'row',alignItems:'center',gap:10},dayNumber:{fontFamily:'serif',fontSize:28,fontWeight:'800',color:theme.green},dayName:{fontSize:12,fontWeight:'900',color:theme.ink,textTransform:'capitalize'},dayDate:{fontSize:11,color:theme.muted,marginTop:2},events:{flex:1,gap:8},event:{minHeight:58,borderRadius:11,backgroundColor:theme.green50,padding:10,flexDirection:'row',alignItems:'center',gap:10},eventIcon:{width:36,height:36,borderRadius:10,backgroundColor:theme.white,alignItems:'center',justifyContent:'center'},eventTitle:{fontSize:13,fontWeight:'900',color:theme.ink},eventMeta:{fontSize:11,color:theme.muted,marginTop:3},type:{fontSize:10,fontWeight:'900',color:theme.green2},empty:{padding:42,alignItems:'center',backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:16},emptyTitle:{fontFamily:'serif',fontSize:20,fontWeight:'800',color:theme.ink,marginTop:10},emptyText:{fontSize:12,color:theme.muted,marginTop:5,textAlign:'center'},label:{fontSize:11,fontWeight:'900',color:theme.muted},input:{height:44,borderWidth:1,borderColor:theme.border,borderRadius:10,paddingHorizontal:12,color:theme.ink,backgroundColor:theme.white},row:{flexDirection:'row',gap:10},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:20,borderWidth:1,borderColor:theme.border},chipOn:{backgroundColor:theme.green,borderColor:theme.green},chipText:{fontSize:11,fontWeight:'800',color:theme.muted},chipTextOn:{color:theme.white},cancel:{paddingHorizontal:15,paddingVertical:11}});
