import { useState } from 'react';
import { ActivityIndicator,Pressable,StyleSheet,useWindowDimensions,View } from 'react-native';
import { LanguageSwitch, Text, TextInput } from '../src/i18n';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { api,establishSession } from '../src/api'; import { theme } from '../src/theme';
export default function Login(){
  const wide=useWindowDimensions().width>=900;
  const[email,setEmail]=useState('luana@luviepro.local'),[password,setPassword]=useState('LuviePro123!'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function enter(){try{setBusy(true);setError('');const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});establishSession(r);router.replace('/home');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <SafeAreaView style={s.page}><View style={s.language}><LanguageSwitch compact/></View>{wide&&<View style={s.decorative}><View><Brand/><Text style={s.slogan}>Organize.{`\n`}Calcule.{`\n`}<Text style={{color:theme.gold}}>Encante.</Text></Text><Text style={s.copy}>O sistema completo para personal organizers profissionais gerenciarem clientes, orçamentos e projetos.</Text></View><Text style={s.community}>● ● ●  Feito para organizers em todo o Brasil</Text></View>}<View style={[s.formSide,!wide&&{backgroundColor:theme.g800}]}>{!wide&&<View style={{marginBottom:26}}><Brand/></View>}<View style={s.card}><Text style={s.title}>Bem-vinda de volta</Text><Text style={s.subtitle}>Acesse sua conta para continuar</Text><Text style={s.label}>E-MAIL</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" style={s.input}/><View style={s.passwordLabel}><Text style={s.label}>SENHA</Text><Text style={s.forgot}>Esqueceu?</Text></View><TextInput value={password} onChangeText={setPassword} secureTextEntry style={s.input}/>{!!error&&<Text style={s.error}>⚠ {error}</Text>}<Pressable style={s.button} onPress={enter}>{busy?<ActivityIndicator color="white"/>:<Text style={s.buttonText}>Entrar</Text>}</Pressable></View><Pressable onPress={()=>router.push('/register')}><Text style={s.create}>Não tem conta?  <Text style={{color:'white',fontWeight:'700'}}>Criar conta grátis</Text></Text></Pressable></View></SafeAreaView>;
}
function Brand(){return <View style={s.logoRow}><View style={s.logoBox}><Text style={s.logoLetter}>L</Text></View><Text style={s.logo}>LuviePro</Text></View>}
const s=StyleSheet.create({language:{position:'absolute',top:18,right:18,zIndex:20},page:{flex:1,backgroundColor:theme.g800,flexDirection:'row'},decorative:{width:'45%',padding:48,justifyContent:'space-between',backgroundColor:theme.g800},logoRow:{flexDirection:'row',alignItems:'center',gap:12},logoBox:{width:40,height:40,borderRadius:12,backgroundColor:theme.gold,alignItems:'center',justifyContent:'center'},logoLetter:{fontFamily:'serif',fontSize:20,fontWeight:'800',color:theme.g900},logo:{fontFamily:'serif',fontSize:22,fontWeight:'700',color:'white'},slogan:{fontFamily:'serif',fontSize:42,lineHeight:49,fontWeight:'700',color:'white',marginTop:64},copy:{color:'#B1CBB6',fontSize:16,lineHeight:25,maxWidth:360,marginTop:20},community:{color:'#B1CBB6',fontSize:13},formSide:{flex:1,alignItems:'center',justifyContent:'center',padding:24,backgroundColor:theme.green2},card:{backgroundColor:'white',borderRadius:28,padding:32,maxWidth:400,width:'100%',shadowColor:'#000',shadowOpacity:.22,shadowRadius:24},title:{fontFamily:'serif',fontSize:25,fontWeight:'700',color:theme.g800},subtitle:{color:theme.muted,fontSize:13,marginTop:5,marginBottom:28},label:{fontSize:13,fontWeight:'700',color:'#626964',marginBottom:7,letterSpacing:.8},passwordLabel:{flexDirection:'row',justifyContent:'space-between'},forgot:{fontSize:13,color:theme.green2},input:{borderWidth:1,borderColor:theme.border,borderRadius:12,padding:13,marginBottom:18,backgroundColor:'white'},button:{backgroundColor:theme.green,borderRadius:12,padding:14,alignItems:'center',marginTop:4},buttonText:{color:'white',fontWeight:'700'},error:{color:theme.danger,marginBottom:10,fontSize:14},create:{color:'#B1CBB6',marginTop:20,fontSize:13}});
