import {useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,View} from 'react-native';
import {router} from 'expo-router';
import {api,logout} from '../src/api';
import {Text} from '../src/i18n';
import {theme} from '../src/theme';

export default function Platform(){
 const [data,setData]=useState<any>(); const [tab,setTab]=useState('overview'); const [companies,setCompanies]=useState<any[]>([]); const [subs,setSubs]=useState<any[]>([]);
 useEffect(()=>{Promise.all([api('/platform/overview'),api('/platform/tenants'),api('/platform/subscriptions')]).then(([o,c,s])=>{setData(o);setCompanies(c?.tenants??c??[]);setSubs(s?.subscriptions??s??[])}).catch(()=>router.replace('/'))},[]);
 if(!data)return <View style={s.loading}><ActivityIndicator color={theme.gold}/></View>;
 const tabs=[['overview','Visão geral'],['companies','Empresas'],['subs','Assinaturas']]; const money=`R$ ${(Number(data.monthlyRevenueCents||0)/100).toLocaleString('pt-BR',{minimumFractionDigits:2})}`;
 return <ScrollView style={s.page} contentContainerStyle={s.wrap}><View style={s.header}><View><Text style={s.kicker}>LUVIEPRO · PLATFORM</Text><Text style={s.title}>Console da plataforma</Text><Text style={s.sub}>Gestão global do seu SaaS</Text></View><Pressable onPress={async()=>{await logout();router.replace('/')}}><Text style={s.logout}>Sair</Text></Pressable></View><View style={s.nav}><Text style={s.brand}>LuviePro <Text style={s.brandLight}>PLATFORM</Text></Text>{tabs.map(([key,label])=><Pressable key={key} onPress={()=>setTab(key)} style={[s.navItem,tab===key&&s.active]}><Text style={s.navText}>{label}</Text></Pressable>)}<View style={s.health}><View style={s.dot}/><Text style={s.healthText}>Sistemas OK</Text></View></View>{tab==='overview'?<><View style={s.metrics}>{[['Empresas',data.tenants],['Ativas',data.activeTenants],['Usuários',data.users],['Clientes',data.clients],['Receita mensal',money]].map(([l,v])=><View style={s.metric} key={String(l)}><Text style={s.label}>{l}</Text><Text style={s.value}>{String(v??0)}</Text></View>)}</View><View style={s.cols}><Panel title="Empresas recentes" action={()=>setTab('companies')}>{companies.slice(0,5).map((c,i)=><Row key={i} title={c.name??c.companyName??'Empresa'} sub={c.ownerEmail??c.email??'Conta LuviePro'} badge={c.active===false?'Inativa':'Ativa'}/>)}</Panel><Panel title="Assinaturas" action={()=>setTab('subs')}>{subs.slice(0,5).map((x,i)=><Row key={i} title={x.plan??x.planName??'Plano Pro'} sub={x.status??'Ativa'} />)}</Panel></View></>:<Panel title={tab==='companies'?'Empresas':'Assinaturas'}>{(tab==='companies'?companies:subs).map((x,i)=><Row key={i} title={tab==='companies'?(x.name??x.companyName??'Empresa'):(x.plan??x.planName??'Plano Pro')} sub={x.ownerEmail??x.email??x.status??'Ativa'} badge={tab==='companies'?(x.active===false?'Inativa':'Ativa'):undefined}/>)}</Panel>}</ScrollView>;
}
function Panel({title,action,children}:any){return <View style={s.panel}><View style={s.panelHead}><Text style={s.panelTitle}>{title}</Text>{action&&<Pressable onPress={action}><Text style={s.link}>Ver todos →</Text></Pressable>}</View>{children}</View>}
function Row({title,sub,badge}:any){return <View style={s.row}><View style={s.avatar}><Text style={s.avatarText}>{title.slice(0,1).toUpperCase()}</Text></View><View style={s.rowMain}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{sub}</Text></View>{badge&&<View style={s.badge}><Text style={s.badgeText}>{badge}</Text></View>}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.cream},wrap:{padding:28,maxWidth:1220,width:'100%',alignSelf:'center'},loading:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:theme.cream},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:22},kicker:{color:theme.gold,fontSize:11,fontWeight:'900',letterSpacing:1.5},title:{color:theme.ink,fontFamily:'serif',fontSize:31,fontWeight:'800',marginTop:5},sub:{color:theme.muted,marginTop:5},logout:{color:theme.green2,fontWeight:'800',padding:10},nav:{backgroundColor:theme.green2,borderRadius:14,padding:8,flexDirection:'row',alignItems:'center',gap:5,marginBottom:22},brand:{color:'#fff',fontWeight:'900',paddingHorizontal:12},brandLight:{color:theme.gold,fontSize:10},navItem:{paddingVertical:9,paddingHorizontal:14,borderRadius:9},active:{backgroundColor:'rgba(255,255,255,.16)'},navText:{color:'#fff',fontSize:12,fontWeight:'700'},health:{marginLeft:'auto',flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:10},dot:{width:7,height:7,borderRadius:7,backgroundColor:'#79d19c'},healthText:{color:'#c7d8cf',fontSize:11},metrics:{flexDirection:'row',flexWrap:'wrap',gap:14,marginBottom:18},metric:{flex:1,minWidth:170,backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:17},label:{color:theme.muted,fontSize:12},value:{color:theme.ink,fontFamily:'serif',fontSize:26,fontWeight:'800',marginTop:8},cols:{flexDirection:'row',gap:18},panel:{flex:1,backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:20,marginBottom:18},panelHead:{flexDirection:'row',justifyContent:'space-between',marginBottom:10},panelTitle:{color:theme.ink,fontFamily:'serif',fontSize:19,fontWeight:'800'},link:{color:theme.green2,fontSize:12,fontWeight:'800'},row:{flexDirection:'row',alignItems:'center',borderTopWidth:1,borderTopColor:theme.border,paddingVertical:13,gap:11},avatar:{width:34,height:34,borderRadius:17,backgroundColor:theme.gold,alignItems:'center',justifyContent:'center'},avatarText:{color:theme.ink,fontWeight:'900'},rowMain:{flex:1},rowTitle:{color:theme.ink,fontWeight:'800',fontSize:13},rowSub:{color:theme.muted,fontSize:11,marginTop:3},badge:{backgroundColor:'#e8f6ed',paddingHorizontal:9,paddingVertical:5,borderRadius:20},badgeText:{color:'#28734b',fontSize:11,fontWeight:'800'}});
