import {useCallback,useMemo,useState} from 'react';
import {Ionicons} from '@expo/vector-icons';
import {Pressable,ScrollView,StyleSheet,useWindowDimensions,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import {api,money} from '../src/api';
import {theme} from '../src/theme';
import {AppShell} from '../src/components/AppShell';
import {AsyncState} from '../src/components/AsyncState';
import {SearchField} from '../src/components/SearchField';
import {BusinessToolbar,FilterChip} from '../src/components/BusinessList';
import {SortMenu} from '../src/components/ListControls';
import {formatDateBR} from '../src/components/DateField';
import {Text} from '../src/i18n';

const fallback=[{key:'scheduled',name:'Agendados',color:theme.gold,active:true},{key:'in_progress',name:'Em andamento',color:theme.green2,active:true},{key:'completed',name:'Concluídos',color:'#6F8C78',active:true}];
const filters=['Todos','Com atraso','Alta prioridade'];

export default function Projects(){
  const[list,setList]=useState<any[]>([]),[statuses,setStatuses]=useState<any[]>(fallback),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[sort,setSort]=useState('priority'),[boardWidth,setBoardWidth]=useState(0);
  const{width}=useWindowDimensions();const compact=width<820;
  const load=useCallback(()=>{setLoading(true);setLoadError('');Promise.all([api('/projects'),api('/project-statuses')]).then(([projects,configured])=>{setList(projects);setStatuses(configured?.length?configured:fallback)}).catch(e=>setLoadError(e.message||'Não foi possível carregar projetos')).finally(()=>setLoading(false))},[]);useFocusEffect(load);
  const filtered=useMemo(()=>{const items=list.filter(project=>{const term=query.trim().toLowerCase();const matches=!term||`${project.name} ${project.client?.name??''} ${project.quote?.number??''}`.toLowerCase().includes(term);const overdue=project.tasks?.some((t:any)=>isOverdue(t));const high=project.tasks?.some((t:any)=>t.status!=='completed'&&t.priority==='high');return matches&&(filter==='Todos'||filter==='Com atraso'&&overdue||filter==='Alta prioridade'&&high)});return [...items].sort((a,b)=>{const critical=(p:any)=>(p.tasks?.filter((t:any)=>isOverdue(t)).length??0)*100+(p.tasks?.filter((t:any)=>t.status!=='completed'&&t.priority==='high').length??0);if(sort==='name')return String(a.name).localeCompare(String(b.name),'pt-BR');if(sort==='progress-desc')return b.progress-a.progress;if(sort==='progress-asc')return a.progress-b.progress;return critical(b)-critical(a)})},[list,query,filter,sort]);
  const columns=statuses.filter(status=>status.active||list.some(project=>project.status===status.key));const needsScroll=compact||columns.length>4;const visibleCount=Math.min(Math.max(columns.length,1),4);const columnWidth=compact?Math.max(270,width-44):boardWidth?Math.max(280,(boardWidth-(visibleCount-1)*12)/visibleCount):330;const totalOverdue=list.reduce((sum,p)=>sum+(p.tasks?.filter((t:any)=>isOverdue(t)).length??0),0);
  return <AppShell title="Projetos" subtitle="Acompanhe entregas, prazos e andamento da operação">
    <View style={s.page}><View style={s.summaryRow}><Summary icon="briefcase-outline" label="Projetos" value={String(list.length)}/><Summary icon="play-circle-outline" label="Em andamento" value={String(list.filter(p=>p.status==='in_progress').length)}/><Summary icon="alert-circle-outline" label="Tarefas atrasadas" value={String(totalOverdue)} danger={totalOverdue>0}/></View>
    <BusinessToolbar search={<SearchField value={query} onChangeText={setQuery} placeholder="Buscar projeto, cliente ou orçamento..."/>} filters={<View style={s.filters}>{filters.map(v=><FilterChip key={v} label={v} active={filter===v} onPress={()=>setFilter(v)}/>)}</View>} actions={<SortMenu value={sort} onChange={setSort} options={[{value:'priority',label:'Mais críticos'},{value:'name',label:'Nome A–Z'},{value:'progress-desc',label:'Maior progresso'},{value:'progress-asc',label:'Menor progresso'}]}/>} count={`${filtered.length} projeto(s)`}/>
    {loading||loadError?<AsyncState loading={loading} error={loadError} onRetry={load}/>:filtered.length===0?<AsyncState empty emptyTitle="Nenhum projeto encontrado" emptyMessage="Revise a busca ou os filtros aplicados."/>:<View style={s.boardMeasure} onLayout={event=>setBoardWidth(event.nativeEvent.layout.width)}><ScrollView horizontal={needsScroll} showsHorizontalScrollIndicator={needsScroll} contentContainerStyle={s.board}>{columns.map(column=><Column key={column.key} column={column} width={columnWidth} projects={filtered.filter(project=>project.status===column.key)}/>)}</ScrollView></View>}</View>
  </AppShell>;
}
function Column({column,projects,width}:{column:any;projects:any[];width?:number}){return <View style={[s.column,width?{width}:undefined]}><View style={s.columnHead}><View style={[s.dot,{backgroundColor:column.color}]}/><Text style={s.columnTitle}>{column.name}</Text><View style={s.count}><Text style={s.countText}>{projects.length}</Text></View></View><View style={s.cards}>{projects.map(project=><ProjectCard key={project.id} project={project} color={column.color}/>)}{!projects.length&&<View style={s.emptyColumn}><Ionicons name="layers-outline" size={23} color={theme.border}/><Text style={s.emptyText}>Nenhum projeto</Text></View>}</View></View>}
function ProjectCard({project,color}:{project:any;color:string}){const overdue=project.tasks?.filter((t:any)=>isOverdue(t)).length??0;const high=project.tasks?.filter((t:any)=>t.status!=='completed'&&t.priority==='high').length??0;return <Pressable onPress={()=>router.push(`/project/${project.id}` as any)} style={[s.card,{borderLeftColor:color},overdue>0&&s.overdueCard]}><View style={s.cardTop}><Text numberOfLines={2} style={s.name}>{project.name}</Text><Ionicons name="chevron-forward" size={17} color={theme.muted}/></View><Text style={s.client}>{project.client?.name}</Text>{(overdue>0||high>0)&&<View style={s.alerts}>{overdue>0&&<Text style={s.dangerTag}>{overdue} atrasada(s)</Text>}{high>0&&<Text style={s.highTag}>{high} alta prioridade</Text>}</View>}<View style={s.metaRow}><Text style={s.meta}>{project.startDate?formatDateBR(project.startDate):'Data a definir'}</Text>{project.quote&&<Text style={s.quote}>{project.quote.number}</Text>}</View><View style={s.progressHead}><Text style={s.progressLabel}>Progresso</Text><Text style={s.progressValue}>{project.progress}%</Text></View><View style={s.track}><View style={[s.bar,{width:`${project.progress}%`,backgroundColor:color}]}/></View>{project.quote&&<View style={s.footer}><Text style={s.footerLabel}>Valor do projeto</Text><Text style={s.value}>{money(project.quote.finalTotalCents||project.quote.totalCents)}</Text></View>}</Pressable>}
function Summary({icon,label,value,danger}:{icon:string;label:string;value:string;danger?:boolean}){return <View style={[s.summary,danger&&s.summaryDanger]}><View style={s.summaryIcon}><Ionicons name={icon as any} size={17} color={danger?theme.danger:theme.green2}/></View><View><Text style={s.summaryLabel}>{label}</Text><Text style={[s.summaryValue,danger&&{color:theme.danger}]}>{value}</Text></View></View>}
function isOverdue(task:any){return task.status!=='completed'&&task.dueDate&&new Date(task.dueDate).getTime()<new Date().setHours(0,0,0,0)}
const s=StyleSheet.create({page:{width:'100%',maxWidth:1440,alignSelf:'center'},summaryRow:{flexDirection:'row',flexWrap:'wrap',gap:10,marginBottom:14},summary:{minWidth:190,flex:1,backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:12,padding:13,flexDirection:'row',alignItems:'center',gap:10},summaryDanger:{borderColor:'#E7C7C1'},summaryIcon:{width:34,height:34,borderRadius:9,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},summaryLabel:{fontSize:11,color:theme.muted},summaryValue:{fontFamily:'serif',fontSize:18,fontWeight:'800',color:theme.ink},filters:{flexDirection:'row',gap:6,flexWrap:'wrap'},board:{flexGrow:1,alignItems:'flex-start',gap:12,paddingTop:14,paddingBottom:8},boardCompact:{flexDirection:'column'},column:{width:330,minHeight:330,backgroundColor:'#EFF3F0',borderRadius:14,padding:11},columnHead:{height:38,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:3},dot:{width:7,height:7,borderRadius:4},columnTitle:{flex:1,fontSize:12,fontWeight:'900',color:theme.ink,textTransform:'uppercase'},count:{minWidth:23,height:23,borderRadius:12,backgroundColor:theme.white,alignItems:'center',justifyContent:'center'},countText:{fontSize:11,fontWeight:'800',color:theme.muted},cards:{gap:9},card:{backgroundColor:theme.white,borderWidth:1,borderLeftWidth:3,borderColor:theme.border,borderRadius:11,padding:13},overdueCard:{borderColor:'#E6B8AF'},cardTop:{flexDirection:'row',gap:6},name:{flex:1,fontSize:13,fontWeight:'800',lineHeight:17,color:theme.ink},client:{fontSize:11,color:theme.muted,marginTop:4},alerts:{flexDirection:'row',gap:6,marginTop:8},dangerTag:{fontSize:10,fontWeight:'900',color:theme.danger,backgroundColor:'#FBE9E6',paddingHorizontal:7,paddingVertical:4,borderRadius:7},highTag:{fontSize:10,fontWeight:'900',color:'#8A6D22',backgroundColor:theme.goldPale,paddingHorizontal:7,paddingVertical:4,borderRadius:7},metaRow:{flexDirection:'row',justifyContent:'space-between',marginTop:11},meta:{fontSize:11,color:theme.muted},quote:{fontSize:11,fontWeight:'800',color:theme.gold},progressHead:{flexDirection:'row',justifyContent:'space-between',marginTop:11},progressLabel:{fontSize:11,color:theme.muted},progressValue:{fontSize:11,fontWeight:'800',color:theme.green2},track:{height:5,backgroundColor:theme.border,borderRadius:3,marginTop:5},bar:{height:5,borderRadius:3},footer:{borderTopWidth:1,borderTopColor:theme.border,marginTop:11,paddingTop:9,flexDirection:'row',justifyContent:'space-between'},footerLabel:{fontSize:11,color:theme.muted},value:{fontSize:11,fontWeight:'800',color:theme.ink},emptyColumn:{height:130,alignItems:'center',justifyContent:'center',gap:7},emptyText:{fontSize:11,color:theme.muted}});
