import {useCallback,useState} from 'react';
import {Ionicons} from '@expo/vector-icons';
import {Pressable,StyleSheet,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router';
import {api} from '../src/api';
import {Text,TextInput} from '../src/i18n';
import {theme} from '../src/theme';
import {AppShell} from '../src/components/AppShell';
import {AsyncState} from '../src/components/AsyncState';
import {FormModal} from '../src/components/FormModal';
import {HeaderAction} from '../src/components/HeaderAction';
import {useFeedback} from '../src/components/Feedback';

export default function ProjectStatuses(){
  const{notify,confirm}=useFeedback();const[list,setList]=useState<any[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[name,setName]=useState(''),[color,setColor]=useState('#2F6B4F'),[busy,setBusy]=useState(false);
  const load=useCallback(()=>{setLoading(true);api('/project-statuses').then(setList).catch((e:any)=>notify({tone:'error',title:'Erro ao carregar status',message:e.message})).finally(()=>setLoading(false))},[notify]);useFocusEffect(load);
  const start=(item?:any)=>{setEditing(item??null);setName(item?.name??'');setColor(item?.color??'#2F6B4F');setOpen(true)};
  async function save(){if(name.trim().length<2)return notify({tone:'error',title:'Nome obrigatório',message:'Informe um nome com pelo menos 2 caracteres.'});try{setBusy(true);await api(editing?`/project-statuses/${editing.id}`:'/project-statuses',{method:editing?'PATCH':'POST',body:JSON.stringify({name:name.trim(),color})});setOpen(false);load();notify({tone:'success',title:'Status salvo',message:'O Kanban foi atualizado.'})}catch(e:any){notify({tone:'error',title:'Não foi possível salvar',message:e.message})}finally{setBusy(false)}}
  async function toggle(item:any){try{await api(`/project-statuses/${item.id}`,{method:'PATCH',body:JSON.stringify({active:!item.active})});load()}catch(e:any){notify({tone:'error',title:'Não foi possível alterar',message:e.message})}}
  async function remove(item:any){if(!(await confirm({title:'Excluir status?',message:'A exclusão só será permitida se não houver projetos neste status.',confirmLabel:'Excluir',danger:true})))return;try{await api(`/project-statuses/${item.id}`,{method:'DELETE'});load()}catch(e:any){notify({tone:'error',title:'Não foi possível excluir',message:e.message})}}
  return <AppShell title="Status dos projetos" subtitle="Configure as colunas exibidas no Kanban." action={<HeaderAction label="Novo status" icon="add-circle-outline" onPress={()=>start()}/>}>
    <Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={16} color={theme.green2}/><Text style={s.backText}>Voltar para projetos</Text></Pressable>
    {loading?<AsyncState loading/>:<View style={s.list}>{list.map((item,index)=><View key={item.id} style={[s.row,!item.active&&s.inactive]}><View style={[s.color,{backgroundColor:item.color}]}/><View style={s.info}><Text style={s.name}>{item.name}</Text><Text style={s.meta}>Coluna {index+1} · {item.active?'Ativo':'Desativado'}</Text></View><Pressable onPress={()=>start(item)} style={s.icon}><Ionicons name="pencil-outline" size={18} color={theme.green2}/></Pressable><Pressable onPress={()=>toggle(item)} style={s.icon}><Ionicons name={item.active?'pause-circle-outline':'play-circle-outline'} size={19} color={theme.gold}/></Pressable><Pressable onPress={()=>remove(item)} style={s.icon}><Ionicons name="trash-outline" size={18} color={theme.danger}/></Pressable></View>)}</View>}
    <FormModal visible={open} title={editing?'Editar status':'Novo status'} subtitle="Defina o nome e a cor da coluna." onClose={()=>setOpen(false)} footer={<><Pressable onPress={()=>setOpen(false)} style={s.cancel}><Text style={s.cancelText}>Cancelar</Text></Pressable><Pressable disabled={busy} onPress={save} style={[s.submit,busy&&{opacity:.55}]}><Text style={s.submitText}>{busy?'Salvando...':'Salvar status'}</Text></Pressable></>}><Text style={s.label}>NOME DO STATUS</Text><TextInput value={name} onChangeText={setName} placeholder="Ex.: Aguardando cliente" style={s.input}/><Text style={s.label}>COR</Text><View style={s.colors}>{['#C9A84C','#2F6B4F','#6F8C78','#3D6F91','#8A5B6B','#A04A45'].map(value=><Pressable key={value} onPress={()=>setColor(value)} style={[s.swatch,{backgroundColor:value},color===value&&s.swatchOn]}><Ionicons name="checkmark" size={15} color={color===value?theme.white:'transparent'}/></Pressable>)}</View></FormModal>
  </AppShell>;
}
const s=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,marginBottom:14},backText:{fontSize:12,fontWeight:'800',color:theme.green2},list:{gap:10,maxWidth:760},row:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:13,padding:14,flexDirection:'row',alignItems:'center',gap:11},inactive:{opacity:.55},color:{width:12,height:42,borderRadius:6},info:{flex:1},name:{fontSize:14,fontWeight:'800',color:theme.ink},meta:{fontSize:11,color:theme.muted,marginTop:4},icon:{width:36,height:36,borderRadius:9,backgroundColor:theme.cream,alignItems:'center',justifyContent:'center'},label:{fontSize:11,fontWeight:'800',letterSpacing:.6,color:theme.muted,marginBottom:6},input:{borderWidth:1,borderColor:theme.border,borderRadius:10,paddingHorizontal:12,paddingVertical:11,color:theme.ink,marginBottom:16},colors:{flexDirection:'row',gap:10,flexWrap:'wrap'},swatch:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'},swatchOn:{borderWidth:3,borderColor:theme.ink},cancel:{borderWidth:1,borderColor:theme.border,borderRadius:9,paddingHorizontal:15,paddingVertical:10},cancelText:{fontSize:12,fontWeight:'800',color:theme.muted},submit:{backgroundColor:theme.gold,borderRadius:9,paddingHorizontal:16,paddingVertical:10},submitText:{fontSize:12,fontWeight:'800',color:theme.g900}});
