import { useCallback,useMemo,useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { Pressable,StyleSheet,Text,useWindowDimensions,View } from 'react-native';
import { router,useFocusEffect } from 'expo-router'; import { api,money } from '../src/api'; import { theme } from '../src/theme'; import { AppShell,shellStyles } from '../src/components/AppShell';
import { SearchField } from '../src/components/SearchField';
const labels:any={draft:'Rascunho',approved:'Aprovado',sent:'Enviado',rejected:'Recusado'}; const filters=['Todos','Rascunho','Enviado','Aprovado'];
export default function Quotes(){
  const[list,setList]=useState<any[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'); const {width}=useWindowDimensions();const compact=width<700;
  useFocusEffect(useCallback(()=>{api('/quotes').then(setList)},[]));
  const filtered=useMemo(()=>list.filter(q=>{const text=`${q.number} ${q.client.name}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(filter==='Todos'||labels[q.status]===filter)}),[list,query,filter]);
  const approved=list.filter(q=>q.status==='approved'); const approvedTotal=approved.reduce((sum,q)=>sum+(q.finalTotalCents||q.totalCents),0);
  return <AppShell title="Orçamentos" action={<Pressable style={shellStyles.button} onPress={()=>router.push('/quote-new')}><Text style={shellStyles.buttonText}>+ Novo orçamento</Text></Pressable>}>
    <View style={s.stats}><Stat label="Total de propostas" value={String(list.length)} icon="documents-outline"/><Stat label="Aprovadas" value={String(approved.length)} icon="checkmark-circle-outline"/><Stat label="Receita aprovada" value={money(approvedTotal)} icon="cash-outline"/></View>
    <View style={s.panel}><View style={[s.toolbar,compact&&s.toolbarCompact]}><SearchField value={query} onChangeText={setQuery} placeholder="Buscar orçamento ou cliente..."/><View style={s.filters}>{filters.map(value=><Pressable key={value} onPress={()=>setFilter(value)} style={[s.filter,filter===value&&s.filterOn]}><Text style={[s.filterText,filter===value&&s.filterTextOn]}>{value}</Text></Pressable>)}</View></View>
      {filtered.length===0?<Text style={shellStyles.empty}>Nenhum orçamento encontrado.</Text>:filtered.map((quote,index)=><Pressable key={quote.id} onPress={()=>router.push(`/quote/${quote.id}` as any)} style={[s.row,index===0&&s.firstRow]}><View style={s.doc}><Ionicons name="document-text-outline" size={18} color={theme.green2}/></View><View style={s.info}><Text style={s.number}>{quote.number}</Text><Text style={s.client}>{quote.client.name}</Text></View>{!compact&&<Text style={s.date}>{new Date(quote.createdAt).toLocaleDateString('pt-BR')}</Text>}<Badge status={quote.status}/><Text style={s.value}>{money(quote.finalTotalCents||quote.totalCents)}</Text><Ionicons name="chevron-forward" size={16} color={theme.muted}/></Pressable>)}
    </View>
  </AppShell>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:string}){return <View style={s.stat}><View style={s.statIcon}><Ionicons name={icon as any} size={18} color={theme.green2}/></View><View><Text style={s.statLabel}>{label}</Text><Text numberOfLines={1} adjustsFontSizeToFit style={s.statValue}>{value}</Text></View></View>}
function Badge({status}:{status:string}){return <View style={[s.badge,status==='approved'&&s.badgeGreen,status==='sent'&&s.badgeGold]}><Text style={[s.badgeText,status==='approved'&&s.badgeGreenText,status==='sent'&&s.badgeGoldText]}>{labels[status]??status}</Text></View>}
const s=StyleSheet.create({stats:{flexDirection:'row',flexWrap:'wrap',gap:13,marginBottom:18},stat:{minWidth:180,flex:1,backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:15,flexDirection:'row',alignItems:'center',gap:12},statIcon:{width:37,height:37,borderRadius:10,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},statLabel:{fontSize:9,color:theme.muted},statValue:{fontFamily:'serif',fontSize:19,fontWeight:'700',color:theme.ink,marginTop:3,maxWidth:180},panel:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:16,overflow:'hidden'},toolbar:{padding:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:theme.border},toolbarCompact:{flexDirection:'column',alignItems:'stretch'},search:{flex:1,height:39,borderWidth:1,borderColor:theme.border,borderRadius:10,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10,backgroundColor:theme.cream},searchInput:{flex:1,fontSize:10,color:theme.ink},filters:{flexDirection:'row',flexWrap:'wrap',gap:5},filter:{paddingHorizontal:9,paddingVertical:7,borderRadius:9},filterOn:{backgroundColor:theme.green2},filterText:{fontSize:8,fontWeight:'700',color:theme.muted},filterTextOn:{color:theme.white},row:{minHeight:68,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:11,borderTopWidth:1,borderTopColor:theme.border},firstRow:{borderTopWidth:0},doc:{width:36,height:36,borderRadius:10,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},info:{flex:1},number:{fontSize:11,fontWeight:'800',color:theme.ink},client:{fontSize:9,color:theme.muted,marginTop:3},date:{fontSize:9,color:theme.muted,minWidth:75},badge:{backgroundColor:theme.cream,borderRadius:10,paddingHorizontal:8,paddingVertical:5},badgeGreen:{backgroundColor:theme.green50},badgeGold:{backgroundColor:theme.goldPale},badgeText:{fontSize:8,fontWeight:'800',color:theme.muted},badgeGreenText:{color:theme.green2},badgeGoldText:{color:'#8A6D22'},value:{fontSize:10,fontWeight:'800',color:theme.ink,minWidth:80,textAlign:'right'}});
