import { useCallback,useEffect,useMemo,useState } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Modal,Pressable,StyleSheet,useWindowDimensions,View } from 'react-native';
import { Text } from '../src/i18n';
import { router,useFocusEffect,useLocalSearchParams } from 'expo-router'; import { api,money } from '../src/api'; import { theme } from '../src/theme'; import { AppShell,shellStyles } from '../src/components/AppShell';
import { HeaderAction } from '../src/components/HeaderAction';
import { SearchField } from '../src/components/SearchField';
import { AsyncState } from '../src/components/AsyncState';
import { BusinessPanel,BusinessToolbar,FilterChip,StatusBadge } from '../src/components/BusinessList';
import { ActionMenu,Pagination,SortMenu,paginate } from '../src/components/ListControls';
import { formatDateBR } from '../src/components/DateField';
import QuoteWizard from '@/features/quotes/QuoteWizard';
const labels:any={draft:'Rascunho',approved:'Aprovado',sent:'Enviado',rejected:'Recusado'}; const filters=['Todos','Rascunho','Enviado','Vencendo','Aprovado','Recusado'];
export default function Quotes(){
  const params=useLocalSearchParams<{new?:string}>();
  const[list,setList]=useState<any[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[page,setPage]=useState(1),[sort,setSort]=useState('recent'),[showNew,setShowNew]=useState(false); const {width}=useWindowDimensions();const compact=width<700;
  useEffect(()=>{if(params.new==='1')setShowNew(true)},[params.new]);
  const closeNew=()=>{setShowNew(false);if(params.new==='1')router.replace('/quotes')};
  const load=useCallback(()=>{setLoading(true);setLoadError('');api('/quotes').then(setList).catch(e=>setLoadError(e.message||'Não foi possível carregar orçamentos')).finally(()=>setLoading(false))},[]);useFocusEffect(load);
  const filtered=useMemo(()=>{const items=list.filter(q=>{const text=`${q.number} ${q.client.name}`.toLowerCase();const expiring=q.status==='sent'&&q.validUntil&&new Date(q.validUntil).getTime()>=Date.now()&&new Date(q.validUntil).getTime()<=Date.now()+7*86400000;return (!query||text.includes(query.toLowerCase()))&&(filter==='Todos'||filter==='Vencendo'&&expiring||labels[q.status]===filter)});return [...items].sort((a,b)=>sort==='oldest'?new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime():sort==='value-desc'?(b.finalTotalCents||b.totalCents)-(a.finalTotalCents||a.totalCents):sort==='value-asc'?(a.finalTotalCents||a.totalCents)-(b.finalTotalCents||b.totalCents):String(b.createdAt).localeCompare(String(a.createdAt)))},[list,query,filter,sort]);
  const pageSize=10;const visible=useMemo(()=>paginate(filtered,page,pageSize),[filtered,page]);useEffect(()=>setPage(1),[query,filter,sort]);
  const approved=list.filter(q=>q.status==='approved'); const approvedTotal=approved.reduce((sum,q)=>sum+(q.finalTotalCents||q.totalCents),0);
  const sent=list.filter(q=>q.status==='sent').length; const expiring=list.filter(q=>q.status==='sent'&&q.validUntil&&new Date(q.validUntil).getTime()>=Date.now()&&new Date(q.validUntil).getTime()<=Date.now()+7*86400000).length;
  return <AppShell title="Orçamentos" subtitle="Acompanhe propostas, valores e andamento comercial." action={<HeaderAction label="Novo orçamento" icon="add-circle-outline" onPress={()=>setShowNew(true)}/>}>
    <View style={s.stats}><Stat label="Propostas" value={String(list.length)} icon="documents-outline"/><Stat label="Enviadas" value={String(sent)} icon="paper-plane-outline"/><Stat label="Vencendo" value={String(expiring)} icon="time-outline"/><Stat label="Receita aprovada" value={money(approvedTotal)} icon="cash-outline"/></View>
    <BusinessPanel><BusinessToolbar search={<SearchField value={query} onChangeText={setQuery} placeholder="Buscar orçamento ou cliente..."/>} filters={<View style={s.filters}>{filters.map(value=><FilterChip key={value} label={value} active={filter===value} onPress={()=>setFilter(value)}/>)}</View>} actions={<SortMenu value={sort} onChange={setSort} options={[{value:'recent',label:'Mais recentes'},{value:'oldest',label:'Mais antigos'},{value:'value-desc',label:'Maior valor'},{value:'value-asc',label:'Menor valor'}]}/>} count={`${filtered.length} resultado(s)`}/>
      {!compact&&!loading&&!loadError&&filtered.length>0?<View style={s.tableHead}><Text style={[s.tableLabel,{flex:1}]}>ORÇAMENTO / CLIENTE</Text><Text style={[s.tableLabel,{width:75}]}>DATA</Text><Text style={[s.tableLabel,{width:78}]}>STATUS</Text><Text style={[s.tableLabel,{width:80,textAlign:'right'}]}>VALOR</Text><Text style={[s.tableLabel,{width:34,textAlign:'center'}]}>AÇÕES</Text></View>:null}{loading||loadError?<AsyncState loading={loading} error={loadError} onRetry={load}/>:filtered.length===0?<Text style={shellStyles.empty}>Nenhum orçamento encontrado.</Text>:visible.map((quote,index)=><Pressable key={quote.id} onPress={()=>router.push(`/quote/${quote.id}` as any)} style={[s.row,index===0&&s.firstRow,compact&&s.rowMobile]}><View style={s.doc}><Ionicons name="document-text-outline" size={18} color={theme.green2}/></View><View style={s.info}><Text style={s.number}>{quote.number}</Text><Text style={s.client}>{quote.client.name}</Text></View>{!compact&&<Text style={s.date}>{formatDateBR(quote.createdAt)}</Text>}<View>{<Badge status={quote.status}/>} {quote.status==='sent'&&quote.validUntil&&<Text style={s.expiry}>{expiryLabel(quote.validUntil)}</Text>}</View><Text style={s.value}>{money(quote.finalTotalCents||quote.totalCents)}</Text><ActionMenu items={[{label:'Abrir orçamento',icon:'open-outline',onPress:()=>router.push(`/quote/${quote.id}` as any)},{label:'Visualizar proposta',icon:'document-text-outline',onPress:()=>router.push(`/quote/${quote.id}/proposal` as any)}]}/></Pressable>)}<Pagination page={page} total={filtered.length} pageSize={pageSize} onChange={setPage}/>
    </BusinessPanel>
    <Modal visible={showNew} transparent animationType="fade" onRequestClose={closeNew}><View style={m.modalBackdrop}><View style={[m.modalCard,compact&&m.modalCardMobile]}><View style={m.modalHeader}><View><Text style={m.modalTitle}>Novo orçamento</Text><Text style={m.modalSub}>Crie uma proposta completa sem sair da lista.</Text></View><Pressable onPress={closeNew} style={m.modalClose}><Ionicons name="close" size={22} color={theme.muted}/></Pressable></View><View style={m.modalContent}><QuoteWizard embedded onClose={closeNew} onSaved={load}/></View></View></View></Modal>
  </AppShell>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:string}){return <View style={s.stat}><View style={s.statIcon}><Ionicons name={icon as any} size={18} color={theme.green2}/></View><View><Text style={s.statLabel}>{label}</Text><Text numberOfLines={1} adjustsFontSizeToFit style={s.statValue}>{value}</Text></View></View>}
function expiryLabel(value:string){const days=Math.ceil((new Date(value).getTime()-Date.now())/86400000);return days<0?'Vencida':days===0?'Vence hoje':days<=7?`Vence em ${days}d`:`Até ${new Date(value).toLocaleDateString('pt-BR')}`}
function Badge({status}:{status:string}){const tone=status==='approved'?'success':status==='sent'?'warning':status==='rejected'?'danger':'neutral';return <StatusBadge label={labels[status]??status} tone={tone as any}/>}
const m=StyleSheet.create({modalBackdrop:{flex:1,backgroundColor:'rgba(8,24,17,.55)',padding:24,alignItems:'center',justifyContent:'center'},modalCard:{width:'100%',maxWidth:1120,height:'92%',backgroundColor:theme.cream,borderRadius:20,overflow:'hidden',shadowColor:'#000',shadowOpacity:.22,shadowRadius:28,elevation:12},modalCardMobile:{height:'96%',marginTop:'auto',borderBottomLeftRadius:0,borderBottomRightRadius:0},modalHeader:{height:70,paddingHorizontal:24,backgroundColor:theme.white,borderBottomWidth:1,borderBottomColor:theme.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},modalTitle:{fontFamily:'serif',fontSize:22,fontWeight:'700',color:theme.ink},modalSub:{fontSize:12,color:theme.muted,marginTop:3},modalClose:{width:38,height:38,borderRadius:19,backgroundColor:theme.cream,alignItems:'center',justifyContent:'center'},modalContent:{flex:1}});
const s=StyleSheet.create({stats:{flexDirection:'row',flexWrap:'wrap',gap:13,marginBottom:18},stat:{minWidth:180,flex:1,backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:15,flexDirection:'row',alignItems:'center',gap:12},statIcon:{width:37,height:37,borderRadius:10,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},statLabel:{fontSize:11,color:theme.muted},statValue:{fontFamily:'serif',fontSize:19,fontWeight:'700',color:theme.ink,marginTop:3,maxWidth:180},panel:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:16,overflow:'hidden'},toolbar:{padding:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:theme.border},toolbarCompact:{flexDirection:'column',alignItems:'stretch'},search:{flex:1,height:39,borderWidth:1,borderColor:theme.border,borderRadius:10,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10,backgroundColor:theme.cream},searchInput:{flex:1,fontSize:12,color:theme.ink},filters:{flexDirection:'row',flexWrap:'wrap',gap:5},filter:{paddingHorizontal:9,paddingVertical:7,borderRadius:9},filterOn:{backgroundColor:theme.green2},filterText:{fontSize:11,fontWeight:'700',color:theme.muted},filterTextOn:{color:theme.white},tableHead:{height:36,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'#F7F9F7',borderBottomWidth:1,borderBottomColor:theme.border},tableLabel:{fontSize:11,fontWeight:'900',letterSpacing:.65,color:theme.muted},row:{minHeight:68,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:11,borderTopWidth:1,borderTopColor:theme.border},rowMobile:{marginHorizontal:10,marginVertical:5,borderWidth:1,borderColor:theme.border,borderRadius:12,paddingVertical:11,flexWrap:'wrap'},firstRow:{borderTopWidth:0},doc:{width:36,height:36,borderRadius:10,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},info:{flex:1},number:{fontSize:13,fontWeight:'800',color:theme.ink},client:{fontSize:11,color:theme.muted,marginTop:3},date:{fontSize:11,color:theme.muted,minWidth:75},badge:{backgroundColor:theme.cream,borderRadius:10,paddingHorizontal:8,paddingVertical:5},badgeGreen:{backgroundColor:theme.green50},badgeGold:{backgroundColor:theme.goldPale},badgeText:{fontSize:11,fontWeight:'800',color:theme.muted},badgeGreenText:{color:theme.green2},badgeGoldText:{color:'#8A6D22'},expiry:{fontSize:11,fontWeight:'800',color:theme.danger,marginTop:3,textAlign:'center'},value:{fontSize:12,fontWeight:'800',color:theme.ink,minWidth:80,textAlign:'right'}});
