import Ionicons from '@expo/vector-icons/Ionicons';
import { useEffect, useState } from 'react';
import type { ComponentProps, ReactNode } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { api, money } from '../../api';
import { feedbackAlert as Alert } from '../../components/Feedback';
import { Text } from '../../i18n';
import { theme } from '../../theme';

type ChangeHandler=(id:string,body:Record<string,unknown>)=>void|Promise<void>;
type Option=readonly [string,string];

export function NewPlatformTenantModal({visible,onClose,onCreated}:{visible:boolean;onClose:()=>void;onCreated:(result:any)=>void|Promise<void>}) {
 const initial={company:'',ownerName:'',ownerEmail:'',phone:'',plan:'pro',period:'monthly'};
 const[form,setForm]=useState(initial),[busy,setBusy]=useState(false);
 const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));
 const setPhone=(value:string)=>{const digits=value.replace(/\D/g,'').slice(0,11);const masked=digits.length<=10?digits.replace(/^(\d{0,2})(\d{0,4})(\d{0,4}).*/,(_,a,b,c)=>[a&&`(${a}`,a.length===2&&') ',b,c&&`-${c}`].filter(Boolean).join('')):digits.replace(/^(\d{2})(\d{5})(\d{0,4}).*/, '($1) $2-$3');set('phone',masked)};
 async function save(){if(form.company.trim().length<2||form.ownerName.trim().length<2||!/^\S+@\S+\.\S+$/.test(form.ownerEmail))return Alert.alert('Revise os dados','Informe empresa, proprietário e um e-mail válido.');try{setBusy(true);const result=await api('/platform/tenants',{method:'POST',body:JSON.stringify(form)});setForm(initial);await onCreated(result)}catch(error:any){Alert.alert('Não foi possível criar a empresa',error.message)}finally{setBusy(false)}}
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><ModalShell onClose={onClose}><ScrollView keyboardShouldPersistTaps="handled"><ModalHeader title="Cadastrar empresa" subtitle="Crie a conta e convide o proprietário para definir a senha." onClose={onClose}/><View style={styles.formGrid}><Field label="EMPRESA" value={form.company} onChangeText={value=>set('company',value)} autoCapitalize="words"/><Field label="PROPRIETÁRIO" value={form.ownerName} onChangeText={value=>set('ownerName',value)} autoCapitalize="words"/><Field label="E-MAIL" value={form.ownerEmail} onChangeText={value=>set('ownerEmail',value.trim())} autoCapitalize="none" keyboardType="email-address"/><Field label="TELEFONE / WHATSAPP" value={form.phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="(00) 00000-0000"/></View><Label text="PLANO"/><Chips value={form.plan} values={[['starter','Starter'],['pro','Pro'],['business','Business']]} onChange={value=>set('plan',value)}/><Label text="PERÍODO"/><Chips value={form.period} values={[['monthly','Mensal'],['quarterly','Trimestral'],['semiannual','Semestral'],['annual','Anual']]} onChange={value=>set('period',value)}/><Text style={styles.notice}>A conta inicia com 14 dias de teste. O acesso só é criado quando o proprietário aceita o convite.</Text><Save busy={busy} label={busy?'Criando empresa...':'Criar empresa e enviar convite'} onPress={save}/></ScrollView></ModalShell></Modal>;
}

export function PlatformEditModal({item,onClose,onTenant,onUser,onPlan}:{item:any;onClose:()=>void;onTenant:ChangeHandler;onUser:ChangeHandler;onPlan:ChangeHandler}) {
 const[form,setForm]=useState<Record<string,any>>({});
 useEffect(()=>setForm(item??{}),[item]);
 if(!item)return null;
 const set=(key:string,value:unknown)=>setForm(current=>({...current,[key]:value}));
 const prices=new Set(['monthlyPriceCents','quarterlyPriceCents','semiannualPriceCents','annualPriceCents']);
 return <Modal visible transparent animationType="fade" onRequestClose={onClose}><ModalShell onClose={onClose}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.modalContent}><ModalHeader title={item.kind==='tenant'?'Gerenciar empresa':item.kind==='user'?'Gerenciar usuário':'Configurar plano'} subtitle={item.name||item.plan?.toUpperCase()} onClose={onClose}/>{item.kind==='tenant'?<><Label text="STATUS"/><Chips value={form.status} values={[['active','Ativa'],['suspended','Suspensa'],['cancelled','Cancelada']]} onChange={value=>set('status',value)}/><Label text="PLANO"/><Chips value={form.plan} values={[['starter','Starter'],['pro','Pro'],['business','Business']]} onChange={value=>set('plan',value)}/><Label text="PERÍODO"/><Chips value={form.planPeriod||'monthly'} values={[['monthly','Mensal'],['quarterly','Trimestral'],['semiannual','Semestral'],['annual','Anual']]} onChange={value=>set('planPeriod',value)}/><Save label="Salvar alterações" onPress={()=>onTenant(item.id,{status:form.status,plan:form.plan,planPeriod:form.planPeriod||'monthly'})}/></>:item.kind==='user'?<><Label text="STATUS DE ACESSO"/><Chips value={form.active?'active':'inactive'} values={[['active','Ativo'],['inactive','Inativo']]} onChange={value=>set('active',value==='active')}/><Label text="PERFIL"/><Chips value={form.role} values={[['owner','Proprietário'],['admin','Administrador'],['commercial','Comercial'],['operational','Operacional'],['finance','Financeiro']]} onChange={value=>set('role',value)}/><Text style={styles.notice}>Ao inativar, as sessões existentes serão encerradas e o usuário perderá o acesso.</Text><Save label="Salvar alterações" onPress={()=>onUser(item.id,{active:form.active,role:form.role})}/></>:<><View style={styles.formGrid}>{[['maxClients','Limite de clientes'],['maxQuotesPerMonth','Orçamentos por mês'],['maxUsers','Usuários'],['monthlyPriceCents','Preço mensal'],['quarterlyPriceCents','Preço trimestral'],['semiannualPriceCents','Preço semestral'],['annualPriceCents','Preço anual']].map(([key,label])=><Field key={key} label={label.toUpperCase()} keyboardType="numeric" value={prices.has(key)?money(Number(form[key]??0)):String(form[key]??'')} onChangeText={value=>{const digits=value.replace(/[^\d]/g,'');set(key,prices.has(key)?Number(digits):Number(value.replace(/[^\d-]/g,'')))}}/>)}</View><Text style={styles.notice}>Valores exibidos em reais. Use -1 para limites ilimitados de clientes ou orçamentos.</Text><Save label="Salvar alterações" onPress={()=>onPlan(item.plan,{maxClients:form.maxClients,maxQuotesPerMonth:form.maxQuotesPerMonth,maxUsers:form.maxUsers,monthlyPriceCents:form.monthlyPriceCents,quarterlyPriceCents:form.quarterlyPriceCents,semiannualPriceCents:form.semiannualPriceCents,annualPriceCents:form.annualPriceCents})}/></>}</ScrollView></ModalShell></Modal>;
}

function ModalShell({onClose,children}:{onClose:()=>void;children:ReactNode}){return <View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={onClose}/><View style={styles.modal}>{children}</View></View>}
function ModalHeader({title,subtitle,onClose}:{title:string;subtitle:string;onClose:()=>void}){return <View style={styles.modalHead}><View style={styles.headerText}><Text style={styles.modalTitle}>{title}</Text><Text style={styles.small}>{subtitle}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Fechar" onPress={onClose} style={styles.close}><Ionicons name="close" size={20} color={theme.muted}/></Pressable></View>}
function Field({label,...props}:{label:string}&ComponentProps<typeof TextInput>){return <View style={styles.field}><Label text={label}/><TextInput placeholderTextColor={theme.muted} {...props} style={styles.input}/></View>}
function Label({text}:{text:string}){return <Text style={styles.formLabel}>{text}</Text>}
function Chips({value,values,onChange}:{value:string;values:readonly Option[];onChange:(value:string)=>void}){return <View style={styles.chips}>{values.map(([option,label])=><Pressable key={option} onPress={()=>onChange(option)} style={[styles.chip,value===option&&styles.chipOn]}><Text style={[styles.chipText,value===option&&styles.chipTextOn]}>{label}</Text></Pressable>)}</View>}
function Save({onPress,label,busy=false}:{onPress:()=>void;label:string;busy?:boolean}){return <Pressable disabled={busy} onPress={onPress} style={[styles.save,busy&&styles.disabled]}><Text style={styles.saveText}>{label}</Text></Pressable>}

const styles=StyleSheet.create({overlay:{flex:1,backgroundColor:'rgba(8,25,18,.6)',alignItems:'center',justifyContent:'center',padding:20},modal:{width:'100%',maxWidth:650,maxHeight:'90%',backgroundColor:'#fff',borderRadius:18,padding:22},modalContent:{paddingBottom:4},modalHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingBottom:16,borderBottomWidth:1,borderBottomColor:theme.border},headerText:{flex:1,paddingRight:12},modalTitle:{fontFamily:'serif',fontSize:21,fontWeight:'800',color:theme.ink},small:{fontSize:9.5,color:theme.muted,marginTop:3},close:{width:36,height:36,borderRadius:18,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},formGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},field:{width:'48%',minWidth:220,flexGrow:1},formLabel:{fontSize:9,fontWeight:'900',letterSpacing:.6,color:theme.muted,marginTop:17,marginBottom:7},input:{height:42,borderWidth:1,borderColor:theme.border,borderRadius:9,paddingHorizontal:11,fontSize:12,color:theme.ink,outlineStyle:'none' as never},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:theme.border,borderRadius:20,paddingHorizontal:12,paddingVertical:8},chipOn:{backgroundColor:theme.green2,borderColor:theme.green2},chipText:{fontSize:10,fontWeight:'700',color:theme.muted},chipTextOn:{color:'#fff'},notice:{fontSize:10,lineHeight:15,color:theme.muted,backgroundColor:'#FFF8E8',borderRadius:9,padding:11,marginTop:16},save:{height:44,backgroundColor:theme.gold,borderRadius:9,alignItems:'center',justifyContent:'center',marginTop:20},saveText:{fontSize:11,fontWeight:'900',color:'#183328'},disabled:{opacity:.55}});
