import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { compare, hash } from 'bcryptjs';
import { PrismaService } from '../../prisma.service';
import { entitlementSnapshot } from '../../entitlements';
import { isBillingPeriod, isPlanCode } from '../../plan-policy';
import { AUTH_SECURITY } from '../auth/auth-security';
import { SubscriptionService } from '../billing/subscription.service';
import { UpdateAccountDto } from './dto/account.dto';

type LogoFile={buffer:Buffer;mimetype:string;size:number};
@Injectable() export class AccountService {
 constructor(private db:PrismaService,private subscriptions:SubscriptionService){}
 private async audit(tenantId:string,actorUserId:string|undefined,action:string,entityId?:string,metadata?:any){await this.db.auditLog.create({data:{tenantId,actorUserId,action,entity:'tenant',entityId,metadata}}).catch(()=>undefined);}
 plans(){return this.db.planLimit.findMany({orderBy:{monthlyPriceCents:'asc'}});}
 async account(tenantId:string,userId?:string){
  const tenant=await this.subscriptions.activateScheduledIfDue(tenantId);if(!tenant)throw new NotFoundException('Conta não encontrada');
  const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});const month=new Date();month.setDate(1);month.setHours(0,0,0,0);const now=new Date();
  const[clients,quotes,users,pendingInvitations,currentUser]=await Promise.all([this.db.client.count({where:{tenantId,active:true}}),this.db.quote.count({where:{tenantId,createdAt:{gte:month}}}),this.db.user.count({where:{tenantId,active:true}}),this.db.userInvitation.count({where:{tenantId,status:'pending',expiresAt:{gt:now}}}),userId?this.db.user.findFirst({where:{id:userId,tenantId},select:{id:true,name:true,email:true,role:true,customProfileId:true,customProfile:{select:{id:true,name:true}},active:true,lastLoginAt:true,lockedUntil:true,passwordChangedAt:true}}):Promise.resolve(null)]);
  const entitlements=entitlementSnapshot(limit,{clients,quotes,users,pendingInvitations});return {tenant,limit,currentUser,usage:entitlements.usage,features:entitlements.features,entitlements};
 }
 async update(tenantId:string,data:UpdateAccountDto,actorUserId?:string){const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Conta não encontrada');const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});const customFields:(keyof UpdateAccountDto)[]=['primaryColor','secondaryColor','proposalText'];if(!limit?.customPdf&&customFields.some(field=>data[field]!==undefined))throw new ForbiddenException('Personalização avançada disponível nos planos Pro e Business');const common:(keyof UpdateAccountDto)[]=['name','responsibleName','phone','contactEmail','siteUrl','instagram','legalName','document','stateRegistration','municipalRegistration','zipCode','addressLine','addressNumber','addressComplement','neighborhood','city','state','proposalValidityDays','proposalPaymentTerms','proposalFooter','pixKey'];const patch:any={};for(const field of common)if(data[field]!==undefined)patch[field]=data[field]||null;if(data.proposalValidityDays!==undefined)patch.proposalValidityDays=data.proposalValidityDays;if(limit?.customPdf)for(const field of customFields)if(data[field]!==undefined)patch[field]=data[field]||null;const updated=await this.db.tenant.update({where:{id:tenantId},data:patch});await this.audit(tenantId,actorUserId,'update',tenantId);return updated;}
 async uploadLogo(tenantId:string,file:LogoFile|undefined,actorUserId?:string){const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Conta não encontrada');const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});if(limit?.logoPdf===false)throw new ForbiddenException('Logo na proposta indisponível neste plano');if(!file?.buffer||!file?.mimetype)throw new BadRequestException('Selecione uma imagem para o logo');if(!['image/png','image/jpeg','image/webp'].includes(file.mimetype))throw new BadRequestException('Formato inválido. Use PNG, JPG ou WebP.');if(file.size>2*1024*1024)throw new BadRequestException('O logo deve ter no máximo 2 MB');const updated=await this.db.tenant.update({where:{id:tenantId},data:{logoUrl:`data:${file.mimetype};base64,${file.buffer.toString('base64')}`}});await this.audit(tenantId,actorUserId,'upload_logo',tenantId,{mimeType:file.mimetype,size:file.size});return updated;}
 async removeLogo(tenantId:string,actorUserId?:string){const updated=await this.db.tenant.update({where:{id:tenantId},data:{logoUrl:null}}).catch(()=>null);if(!updated)throw new NotFoundException('Conta não encontrada');await this.audit(tenantId,actorUserId,'remove_logo',tenantId);return updated;}
 async changePassword(tenantId:string,userId:string,currentPassword:string,newPassword:string){const user=await this.db.user.findFirst({where:{id:userId,tenantId}});if(!user||!await compare(currentPassword,user.passwordHash))throw new BadRequestException('Senha atual inválida');if(currentPassword===newPassword)throw new BadRequestException('A nova senha deve ser diferente da atual');const now=new Date();await this.db.$transaction(async tx=>{await tx.user.update({where:{id:userId},data:{passwordHash:await hash(newPassword,AUTH_SECURITY.bcryptRounds),passwordChangedAt:now,failedLoginAttempts:0,lockedUntil:null}});await tx.authSession.updateMany({where:{userId,tenantId,revokedAt:null},data:{revokedAt:now,revokedReason:'password_changed'}});});await this.audit(tenantId,userId,'change_password',userId);return {ok:true};}
 async updatePlan(tenantId:string,plan:string,period='monthly',actorUserId?:string){if(!isPlanCode(plan))throw new BadRequestException('Plano inválido');if(!isBillingPeriod(period))throw new BadRequestException('Período inválido');const targetLimit=await this.db.planLimit.findUnique({where:{plan}});const now=new Date();const[activeUsers,pendingInvitations]=await Promise.all([this.db.user.count({where:{tenantId,active:true}}),this.db.userInvitation.count({where:{tenantId,status:'pending',expiresAt:{gt:now}}})]);const used=activeUsers+pendingInvitations;if(targetLimit&&targetLimit.maxUsers>=0&&used>targetLimit.maxUsers)throw new BadRequestException(`Cancele convites pendentes ou desative ${used-targetLimit.maxUsers} acesso(s) antes de mudar para este plano`);if(process.env.ALLOW_DIRECT_PLAN_CHANGE!=='true')throw new ForbiddenException('Alteração direta de plano desabilitada. Use o fluxo de cobrança ou o painel da plataforma.');const updated=await this.db.tenant.update({where:{id:tenantId},data:{plan,planPeriod:period}});await this.audit(tenantId,actorUserId,'change_plan',tenantId,{plan,period});return updated;}
}
