import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { compare, hash } from 'bcryptjs';
import { PrismaService } from './prisma.service';
type Calc={dailyRateCents:number;days:number;people:number;variableCostCents:number;fixedCostCents:number;safetyMarginBps:number};
@Injectable() export class ApiService {
  constructor(private db:PrismaService,private jwt:JwtService){}
  calculate(x:Calc){
    for(const v of Object.values(x)) if(!Number.isInteger(v)||v<0) throw new BadRequestException('Use inteiros não negativos; dinheiro em centavos.');
    const laborCents=x.dailyRateCents*x.days; const variableCents=x.variableCostCents*x.people*x.days; const subtotal=laborCents+variableCents+x.fixedCostCents;
    const marginCents=Math.round(x.dailyRateCents*x.safetyMarginBps/10000); return {laborCents,variableCents,fixedCents:x.fixedCostCents,marginCents,totalCents:subtotal+marginCents};
  }
  async login(email:string,password:string){const u=await this.db.user.findUnique({where:{email},include:{tenant:true}});if(!u||!await compare(password,u.passwordHash))throw new UnauthorizedException('E-mail ou senha inválidos');return {token:await this.jwt.signAsync({sub:u.id,tenantId:u.tenantId,role:u.role,plan:u.tenant.plan}),user:{name:u.name,email:u.email},tenant:u.tenant};}
  async register(data:any){const email=String(data.email??'').trim().toLowerCase(),password=String(data.password??''),name=String(data.name??'').trim(),company=String(data.company??'').trim();if(!email||!name||!company||password.length<8)throw new BadRequestException('Informe empresa, responsável, e-mail e senha com pelo menos 8 caracteres');if(await this.db.user.findUnique({where:{email}}))throw new ConflictException('Este e-mail já está cadastrado');const plan=['starter','pro','business'].includes(data.plan)?data.plan:'starter';const period=['monthly','quarterly','semiannual','annual'].includes(data.period)?data.period:'monthly';const limit=await this.db.planLimit.findUnique({where:{plan}});if(!limit)throw new BadRequestException('Plano indisponível');const amountCents=period==='annual'?limit.annualPriceCents:period==='semiannual'?limit.semiannualPriceCents:period==='quarterly'?limit.quarterlyPriceCents:limit.monthlyPriceCents;const now=new Date(),trialEnd=new Date(now);trialEnd.setDate(trialEnd.getDate()+14);const slug=`${company.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'empresa'}-${Date.now().toString(36)}`;const result=await this.db.$transaction(async tx=>{const tenant=await tx.tenant.create({data:{name:company,slug,responsibleName:name,phone:data.phone,contactEmail:email,plan,planPeriod:period,subscriptionExpiresAt:trialEnd}});const user=await tx.user.create({data:{tenantId:tenant.id,name,email,passwordHash:await hash(password,12),role:'owner'}});await tx.subscription.create({data:{tenantId:tenant.id,plan,period,amountCents,status:'trial',startsAt:now,expiresAt:trialEnd}});return {tenant,user}});return {token:await this.jwt.signAsync({sub:result.user.id,tenantId:result.tenant.id,role:result.user.role,plan}),user:{name:result.user.name,email:result.user.email},tenant:result.tenant};}
  plans(){return this.db.planLimit.findMany({orderBy:{monthlyPriceCents:'asc'}});}
  async account(tenantId:string){const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Conta não encontrada');const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});const month=new Date();month.setDate(1);month.setHours(0,0,0,0);const[clients,quotes,users]=await Promise.all([this.db.client.count({where:{tenantId,active:true}}),this.db.quote.count({where:{tenantId,createdAt:{gte:month}}}),this.db.user.count({where:{tenantId}})]);return {tenant,limit,usage:{clients,quotes,users},features:{customPdf:!!limit?.customPdf,projectManagement:limit?.projectManagement??'basic',advancedReports:!!limit?.advancedReports}};}
  async updateAccount(tenantId:string,data:any){const tenant=await this.db.tenant.findUnique({where:{id:tenantId},include:{}});if(!tenant)throw new NotFoundException('Conta não encontrada');const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});const customFields=['primaryColor','secondaryColor','proposalText','logoUrl'];if(!limit?.customPdf&&customFields.some(field=>data[field]!==undefined))throw new ForbiddenException('Personalização de marca disponível nos planos Pro e Business');return this.db.tenant.update({where:{id:tenantId},data:{name:data.name??tenant.name,responsibleName:data.responsibleName??tenant.responsibleName,phone:data.phone??tenant.phone,contactEmail:data.contactEmail??tenant.contactEmail,siteUrl:data.siteUrl??tenant.siteUrl,instagram:data.instagram??tenant.instagram,...(limit?.customPdf?{primaryColor:data.primaryColor??tenant.primaryColor,secondaryColor:data.secondaryColor??tenant.secondaryColor,proposalText:data.proposalText??tenant.proposalText}: {})}});}
  async updatePlan(tenantId:string,plan:string,period='monthly'){if(!['starter','pro','business'].includes(plan))throw new BadRequestException('Plano inválido');if(!['monthly','quarterly','semiannual','annual'].includes(period))throw new BadRequestException('Período inválido');return this.db.tenant.update({where:{id:tenantId},data:{plan,planPeriod:period}});}
  dashboard(tenantId:string){
    return Promise.all([
      this.db.client.count({where:{tenantId}}),
      this.db.quote.findMany({where:{tenantId},include:{client:true},orderBy:{createdAt:'desc'},take:5}),
      this.db.project.findMany({where:{tenantId},include:{client:true},orderBy:{progress:'desc'}})
    ]).then(([clients,quotes,projects])=>({clients,quotes,projects,approvedRevenueCents:quotes.filter(q=>q.status==='approved').reduce((s,q)=>s+(q.finalTotalCents||q.totalCents),0)}));
  }
  clients(tenantId:string){return this.db.client.findMany({where:{tenantId},orderBy:{name:'asc'}});}
  async createClient(tenantId:string,data:any){await this.assertLimit(tenantId,'clients');return this.db.client.create({data:{tenantId,name:data.name,phone:data.phone,email:data.email,city:data.city,address:data.address,notes:data.notes}});}
  async updateClient(tenantId:string,id:string,data:any){const client=await this.db.client.findFirst({where:{id,tenantId}});if(!client)throw new NotFoundException('Cliente não encontrada');return this.db.client.update({where:{id},data:{name:data.name,phone:data.phone||null,email:data.email||null,city:data.city||null,address:data.address||null,notes:data.notes||null}});}
  services(tenantId:string){return this.db.service.findMany({where:{tenantId,active:true},include:{team:true,costs:true,stages:{orderBy:{sequence:'asc'}}},orderBy:{name:'asc'}});}
  quotes(tenantId:string){return this.db.quote.findMany({where:{tenantId},include:{client:true,items:true},orderBy:{createdAt:'desc'}});}
  async quote(tenantId:string,id:string){const quote=await this.db.quote.findFirst({where:{tenantId,id},include:{client:true,items:{include:{stages:{orderBy:{sequence:'asc'}}}},project:true}});if(!quote)throw new NotFoundException('Orçamento não encontrado');return quote;}
  projects(tenantId:string){return this.db.project.findMany({where:{tenantId},include:{client:true,quote:true},orderBy:{name:'asc'}});}
  async createQuote(tenantId:string,data:any){
    await this.assertLimit(tenantId,'quotes');
    const client=await this.db.client.findFirst({where:{id:data.clientId,tenantId}});if(!client)throw new NotFoundException('Cliente não encontrado');
    const items=[];for(const input of data.items){const service=await this.db.service.findFirst({where:{id:input.serviceId,tenantId},include:{stages:{orderBy:{sequence:'asc'}}}});if(!service)throw new NotFoundException('Serviço não encontrado');const days=input.days??service.defaultDays,people=input.people??service.people;const calc=this.calculate({dailyRateCents:input.dailyRateCents??service.dailyRateCents,days,people,variableCostCents:input.variableCostCents??service.variableCostCents,fixedCostCents:input.fixedCostCents??service.fixedCostCents,safetyMarginBps:input.safetyMarginBps??service.safetyMarginBps});items.push({serviceName:service.name,days,people,...calc,configurationJson:{serviceId:service.id},stages:{create:service.stages.map(s=>({sequence:s.sequence,description:s.description,duration:s.duration}))}});}
    const totalCents=items.reduce((s,i)=>s+i.totalCents,0);const discountBps=Math.max(0,Math.min(10000,Number(data.discountBps??0)));const finalTotalCents=Math.round(totalCents*(10000-discountBps)/10000);const count=await this.db.quote.count({where:{tenantId}});return this.db.quote.create({data:{tenantId,clientId:client.id,number:`ORC-${new Date().getFullYear()}-${String(count+1).padStart(3,'0')}`,totalCents,discountBps,finalTotalCents,validityDays:Number(data.validityDays??30),notes:data.notes,items:{create:items}},include:{client:true,items:{include:{stages:true}}}});
  }
  async approve(tenantId:string,id:string){const quote=await this.db.quote.findFirst({where:{id,tenantId},include:{client:true}});if(!quote)throw new NotFoundException();if(!['draft','sent','approved'].includes(quote.status))throw new BadRequestException('Transição de status inválida');return this.db.$transaction(async tx=>{const q=await tx.quote.update({where:{id},data:{status:'approved',approvedAt:quote.approvedAt??new Date()}});await tx.project.upsert({where:{quoteId:id},update:{},create:{tenantId,clientId:quote.clientId,quoteId:id,name:`${quote.number} — ${quote.client.name}`}});return q;});}
  private async assertLimit(tenantId:string,resource:'clients'|'quotes'){
    const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Tenant não encontrada');
    const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});if(!limit)return;
    if(resource==='clients'&&limit.maxClients>=0&&await this.db.client.count({where:{tenantId,active:true}})>=limit.maxClients)throw new BadRequestException('Limite de clientes do plano atingido');
    if(resource==='quotes'&&limit.maxQuotesPerMonth>=0){const start=new Date();start.setDate(1);start.setHours(0,0,0,0);if(await this.db.quote.count({where:{tenantId,createdAt:{gte:start}}})>=limit.maxQuotesPerMonth)throw new BadRequestException('Limite mensal de orçamentos atingido');}
  }
}
