import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { compare, hash } from 'bcryptjs';
import { randomBytes } from 'crypto';
import { PrismaService } from './prisma.service';
type Calc={dailyRateCents:number;days:number;people:number;variableCostCents:number;fixedCostCents:number;safetyMarginBps:number};
@Injectable() export class ApiService {
  constructor(private db:PrismaService,private jwt:JwtService){}
  private refreshSecret(){const secret=process.env.JWT_REFRESH_SECRET??(process.env.NODE_ENV==='production'?undefined:'local-dev-refresh-secret');if(!secret)throw new Error('JWT_REFRESH_SECRET não configurado');return secret;}
  private async issueSession(u:any){
    const payload={sub:u.id,tenantId:u.tenantId,role:u.role,plan:u.tenant.plan};
    const token=await this.jwt.signAsync({...payload,typ:'access'},{expiresIn:'15m'});
    const refreshToken=await this.jwt.signAsync({...payload,typ:'refresh'},{secret:this.refreshSecret(),expiresIn:'30d'});
    await this.db.user.update({where:{id:u.id},data:{refreshTokenHash:await hash(refreshToken,10)}});
    return {token,refreshToken,user:{id:u.id,name:u.name,email:u.email,role:u.role},tenant:u.tenant};
  }
  private async audit(tenantId:string,actorUserId:string|undefined,action:string,entity:string,entityId?:string,metadata?:any){
    await this.db.auditLog.create({data:{tenantId,actorUserId,action,entity,entityId,metadata}}).catch(()=>undefined);
  }
  calculate(x:Calc){for(const v of Object.values(x))if(!Number.isInteger(v)||v<0)throw new BadRequestException('Use inteiros não negativos; dinheiro em centavos.');const laborCents=x.dailyRateCents*x.days;const variableCents=x.variableCostCents*x.people*x.days;const subtotal=laborCents+variableCents+x.fixedCostCents;const marginCents=Math.round(x.dailyRateCents*x.safetyMarginBps/10000);return {laborCents,variableCents,fixedCents:x.fixedCostCents,marginCents,totalCents:subtotal+marginCents};}
  async login(email:string,password:string){const u=await this.db.user.findUnique({where:{email:email.trim().toLowerCase()},include:{tenant:true}});if(!u||!u.active||!await compare(password,u.passwordHash))throw new UnauthorizedException('E-mail ou senha inválidos');return this.issueSession(u);}
  async refresh(refreshToken:string){
    let payload:any;try{payload=await this.jwt.verifyAsync(refreshToken,{secret:this.refreshSecret()});}catch{throw new UnauthorizedException('Sessão expirada');}
    if(payload.typ!=='refresh')throw new UnauthorizedException('Token de renovação inválido');
    const u=await this.db.user.findUnique({where:{id:payload.sub},include:{tenant:true}});if(!u?.active||!u.refreshTokenHash||!await compare(refreshToken,u.refreshTokenHash))throw new UnauthorizedException('Sessão revogada');
    if(u.tenant.status!=='active'||(u.tenant.subscriptionExpiresAt&&u.tenant.subscriptionExpiresAt.getTime()<Date.now()))throw new ForbiddenException('Conta indisponível ou assinatura expirada');
    return this.issueSession(u);
  }
  async logout(userId:string,tenantId:string){await this.db.user.updateMany({where:{id:userId,tenantId},data:{refreshTokenHash:null}});await this.audit(tenantId,userId,'logout','user',userId);return {ok:true};}
  async register(data:any){const email=String(data.email??'').trim().toLowerCase(),password=String(data.password??''),name=String(data.name??'').trim(),company=String(data.company??'').trim();if(!email||!name||!company||password.length<8)throw new BadRequestException('Informe empresa, responsável, e-mail e senha com pelo menos 8 caracteres');if(await this.db.user.findUnique({where:{email}}))throw new ConflictException('Este e-mail já está cadastrado');const plan=['starter','pro','business'].includes(data.plan)?data.plan:'starter';const period=['monthly','quarterly','semiannual','annual'].includes(data.period)?data.period:'monthly';const limit=await this.db.planLimit.findUnique({where:{plan}});if(!limit)throw new BadRequestException('Plano indisponível');const amountCents=period==='annual'?limit.annualPriceCents:period==='semiannual'?limit.semiannualPriceCents:period==='quarterly'?limit.quarterlyPriceCents:limit.monthlyPriceCents;const now=new Date(),trialEnd=new Date(now);trialEnd.setDate(trialEnd.getDate()+14);const slug=`${company.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'empresa'}-${Date.now().toString(36)}`;const result=await this.db.$transaction(async tx=>{const tenant=await tx.tenant.create({data:{name:company,slug,responsibleName:name,phone:data.phone,contactEmail:email,plan,planPeriod:period,subscriptionExpiresAt:trialEnd}});const user=await tx.user.create({data:{tenantId:tenant.id,name,email,passwordHash:await hash(password,12),role:'owner'}});await tx.subscription.create({data:{tenantId:tenant.id,plan,period,amountCents,status:'trial',startsAt:now,expiresAt:trialEnd}});return {tenant,user}});await this.audit(result.tenant.id,result.user.id,'register','tenant',result.tenant.id,{plan,period});return this.issueSession({...result.user,tenant:result.tenant});}
  plans(){return this.db.planLimit.findMany({orderBy:{monthlyPriceCents:'asc'}});}
  async account(tenantId:string,userId?:string){const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Conta não encontrada');const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});const month=new Date();month.setDate(1);month.setHours(0,0,0,0);const[clients,quotes,users,currentUser]=await Promise.all([this.db.client.count({where:{tenantId,active:true}}),this.db.quote.count({where:{tenantId,createdAt:{gte:month}}}),this.db.user.count({where:{tenantId,active:true}}),userId?this.db.user.findFirst({where:{id:userId,tenantId},select:{id:true,name:true,email:true,role:true,active:true}}):Promise.resolve(null)]);return {tenant,limit,currentUser,usage:{clients,quotes,users},features:{customPdf:!!limit?.customPdf,logoPdf:limit?.logoPdf!==false,premiumTemplates:!!limit?.premiumTemplates,projectManagement:limit?.projectManagement??'basic',advancedReports:!!limit?.advancedReports,exportData:!!limit?.exportData}};}
  async updateAccount(tenantId:string,data:any,actorUserId?:string){
    const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Conta não encontrada');
    const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});
    const customFields=['primaryColor','secondaryColor','proposalText'];
    if(!limit?.customPdf&&customFields.some(field=>data[field]!==undefined))throw new ForbiddenException('Personalização avançada disponível nos planos Pro e Business');
    const common=['name','responsibleName','phone','contactEmail','siteUrl','instagram','legalName','document','stateRegistration','municipalRegistration','zipCode','addressLine','addressNumber','addressComplement','neighborhood','city','state','proposalValidityDays','proposalPaymentTerms','proposalFooter','pixKey'];
    const patch:any={}; for(const field of common) if(data[field]!==undefined) patch[field]=data[field]||null;
    if(data.proposalValidityDays!==undefined)patch.proposalValidityDays=data.proposalValidityDays;
    if(limit?.customPdf){for(const field of customFields)if(data[field]!==undefined)patch[field]=data[field]||null;}
    const updated=await this.db.tenant.update({where:{id:tenantId},data:patch});
    await this.audit(tenantId,actorUserId,'update','tenant',tenantId);return updated;
  }
  async uploadLogo(tenantId:string,file:any,actorUserId?:string){
    const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Conta não encontrada');
    const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});if(limit?.logoPdf===false)throw new ForbiddenException('Logo na proposta indisponível neste plano');
    if(!file?.buffer||!file?.mimetype)throw new BadRequestException('Selecione uma imagem para o logo');
    const allowed=['image/png','image/jpeg','image/webp'];if(!allowed.includes(file.mimetype))throw new BadRequestException('Formato inválido. Use PNG, JPG ou WebP.');
    if(file.size>2*1024*1024)throw new BadRequestException('O logo deve ter no máximo 2 MB');
    const logoUrl=`data:${file.mimetype};base64,${file.buffer.toString('base64')}`;
    const updated=await this.db.tenant.update({where:{id:tenantId},data:{logoUrl}});
    await this.audit(tenantId,actorUserId,'upload_logo','tenant',tenantId,{mimeType:file.mimetype,size:file.size});return updated;
  }
  async removeLogo(tenantId:string,actorUserId?:string){
    const updated=await this.db.tenant.update({where:{id:tenantId},data:{logoUrl:null}}).catch(()=>null);if(!updated)throw new NotFoundException('Conta não encontrada');
    await this.audit(tenantId,actorUserId,'remove_logo','tenant',tenantId);return updated;
  }
  async changePassword(tenantId:string,userId:string,currentPassword:string,newPassword:string){const user=await this.db.user.findFirst({where:{id:userId,tenantId}});if(!user||!await compare(currentPassword,user.passwordHash))throw new BadRequestException('Senha atual inválida');if(currentPassword===newPassword)throw new BadRequestException('A nova senha deve ser diferente da atual');await this.db.user.update({where:{id:userId},data:{passwordHash:await hash(newPassword,12),refreshTokenHash:null}});await this.audit(tenantId,userId,'change_password','user',userId);return {ok:true};}

  async updatePlan(tenantId:string,plan:string,period='monthly',actorUserId?:string){if(!['starter','pro','business'].includes(plan))throw new BadRequestException('Plano inválido');if(!['monthly','quarterly','semiannual','annual'].includes(period))throw new BadRequestException('Período inválido');if(process.env.NODE_ENV==='production'&&process.env.ALLOW_DIRECT_PLAN_CHANGE!=='true')throw new ForbiddenException('Alteração direta de plano desabilitada em produção');const updated=await this.db.tenant.update({where:{id:tenantId},data:{plan,planPeriod:period}});await this.audit(tenantId,actorUserId,'change_plan','tenant',tenantId,{plan,period});return updated;}
  users(tenantId:string){return this.db.user.findMany({where:{tenantId},select:{id:true,name:true,email:true,role:true,active:true,createdAt:true,updatedAt:true},orderBy:[{role:'asc'},{name:'asc'}]});}
  async createUser(tenantId:string,data:any,actorUserId:string){const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Conta não encontrada');const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});const current=await this.db.user.count({where:{tenantId,active:true}});if(limit&&limit.maxUsers>=0&&current>=limit.maxUsers)throw new BadRequestException('Limite de usuários do plano atingido');const email=String(data.email).trim().toLowerCase();if(await this.db.user.findUnique({where:{email}}))throw new ConflictException('Este e-mail já está cadastrado');const user=await this.db.user.create({data:{tenantId,name:data.name.trim(),email,passwordHash:await hash(data.password,12),role:data.role,active:true},select:{id:true,name:true,email:true,role:true,active:true,createdAt:true,updatedAt:true}});await this.audit(tenantId,actorUserId,'create','user',user.id,{role:user.role,email:user.email});return user;}
  async updateUser(tenantId:string,id:string,data:any,actorUserId:string){const user=await this.db.user.findFirst({where:{id,tenantId}});if(!user)throw new NotFoundException('Usuário não encontrado');if(user.role==='owner'&&id!==actorUserId)throw new ForbiddenException('O usuário proprietário não pode ser alterado');if(id===actorUserId&&(data.active===false||data.role&&data.role!=='owner'))throw new BadRequestException('Você não pode remover seu próprio acesso de proprietário');const updated=await this.db.user.update({where:{id},data:{name:data.name??user.name,role:user.role==='owner'?'owner':(data.role??user.role),active:data.active??user.active,...(data.active===false?{refreshTokenHash:null}:{})},select:{id:true,name:true,email:true,role:true,active:true,createdAt:true,updatedAt:true}});await this.audit(tenantId,actorUserId,'update','user',id,{role:updated.role,active:updated.active});return updated;}
  async auditLogs(tenantId:string){const[logs,users]=await Promise.all([this.db.auditLog.findMany({where:{tenantId},orderBy:{createdAt:'desc'},take:100}),this.db.user.findMany({where:{tenantId},select:{id:true,name:true,email:true}})]);const actors=new Map(users.map(u=>[u.id,u]));return logs.map(log=>({...log,actor:log.actorUserId?actors.get(log.actorUserId)??null:null}));}
  async dashboard(tenantId:string){
    const now=new Date();const soon=new Date(now.getTime()+7*86400000);
    const monthStart=new Date(now.getFullYear(),now.getMonth(),1);
    const nextMonthStart=new Date(now.getFullYear(),now.getMonth()+1,1);
    const prevMonthStart=new Date(now.getFullYear(),now.getMonth()-1,1);
    const startOfToday=new Date(now.getFullYear(),now.getMonth(),now.getDate());
    const [clients,quotes,projects,revenue,totalQuotes,approvedQuotes,draftQuotes,sentQuotes,rejectedQuotes,openValue,expiringQuotes,currentMonthClients,previousMonthClients,currentMonthQuotes,previousMonthQuotes,currentMonthRevenue,previousMonthRevenue,overdueProjects]=await Promise.all([
      this.db.client.count({where:{tenantId,active:true}}),
      this.db.quote.findMany({where:{tenantId},include:{client:true},orderBy:{createdAt:'desc'},take:5}),
      this.db.project.findMany({where:{tenantId,status:{in:['scheduled','in_progress']}},include:{client:true,tasks:{where:{tenantId,status:{not:'completed'}},orderBy:{dueDate:'asc'}}},orderBy:[{progress:'desc'},{name:'asc'}]}),
      this.db.quote.aggregate({where:{tenantId,status:'approved'},_sum:{finalTotalCents:true}}),
      this.db.quote.count({where:{tenantId}}),this.db.quote.count({where:{tenantId,status:'approved'}}),
      this.db.quote.count({where:{tenantId,status:'draft'}}),this.db.quote.count({where:{tenantId,status:'sent'}}),this.db.quote.count({where:{tenantId,status:'rejected'}}),
      this.db.quote.aggregate({where:{tenantId,status:{in:['draft','sent']}},_sum:{finalTotalCents:true}}),
      this.db.quote.findMany({where:{tenantId,status:'sent',clientDecision:null,validUntil:{gte:now,lte:soon}},include:{client:true},orderBy:{validUntil:'asc'},take:5}),
      this.db.client.count({where:{tenantId,createdAt:{gte:monthStart,lt:nextMonthStart}}}),
      this.db.client.count({where:{tenantId,createdAt:{gte:prevMonthStart,lt:monthStart}}}),
      this.db.quote.count({where:{tenantId,createdAt:{gte:monthStart,lt:nextMonthStart}}}),
      this.db.quote.count({where:{tenantId,createdAt:{gte:prevMonthStart,lt:monthStart}}}),
      this.db.quote.aggregate({where:{tenantId,status:'approved',approvedAt:{gte:monthStart,lt:nextMonthStart}},_sum:{finalTotalCents:true}}),
      this.db.quote.aggregate({where:{tenantId,status:'approved',approvedAt:{gte:prevMonthStart,lt:monthStart}},_sum:{finalTotalCents:true}}),
      this.db.project.findMany({where:{tenantId,status:{in:['scheduled','in_progress']}},include:{client:true,tasks:{where:{tenantId,status:{not:'completed'}},orderBy:{dueDate:'asc'}}},orderBy:[{endDate:'asc'},{name:'asc'}]})
    ]);
    const delta=(current:number,previous:number)=>previous===0?(current===0?0:100):Math.round((current-previous)*100/previous);
    const currentRevenue=currentMonthRevenue._sum.finalTotalCents??0;const previousRevenue=previousMonthRevenue._sum.finalTotalCents??0;
    const overdue=overdueProjects.filter((project:any)=>project.endDate&&new Date(project.endDate)<startOfToday||project.tasks?.some((task:any)=>task.dueDate&&new Date(task.dueDate)<startOfToday)).map((project:any)=>({...project,tasks:(project.tasks??[]).filter((task:any)=>task.dueDate&&new Date(task.dueDate)<startOfToday)})).slice(0,5);
    return {clients,quotes,projects,approvedRevenueCents:revenue._sum.finalTotalCents??0,openPipelineCents:openValue._sum.finalTotalCents??0,totalQuotes,approvedQuotes,pipeline:{draft:draftQuotes,sent:sentQuotes,approved:approvedQuotes,rejected:rejectedQuotes},expiringQuotes,overdueProjects:overdue,period:{currentMonth:{clients:currentMonthClients,quotes:currentMonthQuotes,approvedRevenueCents:currentRevenue},previousMonth:{clients:previousMonthClients,quotes:previousMonthQuotes,approvedRevenueCents:previousRevenue},delta:{clients:delta(currentMonthClients,previousMonthClients),quotes:delta(currentMonthQuotes,previousMonthQuotes),approvedRevenue:delta(currentRevenue,previousRevenue)}}};
  }

  clients(tenantId:string){return this.db.client.findMany({where:{tenantId},orderBy:{name:'asc'}});}
  private clientData(data:any){return {type:data.type??'individual',name:String(data.name).trim(),legalName:data.legalName?.trim()||null,document:data.document?.trim()||null,stateRegistration:data.stateRegistration?.trim()||null,municipalRegistration:data.municipalRegistration?.trim()||null,contactName:data.contactName?.trim()||null,phone:data.phone?.trim()||null,whatsapp:data.whatsapp?.trim()||null,email:data.email?.trim()||null,zipCode:data.zipCode?.trim()||null,addressLine:data.addressLine?.trim()||null,addressNumber:data.addressNumber?.trim()||null,addressComplement:data.addressComplement?.trim()||null,neighborhood:data.neighborhood?.trim()||null,city:data.city?.trim()||null,state:data.state?.trim()||null,address:[data.addressLine,data.addressNumber,data.neighborhood].filter(Boolean).join(', ')||null,notes:data.notes?.trim()||null};}
  async createClient(tenantId:string,data:any,actorUserId?:string){await this.assertLimit(tenantId,'clients');const client=await this.db.client.create({data:{tenantId,...this.clientData(data)}});await this.audit(tenantId,actorUserId,'create','client',client.id,{type:client.type,document:client.document});return client;}
  async updateClient(tenantId:string,id:string,data:any,actorUserId?:string){const client=await this.db.client.findFirst({where:{id,tenantId}});if(!client)throw new NotFoundException('Cliente não encontrado');const updated=await this.db.client.update({where:{id},data:this.clientData(data)});await this.audit(tenantId,actorUserId,'update','client',id,{type:updated.type,document:updated.document});return updated;}
  services(tenantId:string){return this.db.service.findMany({where:{tenantId},include:{team:{where:{tenantId},orderBy:{role:'asc'}},costs:{where:{tenantId},orderBy:{description:'asc'}},stages:{where:{tenantId},orderBy:{sequence:'asc'}}},orderBy:[{active:'desc'},{name:'asc'}]});}
  private normalizeServiceData(tenantId:string,data:any){
    const team=(data.team??[]).map((x:any)=>({tenantId,role:String(x.role).trim(),dailyRateCents:Number(x.dailyRateCents),included:x.included!==false}));
    const costs=(data.costs??[]).map((x:any)=>({tenantId,type:x.type,description:String(x.description).trim(),amountCents:Number(x.amountCents)}));
    const stages=(data.stages??[]).map((x:any,i:number)=>({tenantId,sequence:Number(x.sequence??i+1),description:String(x.description).trim(),duration:x.duration||null})).sort((a:any,b:any)=>a.sequence-b.sequence);
    const teamDaily=team.filter((x:any)=>x.included).reduce((sum:number,x:any)=>sum+x.dailyRateCents,0);
    const variable=costs.filter((x:any)=>x.type==='variable').reduce((sum:number,x:any)=>sum+x.amountCents,0);
    const fixed=costs.filter((x:any)=>x.type==='fixed').reduce((sum:number,x:any)=>sum+x.amountCents,0);
    return {name:String(data.name).trim(),code:data.code?.trim()||null,description:data.description?.trim()||null,category:data.category?.trim()||null,billingUnit:data.billingUnit??'daily',dailyRateCents:team.length?teamDaily:Number(data.dailyRateCents),defaultDays:Number(data.defaultDays),people:Number(data.people),variableCostCents:costs.length?variable:Number(data.variableCostCents),fixedCostCents:costs.length?fixed:Number(data.fixedCostCents),safetyMarginBps:Number(data.safetyMarginBps),active:data.active!==false,team,costs,stages};
  }
  async createService(tenantId:string,data:any,actorUserId?:string){const n=this.normalizeServiceData(tenantId,data);const service=await this.db.service.create({data:{tenantId,name:n.name,code:n.code,description:n.description,category:n.category,billingUnit:n.billingUnit,dailyRateCents:n.dailyRateCents,defaultDays:n.defaultDays,people:n.people,variableCostCents:n.variableCostCents,fixedCostCents:n.fixedCostCents,safetyMarginBps:n.safetyMarginBps,active:n.active,team:{create:n.team},costs:{create:n.costs},stages:{create:n.stages}},include:{team:true,costs:true,stages:{orderBy:{sequence:'asc'}}}});await this.audit(tenantId,actorUserId,'create','service',service.id,{name:service.name});return service;}
  async updateService(tenantId:string,id:string,data:any,actorUserId?:string){const current=await this.db.service.findFirst({where:{id,tenantId}});if(!current)throw new NotFoundException('Serviço não encontrado');const n=this.normalizeServiceData(tenantId,data);const service=await this.db.$transaction(async tx=>{await Promise.all([tx.serviceTeamMember.deleteMany({where:{tenantId,serviceId:id}}),tx.serviceCost.deleteMany({where:{tenantId,serviceId:id}}),tx.serviceStage.deleteMany({where:{tenantId,serviceId:id}})]);return tx.service.update({where:{id},data:{name:n.name,code:n.code,description:n.description,category:n.category,billingUnit:n.billingUnit,dailyRateCents:n.dailyRateCents,defaultDays:n.defaultDays,people:n.people,variableCostCents:n.variableCostCents,fixedCostCents:n.fixedCostCents,safetyMarginBps:n.safetyMarginBps,active:n.active,team:{create:n.team},costs:{create:n.costs},stages:{create:n.stages}},include:{team:true,costs:true,stages:{orderBy:{sequence:'asc'}}}})});await this.audit(tenantId,actorUserId,'update','service',id,{name:service.name,active:service.active});return service;}
  quotes(tenantId:string){return this.db.quote.findMany({where:{tenantId},include:{client:true,items:true},orderBy:{createdAt:'desc'}});}
  async quote(tenantId:string,id:string){const quote=await this.db.quote.findFirst({where:{tenantId,id},include:{client:true,items:{where:{tenantId},include:{stages:{where:{tenantId},orderBy:{sequence:'asc'}}}},project:true}});if(!quote)throw new NotFoundException('Orçamento não encontrado');return quote;}
  async shareQuote(tenantId:string,id:string,actorUserId?:string){const quote=await this.db.quote.findFirst({where:{id,tenantId}});if(!quote)throw new NotFoundException('Orçamento não encontrado');if(['approved','rejected'].includes(quote.status))throw new BadRequestException('Esta proposta já foi finalizada');const now=new Date();const validUntil=quote.validUntil??new Date(now.getTime()+quote.validityDays*86400000);const publicToken=quote.publicToken??randomBytes(24).toString('hex');const updated=await this.db.quote.update({where:{id},data:{publicToken,publicSharedAt:quote.publicSharedAt??now,status:'sent',sentAt:quote.sentAt??now,validUntil}});await this.audit(tenantId,actorUserId,'share','quote',id,{number:updated.number,reused:!!quote.publicToken});return {token:publicToken,path:`/p/${publicToken}`,validUntil:updated.validUntil};}
  async revokeQuoteShare(tenantId:string,id:string,actorUserId?:string){const quote=await this.db.quote.findFirst({where:{id,tenantId}});if(!quote)throw new NotFoundException('Orçamento não encontrado');if(!quote.publicToken)return {ok:true};await this.db.quote.update({where:{id},data:{publicToken:null,publicSharedAt:null}});await this.audit(tenantId,actorUserId,'revoke_share','quote',id,{number:quote.number});return {ok:true};}
  async publicProposal(token:string){const q=await this.db.quote.findUnique({where:{publicToken:token},include:{tenant:true,client:true,items:{include:{stages:{orderBy:{sequence:'asc'}}}}}});if(!q)throw new NotFoundException('Proposta não encontrada');const now=Date.now();const expired=!!q.validUntil&&q.validUntil.getTime()<now;const remainingDays=q.validUntil?Math.max(0,Math.ceil((q.validUntil.getTime()-now)/86400000)):null;return {number:q.number,status:q.status,totalCents:q.totalCents,discountBps:q.discountBps,finalTotalCents:q.finalTotalCents,validityDays:q.validityDays,notes:q.notes,sentAt:q.sentAt,validUntil:q.validUntil,expired,remainingDays,clientDecision:q.clientDecision,clientDecisionAt:q.clientDecisionAt,clientDecisionName:q.clientDecisionName,client:{name:q.client.name,type:q.client.type,legalName:q.client.legalName,document:q.client.document,city:q.client.city,state:q.client.state,addressLine:q.client.addressLine,addressNumber:q.client.addressNumber,neighborhood:q.client.neighborhood},tenant:{name:q.tenant.name,legalName:q.tenant.legalName,document:q.tenant.document,stateRegistration:q.tenant.stateRegistration,municipalRegistration:q.tenant.municipalRegistration,addressLine:q.tenant.addressLine,addressNumber:q.tenant.addressNumber,addressComplement:q.tenant.addressComplement,neighborhood:q.tenant.neighborhood,city:q.tenant.city,state:q.tenant.state,responsibleName:q.tenant.responsibleName,phone:q.tenant.phone,contactEmail:q.tenant.contactEmail,siteUrl:q.tenant.siteUrl,instagram:q.tenant.instagram,proposalText:q.tenant.proposalText,proposalPaymentTerms:q.tenant.proposalPaymentTerms,proposalFooter:q.tenant.proposalFooter,pixKey:q.tenant.pixKey,primaryColor:q.tenant.primaryColor,secondaryColor:q.tenant.secondaryColor,logoUrl:q.tenant.logoUrl},items:q.items.map(i=>({serviceName:i.serviceName,days:i.days,people:i.people,totalCents:i.totalCents,stages:i.stages.map(st=>({sequence:st.sequence,description:st.description,duration:st.duration}))}))};}
  async decidePublicProposal(token:string,decision:'approved'|'rejected',name:string){const quote=await this.db.quote.findUnique({where:{publicToken:token},include:{client:true}});if(!quote)throw new NotFoundException('Proposta não encontrada');if(quote.clientDecision||['approved','rejected'].includes(quote.status))throw new ConflictException('Esta proposta já recebeu uma resposta');if(quote.status!=='sent')throw new BadRequestException('Esta proposta ainda não está disponível para resposta');if(quote.validUntil&&quote.validUntil.getTime()<Date.now())throw new BadRequestException('Esta proposta está vencida');const now=new Date();if(decision==='approved'){await this.db.$transaction(async tx=>{await tx.quote.update({where:{id:quote.id},data:{status:'approved',approvedAt:now,clientDecision:'approved',clientDecisionAt:now,clientDecisionName:name.trim()}});await tx.project.upsert({where:{quoteId:quote.id},update:{},create:{tenantId:quote.tenantId,clientId:quote.clientId,quoteId:quote.id,name:`${quote.number} — ${quote.client.name}`}})});}else await this.db.quote.update({where:{id:quote.id},data:{status:'rejected',clientDecision:'rejected',clientDecisionAt:now,clientDecisionName:name.trim()}});await this.audit(quote.tenantId,undefined,`client_${decision}`,'quote',quote.id,{name:name.trim(),number:quote.number});return {ok:true,status:decision};}
  projects(tenantId:string){return this.db.project.findMany({where:{tenantId},include:{client:true,quote:true,tasks:{where:{tenantId},orderBy:[{status:'asc'},{dueDate:'asc'},{createdAt:'asc'}]}},orderBy:{name:'asc'}});}
  async project(tenantId:string,id:string){const project=await this.db.project.findFirst({where:{id,tenantId},include:{client:true,quote:true,tasks:{where:{tenantId},orderBy:[{status:'asc'},{priority:'desc'},{dueDate:'asc'},{createdAt:'asc'}]},activityNotes:{where:{tenantId},orderBy:{createdAt:'desc'},take:30}}});if(!project)throw new NotFoundException('Projeto não encontrado');return project;}
  async quoteTimeline(tenantId:string,id:string){const quote=await this.db.quote.findFirst({where:{id,tenantId},select:{id:true,createdAt:true,updatedAt:true,sentAt:true,approvedAt:true,clientDecision:true,clientDecisionAt:true,clientDecisionName:true,status:true,version:true}});if(!quote)throw new NotFoundException('Orçamento não encontrado');const logs=await this.db.auditLog.findMany({where:{tenantId,entity:'quote',entityId:id},orderBy:{createdAt:'asc'}});const events:any[]=[{type:'created',title:'Orçamento criado',at:quote.createdAt}];for(const log of logs){const m:any=log.metadata??{};if(log.action==='update')events.push({type:'version',title:`Versão ${m.version??''} salva`.trim(),at:log.createdAt,detail:m.itemsChanged?'Serviços e valores atualizados':'Condições atualizadas'});else if(log.action==='change_status')events.push({type:'status',title:m.to==='sent'?'Proposta enviada':m.to==='rejected'?'Orçamento recusado':'Status alterado',at:log.createdAt,detail:m.to});else if(log.action==='share')events.push({type:'share',title:'Link público compartilhado',at:log.createdAt});else if(log.action==='revoke_share')events.push({type:'share',title:'Link público revogado',at:log.createdAt});else if(log.action==='approve')events.push({type:'approved',title:'Orçamento aprovado internamente',at:log.createdAt});else if(log.action==='client_approved')events.push({type:'approved',title:'Cliente aprovou a proposta',at:log.createdAt,detail:m.name});else if(log.action==='client_rejected')events.push({type:'rejected',title:'Cliente recusou a proposta',at:log.createdAt,detail:m.name});else if(log.action==='duplicate')events.push({type:'duplicate',title:'Orçamento duplicado',at:log.createdAt});}
    return events.sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime());}
  async quoteVersions(tenantId:string,id:string){const quote=await this.db.quote.findFirst({where:{id,tenantId},select:{id:true}});if(!quote)throw new NotFoundException('Orçamento não encontrado');return this.db.quoteVersion.findMany({where:{tenantId,quoteId:id},orderBy:{version:'desc'}});}
  private quoteSnapshot(q:any){return {clientId:q.clientId,number:q.number,status:q.status,totalCents:q.totalCents,discountBps:q.discountBps,finalTotalCents:q.finalTotalCents,validityDays:q.validityDays,notes:q.notes,sentAt:q.sentAt,approvedAt:q.approvedAt,validUntil:q.validUntil,items:(q.items??[]).map((i:any)=>({serviceName:i.serviceName,days:i.days,people:i.people,laborCents:i.laborCents,variableCents:i.variableCents,fixedCents:i.fixedCents,marginCents:i.marginCents,totalCents:i.totalCents,configurationJson:i.configurationJson,stages:i.stages??[]}))};}
  private async buildQuoteItems(tenantId:string,inputs:any[]){const items=[] as any[];for(const input of inputs){const service=await this.db.service.findFirst({where:{id:input.serviceId,tenantId,active:true},include:{stages:{where:{tenantId},orderBy:{sequence:'asc'}}}});if(!service)throw new NotFoundException('Serviço não encontrado ou inativo');const days=input.days??service.defaultDays,people=input.people??service.people;const calc=this.calculate({dailyRateCents:input.dailyRateCents??service.dailyRateCents,days,people,variableCostCents:input.variableCostCents??service.variableCostCents,fixedCostCents:input.fixedCostCents??service.fixedCostCents,safetyMarginBps:input.safetyMarginBps??service.safetyMarginBps});items.push({tenantId,serviceName:service.name,days,people,...calc,configurationJson:{serviceId:service.id,dailyRateCents:input.dailyRateCents??service.dailyRateCents,variableCostCents:input.variableCostCents??service.variableCostCents,fixedCostCents:input.fixedCostCents??service.fixedCostCents,safetyMarginBps:input.safetyMarginBps??service.safetyMarginBps},stages:{create:service.stages.map(st=>({tenantId,sequence:st.sequence,description:st.description,duration:st.duration}))}});}return items;}
  async updateQuote(tenantId:string,id:string,data:any,actorUserId?:string){
    const quote=await this.db.quote.findFirst({where:{id,tenantId},include:{items:{where:{tenantId},include:{stages:{where:{tenantId},orderBy:{sequence:'asc'}}}}}});
    if(!quote)throw new NotFoundException('Orçamento não encontrado');
    if(quote.status!=='draft')throw new BadRequestException('Somente orçamentos em rascunho podem ser editados');
    const nextDiscount=data.discountBps??quote.discountBps;const nextValidity=data.validityDays??quote.validityDays;const nextNotes=data.notes===undefined?quote.notes:data.notes;
    const newItems=data.items?await this.buildQuoteItems(tenantId,data.items):null;const totalCents=newItems?newItems.reduce((sum:number,i:any)=>sum+i.totalCents,0):quote.totalCents;const finalTotalCents=Math.round(totalCents*(10000-nextDiscount)/10000);
    const updated=await this.db.$transaction(async tx=>{await tx.quoteVersion.create({data:{tenantId,quoteId:id,version:quote.version,snapshot:this.quoteSnapshot(quote),createdById:actorUserId}});if(newItems)await tx.quoteItem.deleteMany({where:{tenantId,quoteId:id}});return tx.quote.update({where:{id},data:{discountBps:nextDiscount,validityDays:nextValidity,notes:nextNotes,totalCents,finalTotalCents,version:{increment:1},publicToken:null,publicSharedAt:null,clientDecision:null,clientDecisionAt:null,clientDecisionName:null,...(newItems?{items:{create:newItems}}:{})},include:{client:true,items:{where:{tenantId},include:{stages:{where:{tenantId},orderBy:{sequence:'asc'}}}},project:true}});});
    await this.audit(tenantId,actorUserId,'update','quote',id,{version:updated.version,itemsChanged:!!newItems});return updated;
  }
  async duplicateQuote(tenantId:string,id:string,actorUserId?:string){await this.assertLimit(tenantId,'quotes');const source=await this.db.quote.findFirst({where:{id,tenantId},include:{client:true,items:{where:{tenantId},include:{stages:{where:{tenantId},orderBy:{sequence:'asc'}}}}}});if(!source)throw new NotFoundException('Orçamento não encontrado');const year=new Date().getFullYear();const seq=await this.db.quoteSequence.upsert({where:{tenantId_year:{tenantId,year}},create:{tenantId,year,lastNumber:1},update:{lastNumber:{increment:1}}});const duplicated=await this.db.quote.create({data:{tenantId,clientId:source.clientId,number:`ORC-${year}-${String(seq.lastNumber).padStart(3,'0')}`,status:'draft',totalCents:source.totalCents,discountBps:source.discountBps,finalTotalCents:source.finalTotalCents,validityDays:source.validityDays,notes:source.notes,items:{create:source.items.map(i=>({tenantId,serviceName:i.serviceName,days:i.days,people:i.people,laborCents:i.laborCents,variableCents:i.variableCents,fixedCents:i.fixedCents,marginCents:i.marginCents,totalCents:i.totalCents,configurationJson:i.configurationJson??undefined,stages:{create:i.stages.map(st=>({tenantId,sequence:st.sequence,description:st.description,duration:st.duration,completed:false}))}}))}},include:{client:true,items:true}});await this.audit(tenantId,actorUserId,'duplicate','quote',duplicated.id,{sourceQuoteId:id,sourceNumber:source.number,number:duplicated.number});return duplicated;}
  async createQuote(tenantId:string,data:any,actorUserId?:string){await this.assertLimit(tenantId,'quotes');const client=await this.db.client.findFirst({where:{id:data.clientId,tenantId}});if(!client)throw new NotFoundException('Cliente não encontrado');const items=await this.buildQuoteItems(tenantId,data.items);const totalCents=items.reduce((sum:number,i:any)=>sum+i.totalCents,0);const discountBps=Math.max(0,Math.min(10000,Number(data.discountBps??0)));const finalTotalCents=Math.round(totalCents*(10000-discountBps)/10000);const year=new Date().getFullYear();const seq=await this.db.quoteSequence.upsert({where:{tenantId_year:{tenantId,year}},create:{tenantId,year,lastNumber:1},update:{lastNumber:{increment:1}}});const quote=await this.db.quote.create({data:{tenantId,clientId:client.id,number:`ORC-${year}-${String(seq.lastNumber).padStart(3,'0')}`,totalCents,discountBps,finalTotalCents,validityDays:Number(data.validityDays??30),notes:data.notes,items:{create:items}},include:{client:true,items:{include:{stages:true}}}});await this.audit(tenantId,actorUserId,'create','quote',quote.id,{number:quote.number,finalTotalCents});return quote;}
  async updateQuoteStatus(tenantId:string,id:string,status:string,actorUserId?:string){const quote=await this.db.quote.findFirst({where:{id,tenantId}});if(!quote)throw new NotFoundException('Orçamento não encontrado');if(quote.clientDecision)throw new BadRequestException('A decisão registrada pelo cliente não pode ser reaberta');const allowed:any={draft:['sent'],sent:['draft','rejected'],rejected:['draft']};if(!allowed[quote.status]?.includes(status))throw new BadRequestException(`Não é possível alterar orçamento ${quote.status} para ${status}`);const now=new Date();const validUntil=status==='sent'?new Date(now.getTime()+quote.validityDays*86400000):quote.validUntil;const updated=await this.db.quote.update({where:{id},data:{status,sentAt:status==='sent'?now:quote.sentAt,validUntil:status==='sent'?validUntil:quote.validUntil}});await this.audit(tenantId,actorUserId,'change_status','quote',id,{from:quote.status,to:status});return updated;}
  async updateProject(tenantId:string,id:string,data:any,actorUserId?:string){const project=await this.db.project.findFirst({where:{id,tenantId}});if(!project)throw new NotFoundException('Projeto não encontrado');const progress=data.progress===undefined?project.progress:Math.min(100,Math.max(0,data.progress));const status=data.status??project.status;const normalizedProgress=status==='completed'?100:progress;const updated=await this.db.project.update({where:{id},data:{status,progress:normalizedProgress,notes:data.notes??project.notes,startDate:data.startDate?new Date(data.startDate):project.startDate,endDate:data.endDate?new Date(data.endDate):project.endDate},include:{client:true,quote:true,tasks:{where:{tenantId},orderBy:{createdAt:'asc'}}}});await this.audit(tenantId,actorUserId,'update','project',id,{status:updated.status,progress:updated.progress});return updated;}
  async createProjectNote(tenantId:string,projectId:string,content:string,actorUserId?:string){const project=await this.db.project.findFirst({where:{id:projectId,tenantId}});if(!project)throw new NotFoundException('Projeto não encontrado');const author=actorUserId?await this.db.user.findFirst({where:{id:actorUserId,tenantId},select:{name:true}}):null;const note=await this.db.projectNote.create({data:{tenantId,projectId,authorUserId:actorUserId,authorName:author?.name,content:content.trim()}});await this.audit(tenantId,actorUserId,'create_note','project',projectId,{noteId:note.id});return note;}
  async createProjectTask(tenantId:string,projectId:string,data:any,actorUserId?:string){const project=await this.db.project.findFirst({where:{id:projectId,tenantId}});if(!project)throw new NotFoundException('Projeto não encontrado');const task=await this.db.projectTask.create({data:{tenantId,projectId,title:data.title.trim(),description:data.description,priority:data.priority??'medium',dueDate:data.dueDate?new Date(data.dueDate):undefined}});await this.audit(tenantId,actorUserId,'create','project_task',task.id,{projectId,title:task.title});return task;}
  async updateProjectTask(tenantId:string,projectId:string,taskId:string,data:any,actorUserId?:string){const task=await this.db.projectTask.findFirst({where:{id:taskId,projectId,tenantId}});if(!task)throw new NotFoundException('Tarefa não encontrada');const status=data.status??task.status;const updated=await this.db.projectTask.update({where:{id:taskId},data:{title:data.title??task.title,description:data.description??task.description,status,priority:data.priority??task.priority,dueDate:data.dueDate?new Date(data.dueDate):task.dueDate,completedAt:status==='completed'?(task.completedAt??new Date()):null}});const [total,done]=await Promise.all([this.db.projectTask.count({where:{projectId,tenantId}}),this.db.projectTask.count({where:{projectId,tenantId,status:'completed'}})]);if(total>0)await this.db.project.update({where:{id:projectId},data:{progress:Math.round(done*100/total),status:done===total?'completed':'in_progress'}});await this.audit(tenantId,actorUserId,'update','project_task',taskId,{projectId,status});return updated;}
  async approve(tenantId:string,id:string,actorUserId?:string){const quote=await this.db.quote.findFirst({where:{id,tenantId},include:{client:true}});if(!quote)throw new NotFoundException('Orçamento não encontrado');if(!['draft','sent','approved'].includes(quote.status))throw new BadRequestException('Transição de status inválida');const q=await this.db.$transaction(async tx=>{const updated=await tx.quote.update({where:{id},data:{status:'approved',approvedAt:quote.approvedAt??new Date()}});await tx.project.upsert({where:{quoteId:id},update:{},create:{tenantId,clientId:quote.clientId,quoteId:id,name:`${quote.number} — ${quote.client.name}`}});return updated;});await this.audit(tenantId,actorUserId,'approve','quote',id,{number:quote.number});return q;}

  calendar(tenantId:string){const from=new Date();from.setMonth(from.getMonth()-1);const to=new Date();to.setMonth(to.getMonth()+6);return this.db.calendarEvent.findMany({where:{tenantId,startAt:{gte:from,lte:to}},orderBy:{startAt:'asc'}});}
  async createCalendarEvent(tenantId:string,userId:string,data:any){
    const startAt=new Date(data.startAt);const endAt=data.endAt?new Date(data.endAt):null;
    if(Number.isNaN(startAt.getTime())||endAt&&Number.isNaN(endAt.getTime()))throw new BadRequestException('Data do compromisso inválida');
    if(endAt&&endAt<startAt)throw new BadRequestException('O término deve ser posterior ao início');
    if(data.clientId&&!await this.db.client.findFirst({where:{id:data.clientId,tenantId}}))throw new NotFoundException('Cliente não encontrado');
    if(data.projectId&&!await this.db.project.findFirst({where:{id:data.projectId,tenantId}}))throw new NotFoundException('Projeto não encontrado');
    const event=await this.db.calendarEvent.create({data:{tenantId,createdById:userId,title:data.title.trim(),description:data.description?.trim()||null,type:data.type,startAt,endAt,allDay:!!data.allDay,location:data.location?.trim()||null,recurrence:data.recurrence??'none',reminderMinutes:data.reminderMinutes??60,clientId:data.clientId||null,projectId:data.projectId||null}});
    await this.audit(tenantId,userId,'create','calendar_event',event.id,{title:event.title,startAt:event.startAt});return event;
  }
  async cancelCalendarEvent(tenantId:string,id:string,userId:string){const event=await this.db.calendarEvent.findFirst({where:{id,tenantId}});if(!event)throw new NotFoundException('Compromisso não encontrado');const updated=await this.db.calendarEvent.update({where:{id},data:{status:'cancelled'}});await this.audit(tenantId,userId,'cancel','calendar_event',id,{title:event.title});return updated;}
  private async syncNotifications(tenantId:string,userId:string){
    const prefs=await this.notificationPreferences(tenantId,userId);const now=new Date();const horizon=new Date(now.getTime()+7*86400000);
    const [events,tasks,quotes]=await Promise.all([
      prefs.agendaReminders?this.db.calendarEvent.findMany({where:{tenantId,status:'active',startAt:{gte:now,lte:horizon}}}):[],
      prefs.taskDeadlines?this.db.projectTask.findMany({where:{tenantId,status:{not:'completed'},dueDate:{gte:now,lte:horizon}},include:{project:true}}):[],
      prefs.quoteExpirations?this.db.quote.findMany({where:{tenantId,status:'sent',validUntil:{gte:now,lte:horizon}}}):[]
    ]);
    const rows=[
      ...events.map((x:any)=>({key:`calendar:${x.id}:${x.startAt.toISOString()}`,type:'agenda',title:`Compromisso: ${x.title}`,message:`Agendado para ${x.startAt.toLocaleString('pt-BR')}`,route:'/calendar',entityId:x.id})),
      ...tasks.map((x:any)=>({key:`task:${x.id}:${x.dueDate.toISOString()}`,type:'task_due',title:`Prazo: ${x.title}`,message:x.project?.name,route:`/project/${x.projectId}`,entityId:x.id})),
      ...quotes.map((x:any)=>({key:`quote:${x.id}:${x.validUntil.toISOString()}`,type:'quote_expiring',title:`Proposta ${x.number} próxima do vencimento`,message:`Válida até ${x.validUntil.toLocaleDateString('pt-BR')}`,route:`/quote/${x.id}`,entityId:x.id}))
    ];
    await Promise.all(rows.map(row=>this.db.userNotification.upsert({where:{userId_key:{userId,key:row.key}},update:{title:row.title,message:row.message,route:row.route},create:{tenantId,userId,...row}})));
  }
  async notifications(tenantId:string,userId:string){await this.syncNotifications(tenantId,userId);return this.db.userNotification.findMany({where:{tenantId,userId,archivedAt:null},orderBy:{createdAt:'desc'},take:100});}
  async unreadNotifications(tenantId:string,userId:string){await this.syncNotifications(tenantId,userId);return {count:await this.db.userNotification.count({where:{tenantId,userId,readAt:null,archivedAt:null}})};}
  async readNotification(tenantId:string,userId:string,id:string){const result=await this.db.userNotification.updateMany({where:{id,tenantId,userId},data:{readAt:new Date()}});if(!result.count)throw new NotFoundException('Notificação não encontrada');return {ok:true};}
  async readAllNotifications(tenantId:string,userId:string){await this.db.userNotification.updateMany({where:{tenantId,userId,readAt:null},data:{readAt:new Date()}});return {ok:true};}
  notificationPreferences(tenantId:string,userId:string){return this.db.notificationPreference.upsert({where:{userId},update:{},create:{tenantId,userId}});}
  updateNotificationPreferences(tenantId:string,userId:string,data:any){return this.db.notificationPreference.upsert({where:{userId},update:data,create:{tenantId,userId,...data}});}
  private async assertLimit(tenantId:string,resource:'clients'|'quotes'){const tenant=await this.db.tenant.findUnique({where:{id:tenantId}});if(!tenant)throw new NotFoundException('Tenant não encontrada');const limit=await this.db.planLimit.findUnique({where:{plan:tenant.plan}});if(!limit)return;if(resource==='clients'&&limit.maxClients>=0&&await this.db.client.count({where:{tenantId,active:true}})>=limit.maxClients)throw new BadRequestException('Limite de clientes do plano atingido');if(resource==='quotes'&&limit.maxQuotesPerMonth>=0){const start=new Date();start.setDate(1);start.setHours(0,0,0,0);if(await this.db.quote.count({where:{tenantId,createdAt:{gte:start}}})>=limit.maxQuotesPerMonth)throw new BadRequestException('Limite mensal de orçamentos atingido');}}
}
