import { Injectable, Optional } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { PrismaService } from './prisma.service'; import { MailService } from './mail.service'; import { RedisService } from './redis.service';
import { BillingService } from './modules/billing/billing.service'; import { SubscriptionService } from './modules/billing/subscription.service';
import { AuthService } from './modules/auth/auth.service'; import { AuthSessionService } from './modules/auth/auth-session.service'; import { AccessManagementService } from './modules/access/access-management.service';
import { ProjectsService } from './modules/projects/projects.service'; import { CalendarService } from './modules/calendar/calendar.service'; import { QuotesService } from './modules/quotes/quotes.service'; import { ClientsService } from './modules/clients/clients.service'; import { ServicesService } from './modules/services/services.service'; import { PlatformAdminService } from './modules/platform/platform-admin.service';
import { AccountService } from './modules/account/account.service'; import { AuditService } from './modules/audit/audit.service'; import { DashboardService } from './modules/dashboard/dashboard.service'; import { PricingService } from './modules/pricing/pricing.service';
import { CreateClientDto,UpdateClientDto } from './modules/clients/dto/clients.dto'; import { CreateServiceDto,UpdateServiceDto } from './modules/services/dto/services.dto'; import { PlatformCreateTenantDto,PlatformPlanDto,PlatformTenantDto,PlatformUserDto } from './modules/platform/dto/platform.dto'; import { UpdateAccountDto } from './modules/account/dto/account.dto'; import { AuditQueryDto } from './modules/audit/dto/audit.dto'; import { CalculateDto } from './modules/quotes/dto/quotes.dto';
@Injectable() export class ApiService {
 constructor(private db:PrismaService,private jwt:JwtService,private mail:MailService,@Optional() private redis?:RedisService,@Optional() private billing?:BillingService,@Optional() private subscriptions?:SubscriptionService,@Optional() private auth?:AuthService,@Optional() private authSessions?:AuthSessionService,@Optional() private accessManagement?:AccessManagementService,@Optional() private projectsDomain?:ProjectsService,@Optional() private quotesDomain?:QuotesService,@Optional() private clientsDomain?:ClientsService,@Optional() private servicesDomain?:ServicesService,@Optional() private platformDomain?:PlatformAdminService,@Optional() private calendarDomain?:CalendarService,@Optional() private accountDomain?:AccountService,@Optional() private auditDomain?:AuditService,@Optional() private dashboardDomain?:DashboardService,@Optional() private pricingDomain?:PricingService){}
 private subscriptionService(){return this.subscriptions??new SubscriptionService(this.db);} private billingService(){return this.billing??new BillingService(this.db,this.subscriptionService(),this.redis);} private sessionService(){return this.authSessions??new AuthSessionService(this.db,this.jwt,this.subscriptionService());} private authService(){return this.auth??new AuthService(this.db,this.mail,this.sessionService());} private accessService(){return this.accessManagement??new AccessManagementService(this.db,this.mail,this.sessionService());} private projectsService(){return this.projectsDomain??new ProjectsService(this.db);} private calendarService(){return this.calendarDomain??new CalendarService(this.db);} private quotesService(){return this.quotesDomain??new QuotesService(this.db);} private clientsService(){return this.clientsDomain??new ClientsService(this.db);} private servicesService(){return this.servicesDomain??new ServicesService(this.db);} private platformService(){return this.platformDomain??new PlatformAdminService(this.db,this.mail,this.authService());} private accountService(){return this.accountDomain??new AccountService(this.db,this.subscriptionService());} private auditService(){return this.auditDomain??new AuditService(this.db);} private dashboardService(){return this.dashboardDomain??new DashboardService(this.db);} private pricingService(){return this.pricingDomain??new PricingService();}
 calculate(x:CalculateDto){return this.pricingService().calculate(x);} login(e:string,p:string){return this.authService().login(e,p);} platformLogin(e:string,p:string){return this.authService().platformLogin(e,p);} refresh(t:string){return this.authService().refresh(t);} logout(u:string,t:string,s?:string){return this.authService().logout(u,t,s);} forgotPassword(e:string){return this.authService().forgotPassword(e);} resetPassword(t:string,p:string){return this.authService().resetPassword(t,p);} register(d:any){return this.authService().register(d);}
 listAuthSessions(u:string,t:string,s?:string){return this.sessionService().listTenantSessions(u,t,s);} revokeAuthSession(u:string,t:string,s:string){return this.sessionService().revokeTenantSession(u,t,s);} revokeOtherAuthSessions(u:string,t:string,s?:string){return this.sessionService().revokeOtherTenantSessions(u,t,s);}
 platformOverview(){return this.platformService().overview();} platformTenants(){return this.platformService().tenants();} platformSubscriptions(){return this.platformService().subscriptions();} platformPayments(){return this.platformService().payments();} platformUsers(){return this.platformService().users();} platformPlans(){return this.platformService().plans();} platformChangeTenant(id:string,d:PlatformTenantDto){return this.platformService().changeTenant(id,d);} platformCancelScheduledChange(id:string){return this.platformService().cancelScheduledChange(id);} platformCreateTenant(d:PlatformCreateTenantDto,u:string){return this.platformService().createTenant(d,u);} platformUpdateTenant(id:string,d:PlatformTenantDto){return this.platformService().updateTenant(id,d);} platformUpdateUser(id:string,d:PlatformUserDto){return this.platformService().updateUser(id,d);} platformPasswordReset(id:string){return this.platformService().passwordReset(id);} platformUpdatePlan(p:string,d:PlatformPlanDto){return this.platformService().updatePlan(p,d);}
 plans(){return this.accountService().plans();} account(t:string,u?:string){return this.accountService().account(t,u);} updateAccount(t:string,d:UpdateAccountDto,u?:string){return this.accountService().update(t,d,u);} uploadLogo(t:string,f:any,u?:string){return this.accountService().uploadLogo(t,f,u);} removeLogo(t:string,u?:string){return this.accountService().removeLogo(t,u);} changePassword(t:string,u:string,c:string,n:string){return this.accountService().changePassword(t,u,c,n);} updatePlan(t:string,p:string,period='monthly',u?:string){return this.accountService().updatePlan(t,p,period,u);}
 billingPayments(t:string){return this.billingService().payments(t);} reconcileMercadoPagoReturn(t:string,p:string,u?:string){return this.billingService().reconcileReturn(t,p,u);} createCheckout(t:string,u:string,p:string,period:string){return this.billingService().createCheckout(t,u,p,period);} mercadoPagoWebhook(b:any,d?:string,s?:string,r?:string){return this.billingService().webhook(b,d,s,r);} reconcilePayment(t:string,id:string,u:string){return this.billingService().reconcile(t,id,u);} billingMetrics(t:string){return this.billingService().metrics(t);}
 users(t:string){return this.accessService().users(t);} accessProfiles(t:string){return this.accessService().accessProfiles(t);} createAccessProfile(t:string,d:any,u:string){return this.accessService().createAccessProfile(t,d,u);} updateAccessProfile(t:string,id:string,d:any,u:string){return this.accessService().updateAccessProfile(t,id,d,u);} userInvitations(t:string){return this.accessService().userInvitations(t);} createUser(t:string,d:any,u:string){return this.accessService().createUser(t,d,u);} resendUserInvitation(t:string,id:string,u:string){return this.accessService().resendUserInvitation(t,id,u);} cancelUserInvitation(t:string,id:string,u:string){return this.accessService().cancelUserInvitation(t,id,u);} invitationInfo(token:string){return this.accessService().invitationInfo(token);} acceptInvitation(token:string,p:string){return this.accessService().acceptInvitation(token,p);} updateUser(t:string,id:string,d:any,u:string){return this.accessService().updateUser(t,id,d,u);}
 auditLogs(t:string,f:AuditQueryDto={}){return this.auditService().list(t,f);} dashboard(t:string){return this.dashboardService().overview(t);}
 clients(t:string){return this.clientsService().list(t);} createClient(t:string,d:CreateClientDto,u?:string){return this.clientsService().create(t,d,u);} updateClient(t:string,id:string,d:UpdateClientDto,u?:string){return this.clientsService().update(t,id,d,u);} services(t:string){return this.servicesService().list(t);} createService(t:string,d:CreateServiceDto,u?:string){return this.servicesService().create(t,d,u);} updateService(t:string,id:string,d:UpdateServiceDto,u?:string){return this.servicesService().update(t,id,d,u);}
 quotes(t:string){return this.quotesService().quotes(t);} quote(t:string,id:string){return this.quotesService().quote(t,id);} shareQuote(t:string,id:string,u?:string){return this.quotesService().shareQuote(t,id,u);} revokeQuoteShare(t:string,id:string,u?:string){return this.quotesService().revokeQuoteShare(t,id,u);} publicProposal(token:string){return this.quotesService().publicProposal(token);} decidePublicProposal(token:string,d:'approved'|'rejected',n:string){return this.quotesService().decidePublicProposal(token,d,n);} quoteTimeline(t:string,id:string){return this.quotesService().quoteTimeline(t,id);} quoteVersions(t:string,id:string){return this.quotesService().quoteVersions(t,id);} updateQuote(t:string,id:string,d:any,u?:string){return this.quotesService().updateQuote(t,id,d,u);} duplicateQuote(t:string,id:string,u?:string){return this.quotesService().duplicateQuote(t,id,u);} createQuote(t:string,d:any,u?:string){return this.quotesService().createQuote(t,d,u);} updateQuoteStatus(t:string,id:string,s:string,u?:string){return this.quotesService().updateQuoteStatus(t,id,s,u);} approve(t:string,id:string,u?:string){return this.quotesService().approve(t,id,u);}
 projectStatuses(t:string){return this.projectsService().projectStatuses(t);} createProjectStatus(t:string,d:any,u?:string){return this.projectsService().createProjectStatus(t,d,u);} updateProjectStatus(t:string,id:string,d:any,u?:string){return this.projectsService().updateProjectStatus(t,id,d,u);} deleteProjectStatus(t:string,id:string,u?:string){return this.projectsService().deleteProjectStatus(t,id,u);} projects(t:string){return this.projectsService().projects(t);} project(t:string,id:string){return this.projectsService().project(t,id);} updateProject(t:string,id:string,d:any,u?:string){return this.projectsService().updateProject(t,id,d,u);} createProjectNote(t:string,id:string,c:string,u?:string){return this.projectsService().createProjectNote(t,id,c,u);} createProjectTask(t:string,id:string,d:any,u?:string){return this.projectsService().createProjectTask(t,id,d,u);} updateProjectTask(t:string,p:string,id:string,d:any,u?:string){return this.projectsService().updateProjectTask(t,p,id,d,u);}
 calendar(t:string){return this.calendarService().list(t);} createCalendarEvent(t:string,u:string,d:any){return this.calendarService().create(t,u,d);} cancelCalendarEvent(t:string,id:string,u:string){return this.calendarService().cancel(t,id,u);} updateCalendarEvent(t:string,id:string,u:string,d:any){return this.calendarService().update(t,id,u,d);}
}
