import { Injectable } from '@nestjs/common';
import { escapeHtml } from './security/html';

type MailMessage={from:string;to:string;subject:string;text:string;html:string};
type MailTransport={sendMail(message:MailMessage):Promise<unknown>;verify?():Promise<unknown>};
type NodemailerModule={createTransport(options:Record<string,unknown>):MailTransport};
const nodemailer=require('nodemailer') as NodemailerModule;

export type MailDelivery={sent:true}|{sent:false;reason:'not_configured'|'send_failed'};
export type SmtpStatus={configured:boolean;host:string|null;port:number;secure:boolean;from:string|null;userConfigured:boolean;passwordConfigured:boolean};
@Injectable()
export class MailService {
  private transporter?:MailTransport;
  private config(){const host=process.env.SMTP_HOST?.trim()||'';const port=Number(process.env.SMTP_PORT||587);const secure=process.env.SMTP_SECURE==='true'||port===465;const user=process.env.SMTP_USER?.trim()||'';const pass=process.env.SMTP_PASS||'';const from=(process.env.SMTP_FROM||user||'').trim();return {host,port,secure,user,pass,from};}
  status():SmtpStatus{const c=this.config();return {configured:!!(c.host&&c.from),host:c.host||null,port:c.port,secure:c.secure,from:c.from||null,userConfigured:!!c.user,passwordConfigured:!!c.pass};}
  private getTransporter():MailTransport|undefined{if(this.transporter)return this.transporter;const c=this.config();if(!c.host)return undefined;this.transporter=nodemailer.createTransport({host:c.host,port:c.port,secure:c.secure,auth:c.user?{user:c.user,pass:c.pass}:undefined,disableFileAccess:true,disableUrlAccess:true,connectionTimeout:Number(process.env.SMTP_CONNECTION_TIMEOUT_MS||10000),greetingTimeout:Number(process.env.SMTP_GREETING_TIMEOUT_MS||10000),socketTimeout:Number(process.env.SMTP_SOCKET_TIMEOUT_MS||15000)});return this.transporter;}
  private async send(to:string,subject:string,text:string,html:string):Promise<MailDelivery>{const transporter=this.getTransporter();if(!transporter)return {sent:false,reason:'not_configured'};const from=this.config().from||'LuviePro <no-reply@luviepro.local>';try{await transporter.sendMail({from,to,subject,text,html});return {sent:true};}catch{return {sent:false,reason:'send_failed'};}}
  async verify(){const transporter=this.getTransporter();if(!transporter)return {ok:false,reason:'not_configured' as const,status:this.status()};try{if(transporter.verify)await transporter.verify();return {ok:true,status:this.status()};}catch{return {ok:false,reason:'send_failed' as const,status:this.status()};}}
  async sendTest(input:{to:string;name:string}){return this.send(input.to,'Teste de e-mail do LuviePro',`Olá, ${input.name}. O SMTP do LuviePro está configurado e enviando e-mails corretamente.`,`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#183326"><h2>SMTP configurado com sucesso</h2><p>Olá, <strong>${escapeHtml(input.name)}</strong>.</p><p>Este é um e-mail de teste do LuviePro. Se você recebeu esta mensagem, o envio SMTP está funcionando corretamente.</p></div>`);}
  async sendUserInvitation(input:{to:string;name:string;tenantName:string;roleLabel:string;inviteUrl:string;expiresAt:Date}):Promise<MailDelivery>{const expires=input.expiresAt.toLocaleString('pt-BR');return this.send(input.to,`Primeiro acesso ao ${input.tenantName} no LuviePro`,`Olá, ${input.name}. Você recebeu acesso a ${input.tenantName} no LuviePro como ${input.roleLabel}. Crie sua senha pelo link: ${input.inviteUrl}. O link expira em ${expires}.`,`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#183326"><h2>Seu primeiro acesso ao LuviePro</h2><p>Olá, <strong>${escapeHtml(input.name)}</strong>.</p><p>Você recebeu acesso à empresa <strong>${escapeHtml(input.tenantName)}</strong> com o perfil <strong>${escapeHtml(input.roleLabel)}</strong>.</p><p>Para concluir seu primeiro acesso, crie sua senha individual.</p><p style="margin:28px 0"><a href="${input.inviteUrl}" style="background:#244d3b;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none;font-weight:700">Criar minha senha</a></p><p style="font-size:13px;color:#65736c">Este link expira em ${expires} e só pode ser utilizado uma vez.</p></div>`);}
  async sendAccessActivated(input:{to:string;name:string;tenantName:string;loginUrl:string}):Promise<MailDelivery>{return this.send(input.to,'Seu acesso ao LuviePro foi ativado',`Olá, ${input.name}. Seu acesso a ${input.tenantName} foi ativado. Entre em ${input.loginUrl}.`,`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#183326"><h2>Acesso ativado</h2><p>Olá, <strong>${escapeHtml(input.name)}</strong>.</p><p>Seu primeiro acesso à empresa <strong>${escapeHtml(input.tenantName)}</strong> foi concluído com sucesso.</p><p style="margin:28px 0"><a href="${input.loginUrl}" style="background:#244d3b;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none;font-weight:700">Entrar no LuviePro</a></p></div>`);}
  async sendPasswordReset(input:{to:string;name:string;resetUrl:string;expiresAt:Date}):Promise<MailDelivery>{const expires=input.expiresAt.toLocaleString('pt-BR');return this.send(input.to,'Redefinição de senha do LuviePro',`Olá, ${input.name}. Redefina sua senha pelo link: ${input.resetUrl}. O link expira em ${expires}.`,`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#183326"><h2>Redefinição de senha</h2><p>Olá, <strong>${escapeHtml(input.name)}</strong>.</p><p>Recebemos uma solicitação para redefinir sua senha.</p><p style="margin:28px 0"><a href="${input.resetUrl}" style="background:#244d3b;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none;font-weight:700">Criar nova senha</a></p><p style="font-size:13px;color:#65736c">O link expira em ${expires}. Se você não solicitou a alteração, ignore esta mensagem.</p></div>`);}
  async sendNotification(input:{to:string;name:string;title:string;message?:string|null;url?:string|null}):Promise<MailDelivery>{const action=input.url?`<p style="margin:24px 0"><a href="${input.url}" style="background:#244d3b;color:#fff;padding:11px 16px;border-radius:8px;text-decoration:none;font-weight:700">Abrir no LuviePro</a></p>`:'';return this.send(input.to,input.title,`Olá, ${input.name}. ${input.title}${input.message?`: ${input.message}`:''}${input.url?` ${input.url}`:''}`,`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#183326"><h2>${escapeHtml(input.title)}</h2><p>Olá, <strong>${escapeHtml(input.name)}</strong>.</p>${input.message?`<p>${escapeHtml(input.message)}</p>`:''}${action}<p style="font-size:12px;color:#65736c">Você recebe este e-mail porque habilitou notificações por e-mail no LuviePro.</p></div>`);}
}
