import { ReactNode } from 'react';
import { Pressable,StyleSheet,View } from 'react-native';
import { Text } from '../i18n';
import { theme } from '../theme';

export function BusinessPanel({children}:{children:ReactNode}){return <View style={s.panel}>{children}</View>}
export function BusinessToolbar({search,filters,count,actions}:{search:ReactNode;filters?:ReactNode;count?:string;actions?:ReactNode}){return <View style={s.toolbar}><View style={s.search}>{search}</View>{filters?<View style={s.filters}>{filters}</View>:null}{actions?<View style={s.actions}>{actions}</View>:null}{count?<Text style={s.count}>{count}</Text>:null}</View>}
export function FilterChip({label,active,onPress}:{label:string;active?:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.chip,active&&s.chipOn,pressed&&s.pressed]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
export function StatusBadge({label,tone='neutral'}:{label:string;tone?:'neutral'|'success'|'warning'|'danger'|'info'}){return <View style={[s.badge,tone==='success'&&s.success,tone==='warning'&&s.warning,tone==='danger'&&s.danger,tone==='info'&&s.info]}><Text style={[s.badgeText,tone==='success'&&s.successText,tone==='warning'&&s.warningText,tone==='danger'&&s.dangerText,tone==='info'&&s.infoText]}>{label}</Text></View>}
export function RowAction({children,onPress,danger}:{children:ReactNode;onPress:()=>void;danger?:boolean}){return <Pressable onPress={onPress} style={({pressed})=>[s.action,danger&&s.actionDanger,pressed&&s.pressed]}>{typeof children==='string'?<Text style={[s.actionText,danger&&s.dangerText]}>{children}</Text>:children}</Pressable>}
const s=StyleSheet.create({panel:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:16,overflow:'hidden',shadowColor:theme.shadow,shadowOpacity:.04,shadowRadius:16,shadowOffset:{width:0,height:6},elevation:1},toolbar:{padding:14,flexDirection:'row',alignItems:'center',gap:10,flexWrap:'wrap',borderBottomWidth:1,borderBottomColor:theme.border,backgroundColor:'#FCFDFC'},search:{flex:1,minWidth:250},filters:{flexDirection:'row',gap:6,flexWrap:'wrap'},actions:{flexDirection:'row',gap:6,alignItems:'center'},count:{fontSize:11,fontWeight:'800',color:theme.muted,marginLeft:'auto'},chip:{paddingHorizontal:10,paddingVertical:8,borderRadius:9,borderWidth:1,borderColor:'transparent'},chipOn:{backgroundColor:theme.green2,borderColor:theme.green2},chipText:{fontSize:11,fontWeight:'800',color:theme.muted},chipTextOn:{color:theme.white},badge:{alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:5,borderRadius:999,backgroundColor:theme.cream},badgeText:{fontSize:11,fontWeight:'900',letterSpacing:.2,color:theme.muted},success:{backgroundColor:theme.successSoft},successText:{color:theme.success},warning:{backgroundColor:theme.goldPale},warningText:{color:'#8A6D22'},danger:{backgroundColor:theme.dangerSoft},dangerText:{color:theme.danger},info:{backgroundColor:theme.infoSoft},infoText:{color:theme.green2},action:{minWidth:34,height:34,borderRadius:9,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center',paddingHorizontal:9,backgroundColor:theme.white},actionDanger:{backgroundColor:theme.dangerSoft,borderColor:'#F0D0D0'},actionText:{fontSize:11,fontWeight:'800',color:theme.green2},pressed:{opacity:.72}});
