import { ReactNode } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Modal,Pressable,ScrollView,StyleSheet,useWindowDimensions,View } from 'react-native';
import { Text } from '../i18n';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { theme } from '../theme';

export function FormModal({visible,title,subtitle,onClose,children,footer,size='md',closeOnBackdrop=true}:{visible:boolean;title:string;subtitle?:string;onClose:()=>void;children:ReactNode;footer?:ReactNode;size?:'sm'|'md'|'lg';closeOnBackdrop?:boolean}){
  const mobile=useWindowDimensions().width<620;
  const insets=useSafeAreaInsets();
  return <Modal visible={visible} transparent animationType={mobile?'slide':'fade'} statusBarTranslucent onRequestClose={onClose}><View accessibilityViewIsModal style={[s.overlay,mobile&&s.mobileOverlay]}><Pressable accessibilityLabel={closeOnBackdrop?'Fechar janela':'Área externa do formulário'} style={StyleSheet.absoluteFill} onPress={closeOnBackdrop?onClose:undefined}/><View style={[s.dialog,size==='sm'&&s.dialogSm,size==='lg'&&s.dialogLg,mobile&&s.mobileDialog]}>{mobile&&<View style={s.handle}/>}<View style={s.header}><View style={s.headerText}><Text accessibilityRole="header" style={s.title}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View><Pressable accessibilityRole="button" accessibilityLabel="Fechar" accessibilityHint={`Fecha ${title}`} onPress={onClose} style={({pressed})=>[s.close,pressed&&s.pressed]}><Ionicons name="close" size={21} color={theme.muted}/></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" showsVerticalScrollIndicator contentContainerStyle={s.content}>{children}</ScrollView>{footer&&<View style={[s.footer,mobile&&{paddingBottom:Math.max(15,insets.bottom)}]}>{footer}</View>}</View></View></Modal>
}
const s=StyleSheet.create({overlay:{flex:1,backgroundColor:'rgba(10,24,17,.58)',alignItems:'center',justifyContent:'center',padding:18},mobileOverlay:{justifyContent:'flex-end',padding:0},dialog:{width:'100%',maxWidth:620,maxHeight:'92%',backgroundColor:theme.white,borderRadius:18,overflow:'hidden',boxShadow:'0 24px 70px rgba(0,0,0,.24)'},dialogSm:{maxWidth:460},dialogLg:{maxWidth:820},mobileDialog:{maxHeight:'92%',borderBottomLeftRadius:0,borderBottomRightRadius:0},handle:{width:42,height:4,borderRadius:2,backgroundColor:theme.border,alignSelf:'center',marginTop:9},header:{paddingHorizontal:20,paddingVertical:17,borderBottomWidth:1,borderBottomColor:theme.border,flexDirection:'row',alignItems:'flex-start'},headerText:{flex:1},title:{fontFamily:'serif',fontSize:20,fontWeight:'700',color:theme.ink},subtitle:{fontSize:12,color:theme.muted,marginTop:4},close:{width:34,height:34,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:theme.cream},pressed:{opacity:.68},content:{padding:20,gap:12},footer:{borderTopWidth:1,borderTopColor:theme.border,padding:15,flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:8,flexWrap:'wrap',backgroundColor:theme.white}});
