import { BadRequestException,Injectable,NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma.service';
import { CreateCategoryDto,CreateProductDto,CreateProductUnitDto,StockMovementDto,UpdateCategoryDto,UpdateProductDto,UpdateProductUnitDto } from './dto/products.dto';
@Injectable() export class ProductsService{
 constructor(private db:PrismaService){}
 list(tenantId:string){return this.db.product.findMany({where:{tenantId},include:{category:true},orderBy:[{active:'desc'},{name:'asc'}]})}
 async categories(tenantId:string){const rows=await this.db.productCategory.findMany({where:{tenantId},include:{_count:{select:{products:true}}},orderBy:[{active:'desc'},{name:'asc'}]});return rows.map(({_count,...row})=>({...row,usageCount:_count.products}))}
 async createCategory(tenantId:string,b:CreateCategoryDto){const name=b.name.trim();const existing=await this.db.productCategory.findFirst({where:{tenantId,name:{equals:name,mode:'insensitive'}}});if(existing)throw new BadRequestException('Já existe uma categoria com este nome');return this.db.productCategory.create({data:{tenantId,name,active:b.active!==false}})}
 async updateCategory(tenantId:string,id:string,b:UpdateCategoryDto){const current=await this.db.productCategory.findFirst({where:{id,tenantId}});if(!current)throw new NotFoundException('Categoria não encontrada');const name=b.name.trim();const duplicate=await this.db.productCategory.findFirst({where:{tenantId,name:{equals:name,mode:'insensitive'},NOT:{id}}});if(duplicate)throw new BadRequestException('Já existe uma categoria com este nome');return this.db.productCategory.update({where:{id},data:{name,active:b.active!==false}})}
 async units(tenantId:string){const [rows,used]=await Promise.all([this.db.productUnit.findMany({where:{tenantId},orderBy:[{active:'desc'},{sortOrder:'asc'},{name:'asc'}]}),this.db.product.groupBy({by:['unit'],where:{tenantId},_count:{_all:true}})]);const counts=new Map(used.map(x=>[x.unit.trim().toLowerCase(),x._count._all]));return rows.map(row=>({...row,usageCount:counts.get(row.code.trim().toLowerCase())||0}))}
 async createUnit(tenantId:string,b:CreateProductUnitDto){const code=b.code.trim().toLowerCase();const name=b.name.trim();const existing=await this.db.productUnit.findFirst({where:{tenantId,code:{equals:code,mode:'insensitive'}}});if(existing)throw new BadRequestException('Já existe uma unidade com este código');return this.db.productUnit.create({data:{tenantId,code,name,active:b.active!==false,sortOrder:b.sortOrder||0}})}
 async updateUnit(tenantId:string,id:string,b:UpdateProductUnitDto){const current=await this.db.productUnit.findFirst({where:{id,tenantId}});if(!current)throw new NotFoundException('Unidade não encontrada');const code=b.code.trim().toLowerCase();const name=b.name.trim();const duplicate=await this.db.productUnit.findFirst({where:{tenantId,code:{equals:code,mode:'insensitive'},NOT:{id}}});if(duplicate)throw new BadRequestException('Já existe uma unidade com este código');return this.db.productUnit.update({where:{id},data:{code,name,active:b.active!==false,sortOrder:b.sortOrder||0}})}
 async create(tenantId:string,b:CreateProductDto,actor?:string){await this.validateParameters(tenantId,b.categoryId,b.unit||'un');const initialStock=Math.max(0,b.initialStock||0);const p=await this.db.$transaction(async tx=>{const created=await tx.product.create({data:{tenantId,name:b.name.trim(),sku:b.sku.trim().toUpperCase(),categoryId:b.categoryId||null,description:b.description?.trim()||null,unit:b.unit||'un',barcode:b.barcode?.trim()||null,supplierName:b.supplierName?.trim()||null,costCents:b.costCents,salePriceCents:b.salePriceCents,minimumStock:b.minimumStock||0,stockQuantity:initialStock,imageUrl:b.imageUrl?.trim()||null,active:b.active!==false},include:{category:true}});if(initialStock>0)await tx.stockMovement.create({data:{tenantId,productId:created.id,type:'entry',quantity:initialStock,balanceAfter:initialStock,unitCostCents:b.costCents,reason:'Estoque inicial informado no cadastro do produto',actorUserId:actor}});return created});await this.audit(tenantId,actor,'create',p.id,{sku:p.sku,initialStock});return p}
 async update(tenantId:string,id:string,b:UpdateProductDto,actor?:string){await this.validateParameters(tenantId,b.categoryId,b.unit||'un');const old=await this.db.product.findFirst({where:{id,tenantId}});if(!old)throw new NotFoundException('Produto não encontrado');const p=await this.db.product.update({where:{id},data:{name:b.name.trim(),sku:b.sku.trim().toUpperCase(),categoryId:b.categoryId||null,description:b.description?.trim()||null,unit:b.unit||'un',barcode:b.barcode?.trim()||null,supplierName:b.supplierName?.trim()||null,costCents:b.costCents,salePriceCents:b.salePriceCents,minimumStock:b.minimumStock||0,imageUrl:b.imageUrl?.trim()||null,active:b.active!==false},include:{category:true}});await this.audit(tenantId,actor,'update',id,{sku:p.sku});return p}
 async remove(tenantId:string,id:string,actor?:string){const product=await this.db.product.findFirst({where:{id,tenantId}});if(!product)throw new NotFoundException('Produto não encontrado');const [quoteItems,orderItems,purchaseItems,reservations,movements]=await Promise.all([this.db.quoteProductItem.count({where:{tenantId,productId:id}}),this.db.orderItem.count({where:{productId:id,order:{tenantId}}}),this.db.purchaseOrderItem.count({where:{productId:id,purchaseOrder:{tenantId}}}),this.db.stockReservation.count({where:{tenantId,productId:id}}),this.db.stockMovement.count({where:{tenantId,productId:id}})]);if(quoteItems||orderItems||purchaseItems||reservations)throw new BadRequestException('Este produto já está vinculado a orçamento, pedido, compra ou reserva. Inative o produto em vez de excluí-lo para preservar o histórico.');if(product.stockQuantity!==0||product.reservedQuantity!==0||movements)throw new BadRequestException('Este produto possui saldo ou histórico de estoque. Zere o estoque e inative o produto para preservar as movimentações registradas.');await this.db.product.delete({where:{id}});await this.audit(tenantId,actor,'delete',id,{sku:product.sku,name:product.name});return {ok:true,id}}
 async movements(tenantId:string,id:string){await this.get(tenantId,id);return this.db.stockMovement.findMany({where:{tenantId,productId:id},orderBy:{createdAt:'desc'},take:100})}
 async move(tenantId:string,id:string,b:StockMovementDto,actor?:string){const p=await this.get(tenantId,id);let delta=b.quantity;if(b.type==='exit'||b.type==='loss')delta=-Math.abs(b.quantity);if(b.type==='entry'||b.type==='return')delta=Math.abs(b.quantity);let next=b.type==='adjustment'?b.quantity:p.stockQuantity+delta;if(next<0)throw new BadRequestException('Estoque insuficiente para esta saída');return this.db.$transaction(async tx=>{const updated=await tx.product.update({where:{id},data:{stockQuantity:next}});await tx.stockMovement.create({data:{tenantId,productId:id,type:b.type,quantity:b.type==='adjustment'?next-p.stockQuantity:delta,balanceAfter:next,unitCostCents:b.unitCostCents,reason:b.reason?.trim()||null,actorUserId:actor}});return {...updated,availableQuantity:updated.stockQuantity-updated.reservedQuantity}})}
 async summary(tenantId:string){const rows=await this.db.product.findMany({where:{tenantId,active:true},select:{stockQuantity:true,reservedQuantity:true,minimumStock:true,costCents:true,salePriceCents:true}});return {activeProducts:rows.length,lowStock:rows.filter(x=>x.stockQuantity-x.reservedQuantity<=x.minimumStock).length,reservedUnits:rows.reduce((s,x)=>s+x.reservedQuantity,0),stockCostCents:rows.reduce((s,x)=>s+x.stockQuantity*x.costCents,0),stockSaleCents:rows.reduce((s,x)=>s+x.stockQuantity*x.salePriceCents,0)}}
 private async validateParameters(tenantId:string,categoryId:string|undefined,unit:string){if(categoryId){const category=await this.db.productCategory.findFirst({where:{id:categoryId,tenantId}});if(!category)throw new BadRequestException('Categoria de produto inválida');if(!category.active)throw new BadRequestException('A categoria selecionada está inativa')}const productUnit=await this.db.productUnit.findFirst({where:{tenantId,code:{equals:unit.trim().toLowerCase(),mode:'insensitive'}}});if(!productUnit)throw new BadRequestException('Unidade de produto inválida. Cadastre-a em Configurações > Unidades de produtos.');if(!productUnit.active)throw new BadRequestException('A unidade selecionada está inativa')}
 private async get(tenantId:string,id:string){const p=await this.db.product.findFirst({where:{id,tenantId}});if(!p)throw new NotFoundException('Produto não encontrado');return p}
 private audit(tenantId:string,actor:string|undefined,action:string,id:string,metadata:any){return this.db.auditLog.create({data:{tenantId,actorUserId:actor,action,entity:'product',entityId:id,metadata}}).catch(()=>undefined)}
}
