import { readFileSync } from 'fs';
import { resolve } from 'path';
const read=(f:string)=>readFileSync(resolve(process.cwd(),'src',f),'utf8');
describe('round v85-v120 security and production hardening',()=>{
  const access=read('modules/access/access-management.service.ts');
  const app=read('app.module.ts');
  const clients=read('modules/clients/clients.service.ts');
  const products=read('modules/products/products.service.ts');
  const projects=read('modules/projects/projects.service.ts');
  const orders=read('modules/orders/orders.service.ts');
  const purchases=read('modules/purchases/purchases.service.ts');
  const quotes=read('modules/quotes/quotes.service.ts');
  const services=read('modules/services/services.service.ts');
  const finance=read('modules/finance/finance.service.ts');
  const calendar=read('modules/calendar/calendar.service.ts');
  const notifications=read('modules/notifications/notifications.service.ts');
  const audit=read('modules/audit/audit-query.ts');
  const billing=read('modules/billing/billing.service.ts');
  const main=read('main.ts');
  const allBusiness=[access,clients,products,projects,orders,purchases,quotes,services,finance,calendar,notifications,billing].join('\n');
  it('v85 revalidates a custom profile inside the user update transaction',()=>{expect(access.includes("tx.accessProfile.findFirst({where:{id:data.customProfileId,tenantId,active:true}})")).toBe(true);});
  it('v86 blocks resend when the invitation custom profile is inactive',()=>{expect(access.includes("invitation.customProfileId&&!invitation.customProfile?.active")).toBe(true);});
  it('v87 uses updatedAt CAS when accepting or expiring an invitation',()=>{expect(access.includes("status:'pending',updatedAt:invitation.updatedAt")).toBe(true);});
  it('v88 keeps invitation cancellation tenant scoped',()=>{expect(access.includes("where:{id,tenantId,status:{in:['pending','expired']},updatedAt:invitation.updatedAt}")).toBe(true);});
  it('v89 keeps tenant ownership in password reset target lookup',()=>{expect(access.includes("findFirst({where:{id,tenantId},select:{id:true,email:true,active:true}})")).toBe(true);});
  it('v90 protects profile deactivation against assigned active users',()=>{expect(access.includes("tx.user.count({where:{tenantId,customProfileId:id,active:true}})")).toBe(true);});
  it('v91 keeps global auth, tenant, role and permission guards enabled',()=>{expect(['AuthGuard','TenantActiveGuard','RolesGuard','PermissionsGuard'].every(x=>app.includes(x))).toBe(true);});
  it('v92 scopes client reads and updates to tenant ownership',()=>{expect(clients.includes("findFirst({where:{id,tenantId}})")).toBe(true);});
  it('v93 serializes client activation capacity checks',()=>{expect(clients.includes("isolationLevel:'Serializable'") && clients.includes("tx.user")===false).toBe(true);});
  it('v94 uses compare-and-set for product stock movement',()=>{expect(products.includes("updateMany({where:{id,tenantId,stockQuantity:p.stockQuantity}")).toBe(true);});
  it('v95 validates product category ownership by tenant',()=>{expect(products.includes("productCategory.findFirst({where:{id:categoryId,tenantId}})")).toBe(true);});
  it('v96 validates project assignees inside the tenant',()=>{expect(projects.includes("user.findFirst({ where: { id, tenantId, active: true }")).toBe(true);});
  it('v97 scopes project lookup by id and tenant',()=>{expect(projects.includes("project.findFirst({ where: { id, tenantId }") || projects.includes("project.findFirst({where:{id:projectId,tenantId}")).toBe(true);});
  it('v98 uses serializable retry for project mutation conflicts',()=>{expect(projects.includes("isolationLevel:'Serializable'") && projects.includes("'P2034'")).toBe(true);});
  it('v99 scopes order detail by tenant',()=>{expect(orders.includes("order.findFirst({where:{id,tenantId}")).toBe(true);});
  it('v100 uses CAS for concurrent order payments',()=>{expect(orders.includes("order.updateMany({where:{id,tenantId,amountPaidCents:current.amountPaidCents")).toBe(true);});
  it('v101 uses CAS for concurrent order cancellation',()=>{expect(orders.includes("order.updateMany({where:{id,tenantId,status:{not:'canceled'}}")).toBe(true);});
  it('v102 scopes purchase detail by tenant',()=>{expect(purchases.includes("purchaseOrder.findFirst({where:{id,tenantId}")).toBe(true);});
  it('v103 serializes purchase receipt inventory updates',()=>{expect(purchases.includes("isolationLevel:'Serializable'") && purchases.includes("'P2034'")).toBe(true);});
  it('v104 uses bounded retry for purchase number allocation',()=>{expect(purchases.includes("'P2002'") && purchases.includes("attempt")).toBe(true);});
  it('v105 scopes quote reads by tenant',()=>{expect(quotes.includes("where:{id,tenantId}")).toBe(true);});
  it('v106 uses CAS for quote status transitions',()=>{expect(quotes.includes("quote.updateMany({where:{id,tenantId,status:quote.status,clientDecision:null}")).toBe(true);});
  it('v107 keeps quote creation capacity inside a serializable transaction',()=>{expect(quotes.includes("isolationLevel:'Serializable'") && quotes.includes("quote.count")).toBe(true);});
  it('v109 scopes finance entry state transitions by tenant',()=>{expect(finance.includes("financialEntry.updateMany({where:{id,tenantId,status:'pending'}")).toBe(true);});
  it('v111 scopes calendar relation validation to tenant',()=>{expect(calendar.includes("client.findFirst({ where: { id: clientId, tenantId } })") && calendar.includes("project.findFirst({ where: { id: projectId, tenantId } })")).toBe(true);});
  it('v112 scopes notification mutations to tenant and user',()=>{expect(notifications.includes("updateMany({ where: { id, tenantId, userId }")).toBe(true);});
  it('v113 keeps audit queries tenant scoped',()=>{expect(audit.includes("const where:Prisma.AuditLogWhereInput={tenantId}")).toBe(true);});
  it('v114 validates Mercado Pago webhook signatures before processing',()=>{expect(billing.includes("validSignature(paymentId,signature,requestId)")).toBe(true);});
  it('v115 deduplicates Mercado Pago webhook events',()=>{expect(billing.includes("provider_eventKey:{provider,eventKey}")).toBe(true);});
  it('v116 ignores stale webhook payment status regressions',()=>{expect(billing.includes("payment_status_regression_ignored")).toBe(true);});
  it('v117 uses CAS before applying payment approval',()=>{expect(billing.includes("payment.updateMany({where:{id:local.id,status:{not:'approved'}}")).toBe(true);});
  it('v118 checks payment external reference, amount and currency',()=>{expect(billing.includes("Referência do pagamento não confere") && billing.includes("Valor confirmado pelo Mercado Pago não confere") && billing.includes("Moeda do pagamento não confere")).toBe(true);});
  it('v119 keeps Prisma generated runtime import out of business modules',()=>{expect(!allBusiness.includes("from '../../../../generated-prisma'") || allBusiness.includes("import type")).toBe(true);});
  it('v120 keeps sensitive cache and security headers enabled at bootstrap',()=>{expect(main.includes('securityHeadersOptions()') && main.includes('sensitiveCacheMiddleware()')).toBe(true);});
});
