ALTER TABLE "Tenant" ADD COLUMN "secondaryColor" TEXT NOT NULL DEFAULT '#C9A84C';
ALTER TABLE "Tenant" ADD COLUMN "responsibleName" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "phone" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "contactEmail" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "logoUrl" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "organizerPhotoUrl" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "siteUrl" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "instagram" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "proposalText" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "planPeriod" TEXT;
ALTER TABLE "Tenant" ADD COLUMN "subscriptionExpiresAt" TIMESTAMP(3);
ALTER TABLE "Tenant" ALTER COLUMN "plan" SET DEFAULT 'starter';
ALTER TABLE "Client" ADD COLUMN "address" TEXT;
ALTER TABLE "Client" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Service" ADD COLUMN "code" TEXT;
ALTER TABLE "Service" ADD COLUMN "description" TEXT;
ALTER TABLE "Quote" ADD COLUMN "discountBps" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Quote" ADD COLUMN "finalTotalCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Quote" ADD COLUMN "validityDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Quote" ADD COLUMN "notes" TEXT;
ALTER TABLE "Quote" ADD COLUMN "sentAt" TIMESTAMP(3);
ALTER TABLE "Quote" ADD COLUMN "approvedAt" TIMESTAMP(3);
ALTER TABLE "QuoteItem" ADD COLUMN "configurationJson" JSONB;
ALTER TABLE "Project" ADD COLUMN "notes" TEXT;
CREATE TABLE "PlanLimit" ("plan" TEXT NOT NULL,"maxClients" INTEGER NOT NULL,"maxQuotesPerMonth" INTEGER NOT NULL,"maxUsers" INTEGER NOT NULL,"customPdf" BOOLEAN NOT NULL DEFAULT false,"projectManagement" TEXT NOT NULL DEFAULT 'basic',"advancedReports" BOOLEAN NOT NULL DEFAULT false,"monthlyPriceCents" INTEGER NOT NULL,"quarterlyPriceCents" INTEGER NOT NULL,"semiannualPriceCents" INTEGER NOT NULL,"annualPriceCents" INTEGER NOT NULL,CONSTRAINT "PlanLimit_pkey" PRIMARY KEY ("plan"));
CREATE TABLE "Subscription" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"plan" TEXT NOT NULL,"period" TEXT NOT NULL,"amountCents" INTEGER NOT NULL,"status" TEXT NOT NULL DEFAULT 'active',"startsAt" TIMESTAMP(3) NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ServiceTeamMember" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"serviceId" TEXT NOT NULL,"role" TEXT NOT NULL,"dailyRateCents" INTEGER NOT NULL,"included" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "ServiceTeamMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ServiceCost" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"serviceId" TEXT NOT NULL,"type" TEXT NOT NULL,"description" TEXT NOT NULL,"amountCents" INTEGER NOT NULL,CONSTRAINT "ServiceCost_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ServiceStage" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"serviceId" TEXT NOT NULL,"sequence" INTEGER NOT NULL,"description" TEXT NOT NULL,"duration" TEXT,CONSTRAINT "ServiceStage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "QuoteStage" ("id" TEXT NOT NULL,"quoteItemId" TEXT NOT NULL,"sequence" INTEGER NOT NULL,"description" TEXT NOT NULL,"duration" TEXT,"completed" BOOLEAN NOT NULL DEFAULT false,CONSTRAINT "QuoteStage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MonthlyFollowUp" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"projectId" TEXT NOT NULL,"month" INTEGER NOT NULL,"year" INTEGER NOT NULL,"visitDate" TIMESTAMP(3),"present" BOOLEAN NOT NULL DEFAULT false,"notes" TEXT,CONSTRAINT "MonthlyFollowUp_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Service_tenantId_code_key" ON "Service"("tenantId","code");
CREATE INDEX "Subscription_tenantId_status_idx" ON "Subscription"("tenantId","status");
CREATE INDEX "ServiceTeamMember_tenantId_serviceId_idx" ON "ServiceTeamMember"("tenantId","serviceId");
CREATE INDEX "ServiceCost_tenantId_serviceId_idx" ON "ServiceCost"("tenantId","serviceId");
CREATE UNIQUE INDEX "ServiceStage_serviceId_sequence_key" ON "ServiceStage"("serviceId","sequence");
CREATE INDEX "ServiceStage_tenantId_serviceId_idx" ON "ServiceStage"("tenantId","serviceId");
CREATE UNIQUE INDEX "QuoteStage_quoteItemId_sequence_key" ON "QuoteStage"("quoteItemId","sequence");
CREATE UNIQUE INDEX "MonthlyFollowUp_projectId_month_year_key" ON "MonthlyFollowUp"("projectId","month","year");
CREATE INDEX "MonthlyFollowUp_tenantId_projectId_idx" ON "MonthlyFollowUp"("tenantId","projectId");
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceTeamMember" ADD CONSTRAINT "ServiceTeamMember_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceCost" ADD CONSTRAINT "ServiceCost_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServiceStage" ADD CONSTRAINT "ServiceStage_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "QuoteStage" ADD CONSTRAINT "QuoteStage_quoteItemId_fkey" FOREIGN KEY ("quoteItemId") REFERENCES "QuoteItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MonthlyFollowUp" ADD CONSTRAINT "MonthlyFollowUp_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
