import Ionicons from '@expo/vector-icons/Ionicons';
import {useEffect,useMemo,useState} from 'react';
import {Pressable,StyleSheet,View} from 'react-native';
import {FormField} from '../../../components/FormField';
import {FormModal} from '../../../components/FormModal';
import {SearchField} from '../../../components/SearchField';
import {Text} from '../../../i18n';
import {theme} from '../../../theme';
import {purchasesApi,Supplier} from '../api/purchases.api';

type Form={id:string;name:string;document:string;email:string;phone:string;contactName:string;notes:string;active:boolean};
type StatusFilter='all'|'active'|'inactive';
const empty=():Form=>({id:'',name:'',document:'',email:'',phone:'',contactName:'',notes:'',active:true});
const fromSupplier=(s:Supplier):Form=>({id:s.id,name:s.name,document:s.document||'',email:s.email||'',phone:s.phone||'',contactName:s.contactName||'',notes:s.notes||'',active:s.active});

export function SuppliersManager({visible,onClose,onChanged}:{visible:boolean;onClose:()=>void;onChanged:()=>Promise<void>}){
 const[rows,setRows]=useState<Supplier[]>([]),[form,setForm]=useState<Form>(empty()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<StatusFilter>('all');
 const load=()=>purchasesApi.suppliers().then(setRows).catch(e=>setError(e instanceof Error?e.message:'Não foi possível carregar fornecedores.'));
 useEffect(()=>{if(visible)void load()},[visible]);
 const filtered=useMemo(()=>{const term=query.trim().toLowerCase();return rows.filter(s=>(status==='all'||(status==='active')===s.active)&&(!term||[s.name,s.document,s.contactName,s.email,s.phone].some(value=>value?.toLowerCase().includes(term))))},[rows,query,status]);
 const change=(key:keyof Form,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
 async function save(){if(form.name.trim().length<2){setError('Informe o nome do fornecedor.');return}setBusy(true);setError('');try{const payload={name:form.name.trim(),document:form.document.trim(),email:form.email.trim(),phone:form.phone.trim(),contactName:form.contactName.trim(),notes:form.notes.trim(),active:form.active};form.id?await purchasesApi.updateSupplier(form.id,payload):await purchasesApi.createSupplier(payload);setForm(empty());await Promise.all([load(),onChanged()])}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o fornecedor.')}finally{setBusy(false)}}
 async function toggle(s:Supplier){setBusy(true);setError('');try{await purchasesApi.updateSupplier(s.id,{active:!s.active});if(form.id===s.id)setForm(empty());await Promise.all([load(),onChanged()])}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar o fornecedor.')}finally{setBusy(false)}}
 return <FormModal visible={visible} title="Gestão de fornecedores" subtitle="Cadastre, edite ou inative fornecedores" size="lg" onClose={onClose}>
  <SearchField value={query} onChangeText={setQuery} placeholder="Buscar por nome, documento ou contato..."/>
  <View style={styles.filters}>{(['all','active','inactive'] as const).map(value=><Pressable key={value} onPress={()=>setStatus(value)} style={[styles.filter,status===value&&styles.filterActive]}><Text style={[styles.filterText,status===value&&styles.filterTextActive]}>{value==='all'?'Todos':value==='active'?'Ativos':'Inativos'}</Text></Pressable>)}</View>
  <View style={styles.list}>{filtered.length?filtered.map(s=><View key={s.id} style={[styles.row,!s.active&&styles.inactive]}><View style={{flex:1}}><Text style={styles.name}>{s.name}</Text><Text style={styles.meta}>{[s.contactName,s.email,s.phone,s.document].filter(Boolean).join(' · ')||'Sem dados de contato'}</Text><Text style={styles.status}>{s.active?'Ativo':'Inativo'}</Text></View><Pressable accessibilityLabel={`Editar ${s.name}`} onPress={()=>setForm(fromSupplier(s))} style={styles.icon}><Ionicons name="create-outline" size={18} color={theme.green2}/></Pressable><Pressable accessibilityLabel={`${s.active?'Inativar':'Ativar'} ${s.name}`} disabled={busy} onPress={()=>void toggle(s)} style={styles.icon}><Ionicons name={s.active?'pause-circle-outline':'play-circle-outline'} size={18} color={s.active?theme.danger:theme.green2}/></Pressable></View>):<Text style={styles.empty}>Nenhum fornecedor encontrado.</Text>}</View>
  <Text style={styles.heading}>{form.id?'Editar fornecedor':'Novo fornecedor'}</Text><FormField label="Nome" required value={form.name} onChangeText={v=>change('name',v)}/><View style={styles.fields}><FormField label="CPF/CNPJ" value={form.document} onChangeText={v=>change('document',v)} containerStyle={styles.field}/><FormField label="Contato" value={form.contactName} onChangeText={v=>change('contactName',v)} containerStyle={styles.field}/></View><View style={styles.fields}><FormField label="E-mail" value={form.email} onChangeText={v=>change('email',v)} containerStyle={styles.field}/><FormField label="Telefone" value={form.phone} onChangeText={v=>change('phone',v)} containerStyle={styles.field}/></View><FormField label="Observações" value={form.notes} onChangeText={v=>change('notes',v)}/>{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.actions}>{form.id?<Pressable style={styles.secondary} onPress={()=>setForm(empty())}><Text style={styles.secondaryText}>Cancelar edição</Text></Pressable>:<View/>}<Pressable disabled={busy} style={styles.primary} onPress={()=>void save()}><Text style={styles.primaryText}>{busy?'Salvando...':'Salvar fornecedor'}</Text></Pressable></View>
 </FormModal>;
}
const styles=StyleSheet.create({filters:{flexDirection:'row',flexWrap:'wrap',gap:7},filter:{borderWidth:1,borderColor:theme.border,borderRadius:18,paddingHorizontal:12,paddingVertical:7},filterActive:{backgroundColor:theme.green,borderColor:theme.green},filterText:{fontSize:11,fontWeight:'800',color:theme.muted},filterTextActive:{color:theme.white},list:{gap:7},row:{flexDirection:'row',alignItems:'center',gap:7,borderWidth:1,borderColor:theme.border,borderRadius:10,padding:10},inactive:{opacity:.55},name:{fontSize:13,fontWeight:'800',color:theme.ink},meta:{fontSize:10,color:theme.muted,marginTop:3},status:{fontSize:10,fontWeight:'800',color:theme.green2,marginTop:3},icon:{padding:7},empty:{fontSize:11,color:theme.muted,paddingVertical:12,textAlign:'center'},heading:{fontSize:12,fontWeight:'900',color:theme.ink,marginTop:8},fields:{flexDirection:'row',flexWrap:'wrap',gap:9},field:{flex:1,minWidth:200},actions:{flexDirection:'row',justifyContent:'space-between',gap:8},primary:{backgroundColor:theme.green,borderRadius:9,paddingHorizontal:14,paddingVertical:11},primaryText:{color:theme.white,fontWeight:'800',fontSize:12},secondary:{borderWidth:1,borderColor:theme.border,borderRadius:9,paddingHorizontal:14,paddingVertical:11},secondaryText:{color:theme.ink,fontWeight:'800',fontSize:12},error:{color:theme.danger,fontSize:11,fontWeight:'700'}});
