import { type ComponentProps,useCallback,useEffect,useState } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Pressable,ScrollView,useWindowDimensions,View } from 'react-native';
import { router } from 'expo-router';
import { Text,TextInput } from '../../../i18n';
import { api } from '../../../api';
import { AsyncButton } from '../../../components/AsyncButton';
import { AppShell } from '../../../components/AppShell';
import { AsyncState } from '../../../components/AsyncState';
import { feedbackAlert as Alert } from '../../../components/Feedback';
import { theme } from '../../../theme';
import { formatCep,formatCpfCnpj,formatPhone,formatUf,integerInput } from '../../../inputFormatters';
import { lookupCep } from '../../../cep';
import { cepMessage,isValidEmail } from '../../../formValidation';
import type { AccountData,TenantSettings } from '../settings.types';
import { errorMessage } from '../settings.utils';
import { s } from '../settings.styles';
import { Section,Field,Usage } from '../components/SettingsPrimitives';
import { LogoUpload } from '../components/LogoUpload';

type IoniconName=ComponentProps<typeof Ionicons>['name'];
const companyTabs=['Dados da empresa','Fiscal e endereço','Modelo de proposta','Identidade visual','Assinatura'] as const;

export default function CompanyScreen(){
  const[data,setData]=useState<AccountData>(),[tab,setTab]=useState(0),[form,setForm]=useState<TenantSettings>({}),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[formErrors,setFormErrors]=useState<Record<string,string>>({}),[cepBusy,setCepBusy]=useState(false);
  const compact=useWindowDimensions().width<760;
  const load=useCallback(()=>{setLoading(true);setLoadError('');api<AccountData>('/account').then(value=>{setData(value);setForm(value.tenant)}).catch((e:unknown)=>setLoadError(errorMessage(e))).finally(()=>setLoading(false))},[]);
  useEffect(load,[]);
  const change=(key:string,value:string)=>{setForm(current=>({...current,[key]:value}));setFormErrors(current=>({...current,[key]:''}))};
  async function fillCompanyCep(){const message=cepMessage(form.zipCode??'');if(message){setFormErrors(e=>({...e,zipCode:message}));return}if(!form.zipCode)return;try{setCepBusy(true);const address=await lookupCep(form.zipCode);setForm(current=>({...current,...address}));setFormErrors(e=>({...e,zipCode:''}))}catch(e:unknown){setFormErrors(current=>({...current,zipCode:errorMessage(e)||'CEP não encontrado.'}))}finally{setCepBusy(false)}}
  async function save(){if(!data)return;const next:Record<string,string>={};if(form.contactEmail&&!isValidEmail(form.contactEmail))next.contactEmail='Informe um e-mail válido.';const cep=cepMessage(form.zipCode??'');if(cep)next.zipCode=cep;const validity=Number(form.proposalValidityDays??30);if(!Number.isInteger(validity)||validity<1||validity>365)next.proposalValidityDays='Informe um valor entre 1 e 365 dias.';setFormErrors(next);if(Object.keys(next).length)return;try{setSaving(true);const payload:TenantSettings={name:form.name,responsibleName:form.responsibleName,phone:form.phone,contactEmail:form.contactEmail,siteUrl:form.siteUrl,instagram:form.instagram,legalName:form.legalName,document:form.document,stateRegistration:form.stateRegistration,municipalRegistration:form.municipalRegistration,zipCode:form.zipCode,addressLine:form.addressLine,addressNumber:form.addressNumber,addressComplement:form.addressComplement,neighborhood:form.neighborhood,city:form.city,state:form.state,proposalValidityDays:Number(form.proposalValidityDays)||30,proposalPaymentTerms:form.proposalPaymentTerms,proposalFooter:form.proposalFooter,pixKey:form.pixKey};if(data.features.customPdf)Object.assign(payload,{primaryColor:form.primaryColor,secondaryColor:form.secondaryColor,proposalText:form.proposalText});const tenant=await api<TenantSettings>('/account/settings',{method:'PATCH',body:JSON.stringify(payload)});setForm(tenant);Alert.alert('Dados da empresa salvos')}catch(error:unknown){Alert.alert('Não foi possível salvar',errorMessage(error))}finally{setSaving(false)}}
  if(loading||loadError)return <AppShell title="Empresa"><AsyncState loading={loading} error={loadError} onRetry={load}/></AppShell>;
  if(!data)return <AppShell title="Empresa"><AsyncState loading={loading} onRetry={load}/></AppShell>;
  const current=companyTabs[tab]; const editable=current!=='Assinatura'; const locked=!data.features.customPdf;
  return <AppShell title="Empresa" subtitle="Dados cadastrais, fiscais, identidade e informações comerciais da empresa." action={editable?<AsyncButton busy={saving} onPress={save} label="Salvar alterações" tone="header"/>:undefined}>
    <View style={[s.layout,compact&&s.layoutCompact]}><ScrollView horizontal={compact} style={[s.tabs,compact&&s.tabsCompact]} contentContainerStyle={compact?s.tabsRow:undefined}>{companyTabs.map((label,index)=><Pressable key={label} onPress={()=>setTab(index)} style={[s.tab,current===label&&s.tabOn]}><Ionicons name={(label==='Dados da empresa'?'business-outline':label==='Fiscal e endereço'?'location-outline':label==='Modelo de proposta'?'document-text-outline':label==='Identidade visual'?'color-palette-outline':'card-outline') as IoniconName} size={17} color={current===label?theme.green2:theme.muted}/><Text style={[s.tabText,current===label&&s.tabTextOn]}>{label}</Text></Pressable>)}</ScrollView>
      <View style={s.content}>{current==='Dados da empresa'&&<Section title="Dados da empresa" subtitle="Informações institucionais e de contato da empresa."><View style={s.grid}><Field label="Nome da empresa" value={form.name} change={v=>change('name',v)}/><Field label="Nome da responsável" value={form.responsibleName} change={v=>change('responsibleName',v)}/><Field label="Telefone / WhatsApp" value={form.phone} change={v=>change('phone',formatPhone(v))} keyboardType="phone-pad"/><Field label="E-mail" error={formErrors.contactEmail} value={form.contactEmail} change={v=>change('contactEmail',v)}/><Field label="Site" value={form.siteUrl} change={v=>change('siteUrl',v)}/><Field label="Instagram" value={form.instagram} change={v=>change('instagram',v)}/></View></Section>}
      {current==='Fiscal e endereço'&&<Section title="Dados fiscais e endereço" subtitle="Dados cadastrais usados em propostas, contratos e documentos."><View style={s.grid}><Field label="Razão social" value={form.legalName} change={v=>change('legalName',v)}/><Field label="CPF / CNPJ" value={form.document} change={v=>change('document',formatCpfCnpj(v))} keyboardType="number-pad"/><Field label="Inscrição estadual" value={form.stateRegistration} change={v=>change('stateRegistration',v)}/><Field label="Inscrição municipal" value={form.municipalRegistration} change={v=>change('municipalRegistration',v)}/><Field label="CEP" value={form.zipCode} error={formErrors.zipCode} helper={cepBusy?'Consultando CEP...':'O endereço é preenchido automaticamente ao sair do campo.'} change={v=>change('zipCode',formatCep(v))} onBlur={fillCompanyCep} keyboardType="number-pad"/><Field label="Endereço" value={form.addressLine} change={v=>change('addressLine',v)}/><Field label="Número" value={form.addressNumber} change={v=>change('addressNumber',v)}/><Field label="Complemento" value={form.addressComplement} change={v=>change('addressComplement',v)}/><Field label="Bairro" value={form.neighborhood} change={v=>change('neighborhood',v)}/><Field label="Cidade" value={form.city} change={v=>change('city',v)}/><Field label="UF" value={form.state} change={v=>change('state',formatUf(v))} autoCapitalize="characters"/></View></Section>}
      {current==='Modelo de proposta'&&<Section title="Padrões comerciais da empresa" subtitle="Padrões usados nas novas propostas. Podem ser ajustados em cada orçamento."><View style={s.grid}><Field label="Validade padrão (dias)" required error={formErrors.proposalValidityDays} value={String(form.proposalValidityDays??30)} change={v=>change('proposalValidityDays',integerInput(v,3))} keyboardType="number-pad"/><Field label="Chave PIX" value={form.pixKey} change={v=>change('pixKey',v)}/><View style={s.full}><Text style={s.label}>CONDIÇÕES DE PAGAMENTO</Text><TextInput multiline value={form.proposalPaymentTerms??''} onChangeText={(v:string)=>change('proposalPaymentTerms',v)} style={[s.input,s.textarea]}/></View><View style={s.full}><Text style={s.label}>RODAPÉ / OBSERVAÇÕES PADRÃO</Text><TextInput multiline value={form.proposalFooter??''} onChangeText={(v:string)=>change('proposalFooter',v)} style={[s.input,s.textarea]}/></View></View></Section>}
      {current==='Identidade visual'&&<Section title="Identidade visual" subtitle="Logo, cores e apresentação institucional da empresa.">{locked&&<View style={s.lock}><Ionicons name="lock-closed" size={18} color={theme.gold}/><View style={{flex:1}}><Text style={s.lockTitle}>Cores e mensagem personalizadas: Pro e Business</Text><Text style={s.lockText}>No Starter você ainda pode usar o logo da empresa na proposta.</Text></View><Pressable onPress={()=>router.push('/plans')}><Text style={s.upgrade}>Ver planos</Text></Pressable></View>}<View style={s.visual}><View style={s.full}><LogoUpload value={form.logoUrl} enabled={data.features.logoPdf} onChanged={logoUrl=>change('logoUrl',logoUrl??'')}/></View><Field label="Cor primária" value={form.primaryColor} change={v=>change('primaryColor',v)} disabled={locked}/><Field label="Cor de destaque" value={form.secondaryColor} change={v=>change('secondaryColor',v)} disabled={locked}/><View style={s.full}><Text style={s.label}>TEXTO DE BOAS-VINDAS DA PROPOSTA</Text><TextInput editable={!locked} multiline value={form.proposalText??''} onChangeText={(v:string)=>change('proposalText',v)} style={[s.input,s.textarea,locked&&s.inputDisabled]}/></View></View></Section>}
      {current==='Assinatura'&&<Section title={`Plano ${data.tenant.plan}`} subtitle="Plano contratado e consumo atual da empresa."><Usage label="Clientes" value={data.usage.clients} max={data.limit.maxClients}/><Usage label="Orçamentos neste mês" value={data.usage.quotes} max={data.limit.maxQuotesPerMonth}/><Usage label="Usuários" value={data.usage.users} max={data.limit.maxUsers}/><Pressable onPress={()=>router.push('/plans')} style={s.planButton}><Text style={s.planButtonText}>Comparar e alterar plano</Text><Ionicons name="arrow-forward" size={16} color={theme.g900}/></Pressable></Section>}</View></View>
  </AppShell>;
}
