import {useEffect,useState} from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import {Pressable,StyleSheet,View} from 'react-native';
import {router} from 'expo-router';
import {api} from '../../../api';
import {AppShell} from '../../../components/AppShell';
import {AsyncState} from '../../../components/AsyncState';
import {AsyncButton} from '../../../components/AsyncButton';
import {Text} from '../../../i18n';
import {theme} from '../../../theme';
import {useFeedback} from '../../../components/Feedback';

type SmtpStatus={configured:boolean;host:string|null;port:number;secure:boolean;from:string|null;userConfigured:boolean;passwordConfigured:boolean;verification?:{ok:boolean;reason?:string}};
export default function EmailSettingsScreen(){const[data,setData]=useState<SmtpStatus>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);const{notify}=useFeedback();const load=()=>{setLoading(true);setError('');api<SmtpStatus>('/mail/status').then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:'Não foi possível consultar o SMTP')).finally(()=>setLoading(false))};useEffect(load,[]);async function test(){try{setBusy(true);const result=await api<{sent:boolean;reason?:string}>('/mail/test',{method:'POST'});notify({tone:result.sent?'success':'error',title:result.sent?'E-mail de teste enviado':'Falha no envio',message:result.sent?'Confira sua caixa de entrada.':result.reason==='not_configured'?'Configure as variáveis SMTP no backend.':'O servidor SMTP recusou o envio.'})}catch(e:unknown){notify({tone:'error',title:'Não foi possível testar o SMTP',message:e instanceof Error?e.message:'Erro inesperado'})}finally{setBusy(false)}}return <AppShell title="E-mail e SMTP" subtitle="Configuração dos e-mails de primeiro acesso, recuperação de senha e notificações."><Pressable onPress={()=>router.push('/settings')} style={s.back}><Ionicons name="arrow-back" size={16} color={theme.green2}/><Text style={s.backText}>Voltar para Configurações</Text></Pressable>{loading||error?<AsyncState loading={loading} error={error} onRetry={load}/>:data&&<><View style={[s.banner,data.verification?.ok&&s.ok]}><Ionicons name={data.verification?.ok?'checkmark-circle-outline':'alert-circle-outline'} size={22} color={data.verification?.ok?theme.green2:theme.gold}/><View style={{flex:1}}><Text style={s.bannerTitle}>{data.verification?.ok?'SMTP conectado':'SMTP ainda não validado'}</Text><Text style={s.muted}>{data.verification?.ok?'O backend conseguiu autenticar no servidor de e-mail.':'Confira as variáveis de ambiente do serviço backend.'}</Text></View></View><View style={s.card}><Row label="Servidor" value={data.host??'Não configurado'}/><Row label="Porta" value={String(data.port)}/><Row label="Segurança" value={data.secure?'SSL/TLS':'STARTTLS / sem SSL direto'}/><Row label="Remetente" value={data.from??'Não configurado'}/><Row label="Usuário SMTP" value={data.userConfigured?'Configurado':'Não configurado'}/><Row label="Senha SMTP" value={data.passwordConfigured?'Configurada':'Não configurada'}/></View><View style={s.help}><Text style={s.helpTitle}>Variáveis do backend</Text><Text style={s.code}>SMTP_HOST{`\n`}SMTP_PORT{`\n`}SMTP_SECURE{`\n`}SMTP_USER{`\n`}SMTP_PASS{`\n`}SMTP_FROM</Text><Text style={s.muted}>No Render, cadastre essas variáveis no serviço luviepro-api-hml. A senha nunca é exibida no LuviePro.</Text></View><AsyncButton busy={busy} label="Enviar e-mail de teste para mim" onPress={test}/></>}</AppShell>}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,marginBottom:14},backText:{fontSize:12,fontWeight:'800',color:theme.green2},banner:{borderWidth:1,borderColor:theme.goldLight,backgroundColor:theme.goldPale,borderRadius:13,padding:14,flexDirection:'row',gap:10,alignItems:'center',marginBottom:14},ok:{backgroundColor:theme.green50,borderColor:theme.border},bannerTitle:{fontSize:13,fontWeight:'900',color:theme.ink},muted:{fontSize:11,lineHeight:17,color:theme.muted,marginTop:3},card:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,overflow:'hidden',marginBottom:14},row:{padding:13,borderBottomWidth:1,borderBottomColor:theme.border,flexDirection:'row',justifyContent:'space-between',gap:16},label:{fontSize:11,fontWeight:'800',color:theme.muted},value:{fontSize:12,fontWeight:'800',color:theme.ink,textAlign:'right',flex:1},help:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:15,marginBottom:14},helpTitle:{fontSize:13,fontWeight:'900',color:theme.ink},code:{fontFamily:'monospace',fontSize:12,lineHeight:19,color:theme.green2,marginVertical:10}});
