import {useCallback,useEffect,useMemo,useState} from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import {Pressable,StyleSheet,useWindowDimensions,View} from 'react-native';
import {router} from 'expo-router';
import {AppShell} from '../../../components/AppShell';
import {AsyncState} from '../../../components/AsyncState';
import {HeaderAction} from '../../../components/HeaderAction';
import {FormModal} from '../../../components/FormModal';
import {FormField} from '../../../components/FormField';
import {AsyncButton} from '../../../components/AsyncButton';
import {SearchField} from '../../../components/SearchField';
import {Text} from '../../../i18n';
import {theme} from '../../../theme';
import {useFeedback} from '../../../components/Feedback';
import {FinancePaymentMethod,financeApi} from '../../finance/api/finance.api';

type Status='all'|'active'|'inactive';
type Form={id:string;name:string;code:string;active:boolean};
const empty=():Form=>({id:'',name:'',code:'',active:true});
const msg=(e:unknown)=>e instanceof Error?e.message:'Erro inesperado';
const PAGE_SIZE=10;

export default function PaymentMethodsScreen(){
 const[items,setItems]=useState<FinancePaymentMethod[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<Status>('all'),[page,setPage]=useState(1),[form,setForm]=useState<Form>(empty()),[nameError,setNameError]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const compact=useWindowDimensions().width<760;const{notify,confirm}=useFeedback();
 const load=useCallback(()=>{setLoading(true);setError('');financeApi.managePaymentMethods().then(setItems).catch(e=>setError(msg(e))).finally(()=>setLoading(false))},[]);
 useEffect(load,[]);useEffect(()=>setPage(1),[query,status]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(i=>(!q||i.name.toLowerCase().includes(q)||i.code.toLowerCase().includes(q))&&(status==='all'||(status==='active'?i.active:!i.active)))},[items,query,status]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages]);
 const paged=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),active=items.filter(i=>i.active).length,used=items.filter(i=>(i.usageCount||0)>0).length;
 const create=()=>{setForm(empty());setNameError('');setOpen(true)};const edit=(i:FinancePaymentMethod)=>{setForm({id:i.id,name:i.name,code:i.code,active:i.active});setNameError('');setOpen(true)};
 async function save(){const name=form.name.trim();if(name.length<2){setNameError('Informe pelo menos 2 caracteres.');return}try{setBusy(true);if(form.id)await financeApi.updatePaymentMethod(form.id,{name,active:form.active});else await financeApi.createPaymentMethod({name});setOpen(false);await load();notify({tone:'success',title:form.id?'Forma de pagamento atualizada':'Forma de pagamento cadastrada'})}catch(e){notify({tone:'error',title:'Não foi possível salvar a forma de pagamento',message:msg(e)})}finally{setBusy(false)}}
 async function toggle(i:FinancePaymentMethod){if(i.active){const count=i.usageCount||0;const ok=await confirm({title:'Inativar forma de pagamento?',message:count?`Esta forma aparece em ${count} movimentação(ões). O histórico será mantido, mas ela não poderá ser usada em novos recebimentos ou pagamentos.`:'A forma de pagamento deixará de ficar disponível em novos lançamentos.',confirmLabel:'Inativar',danger:true});if(!ok)return}try{setBusy(true);await financeApi.updatePaymentMethod(i.id,{active:!i.active});await load();notify({tone:'success',title:i.active?'Forma de pagamento inativada':'Forma de pagamento ativada'})}catch(e){notify({tone:'error',title:'Não foi possível alterar a forma de pagamento',message:msg(e)})}finally{setBusy(false)}}
 return <AppShell title="Formas de pagamento" subtitle="Parametrize as formas usadas em recebimentos, pagamentos e baixas financeiras." action={<HeaderAction label="Nova forma" onPress={create}/>}> 
  <Pressable onPress={()=>router.push('/settings')} style={s.back}><Ionicons name="arrow-back" size={16} color={theme.green2}/><Text style={s.backText}>Voltar para Configurações</Text></Pressable>
  {loading||error?<AsyncState loading={loading} error={error} onRetry={load}/>:<>
   <View style={[s.summaryRow,compact&&s.summaryCompact]}><Summary label="Total" value={String(items.length)} icon="card-outline"/><Summary label="Ativas" value={String(active)} icon="checkmark-circle-outline"/><Summary label="Em uso" value={String(used)} icon="receipt-outline"/></View>
   <View style={s.panel}><View style={[s.toolbar,compact&&s.toolbarCompact]}><View style={s.search}><SearchField value={query} onChangeText={setQuery} placeholder="Buscar forma de pagamento..."/></View><View style={s.filters}><Filter label="Todas" active={status==='all'} onPress={()=>setStatus('all')}/><Filter label="Ativas" active={status==='active'} onPress={()=>setStatus('active')}/><Filter label="Inativas" active={status==='inactive'} onPress={()=>setStatus('inactive')}/></View></View>
    {paged.length===0?<View style={s.empty}><Ionicons name="card-outline" size={26} color={theme.muted}/><Text style={s.emptyTitle}>Nenhuma forma de pagamento encontrada</Text></View>:paged.map((i,index)=><View key={i.id} style={[s.row,index===0&&s.first]}><View style={s.rowInfo}><Text style={s.rowTitle}>{i.name}</Text><Text style={s.rowMeta}>Código: {i.code} · {i.usageCount||0} movimentação(ões)</Text></View><StatusBadge active={i.active}/><Pressable onPress={()=>edit(i)} style={s.iconButton}><Ionicons name="pencil-outline" size={17} color={theme.green2}/></Pressable><Pressable disabled={busy} onPress={()=>void toggle(i)} style={s.iconButton}><Ionicons name={i.active?'pause-circle-outline':'play-circle-outline'} size={18} color={i.active?theme.muted:theme.green2}/></Pressable></View>)}
    {filtered.length>PAGE_SIZE&&<View style={s.pagination}><Text style={s.pageInfo}>{(page-1)*PAGE_SIZE+1}-{Math.min(page*PAGE_SIZE,filtered.length)} de {filtered.length}</Text><View style={s.pageButtons}><Pressable disabled={page===1} onPress={()=>setPage(p=>Math.max(1,p-1))} style={[s.pageButton,page===1&&s.disabled]}><Ionicons name="chevron-back" size={17} color={theme.ink}/></Pressable><Text style={s.pageNumber}>{page} / {totalPages}</Text><Pressable disabled={page===totalPages} onPress={()=>setPage(p=>Math.min(totalPages,p+1))} style={[s.pageButton,page===totalPages&&s.disabled]}><Ionicons name="chevron-forward" size={17} color={theme.ink}/></Pressable></View></View>}
   </View>
  </>}
  <FormModal visible={open} title={form.id?'Editar forma de pagamento':'Nova forma de pagamento'} subtitle="A forma ativa ficará disponível no Financeiro, Vendas e Compras." onClose={()=>!busy&&setOpen(false)} footer={<><Pressable style={s.cancel} onPress={()=>setOpen(false)}><Text style={s.cancelText}>Cancelar</Text></Pressable><AsyncButton busy={busy} label={form.id?'Salvar alterações':'Cadastrar forma'} onPress={save}/></>}> 
   <FormField label="Nome" required value={form.name} error={nameError} onChangeText={v=>{setForm(f=>({...f,name:v}));setNameError('')}} placeholder="Ex.: PIX, Cartão, Transferência" autoFocus/>
   {form.id&&<FormField label="Código interno" value={form.code} onChangeText={()=>{}} editable={false} helper="O código é preservado para manter o histórico das movimentações."/>}
   {form.id&&<Pressable onPress={()=>setForm(f=>({...f,active:!f.active}))} style={[s.activeChoice,form.active&&s.activeChoiceOn]}><Ionicons name={form.active?'checkmark-circle':'ellipse-outline'} size={18} color={form.active?theme.green2:theme.muted}/><Text style={s.activeChoiceText}>{form.active?'Forma ativa':'Forma inativa'}</Text></Pressable>}
  </FormModal>
 </AppShell>;
}
function Summary({label,value,icon}:{label:string;value:string;icon:any}){return <View style={s.summary}><View style={s.summaryIcon}><Ionicons name={icon} size={17} color={theme.green2}/></View><View><Text style={s.summaryLabel}>{label}</Text><Text style={s.summaryValue}>{value}</Text></View></View>}
function StatusBadge({active}:{active:boolean}){return <View style={[s.status,active?s.statusOn:undefined]}><Text style={[s.statusText,active&&s.statusTextOn]}>{active?'Ativo':'Inativo'}</Text></View>}
function Filter({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.filter,active&&s.filterOn]}><Text style={[s.filterText,active&&s.filterTextOn]}>{label}</Text></Pressable>}
const s=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,marginBottom:14,paddingVertical:4},backText:{fontSize:12,fontWeight:'800',color:theme.green2},summaryRow:{flexDirection:'row',gap:12,marginBottom:18},summaryCompact:{flexWrap:'wrap'},summary:{minWidth:180,flex:1,backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:15,flexDirection:'row',alignItems:'center',gap:11},summaryIcon:{width:36,height:36,borderRadius:10,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},summaryLabel:{fontSize:11,color:theme.muted},summaryValue:{fontFamily:'serif',fontSize:20,fontWeight:'800',color:theme.ink,marginTop:2},panel:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:16,overflow:'hidden'},toolbar:{padding:14,borderBottomWidth:1,borderBottomColor:theme.border,flexDirection:'row',alignItems:'center',gap:12},toolbarCompact:{flexDirection:'column',alignItems:'stretch'},search:{flex:1,minWidth:220},filters:{flexDirection:'row',gap:6,flexWrap:'wrap'},filter:{borderWidth:1,borderColor:theme.border,borderRadius:999,paddingHorizontal:10,paddingVertical:7,backgroundColor:theme.white},filterOn:{backgroundColor:theme.green,borderColor:theme.green},filterText:{fontSize:10,fontWeight:'900',color:theme.muted},filterTextOn:{color:theme.white},row:{minHeight:72,paddingHorizontal:15,paddingVertical:12,borderTopWidth:1,borderTopColor:theme.border,flexDirection:'row',alignItems:'center',gap:10},first:{borderTopWidth:0},rowInfo:{flex:1,minWidth:0},rowTitle:{fontSize:13,fontWeight:'900',color:theme.ink},rowMeta:{fontSize:11,color:theme.muted,marginTop:4},status:{borderRadius:999,paddingHorizontal:9,paddingVertical:5,backgroundColor:'#F1F2EF'},statusOn:{backgroundColor:theme.green50},statusText:{fontSize:9,fontWeight:'900',color:theme.muted,textTransform:'uppercase'},statusTextOn:{color:theme.green2},iconButton:{width:34,height:34,borderRadius:9,borderWidth:1,borderColor:theme.border,alignItems:'center',justifyContent:'center'},empty:{padding:32,alignItems:'center',gap:8},emptyTitle:{fontSize:13,fontWeight:'800',color:theme.muted},pagination:{borderTopWidth:1,borderTopColor:theme.border,padding:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},pageInfo:{fontSize:10,color:theme.muted},pageButtons:{flexDirection:'row',alignItems:'center',gap:8},pageButton:{width:32,height:32,borderWidth:1,borderColor:theme.border,borderRadius:8,alignItems:'center',justifyContent:'center'},pageNumber:{fontSize:10,fontWeight:'900',color:theme.ink},disabled:{opacity:.35},cancel:{paddingHorizontal:14,paddingVertical:10},cancelText:{fontSize:12,fontWeight:'800',color:theme.muted},activeChoice:{marginTop:4,borderWidth:1,borderColor:theme.border,borderRadius:10,padding:11,flexDirection:'row',alignItems:'center',gap:8},activeChoiceOn:{backgroundColor:theme.green50},activeChoiceText:{fontSize:12,fontWeight:'800',color:theme.ink}});
