import { Type } from 'class-transformer';
import { IsArray, IsIn, IsInt, IsOptional, IsString, IsUrl, Max, Min, MinLength, ValidateNested } from 'class-validator';
export class CalculateDto { @IsInt() @Min(0) dailyRateCents!:number; @IsInt() @Min(0) days!:number; @IsInt() @Min(0) people!:number; @IsInt() @Min(0) variableCostCents!:number; @IsInt() @Min(0) fixedCostCents!:number; @IsInt() @Min(0) safetyMarginBps!:number; @IsOptional() @IsIn(['per_day','fixed','per_person','per_person_day']) variableCostMode?:string; }
export class QuoteProductItemDto { @IsString() productId!:string; @IsInt() @Min(1) quantity!:number; @IsOptional() @IsInt() @Min(0) unitPriceCents?:number; @IsOptional() @IsInt() @Min(0) @Max(10000) discountBps?:number; }
export class QuoteStageDto { @IsString() @MinLength(1) description!:string; @IsOptional() @IsString() duration?:string; }
export class QuoteItemDto { @IsString() serviceId!:string; @IsOptional() @IsInt() @Min(0) days?:number; @IsOptional() @IsInt() @Min(0) people?:number; @IsOptional() @IsInt() @Min(0) dailyRateCents?:number; @IsOptional() @IsInt() @Min(0) variableCostCents?:number; @IsOptional() @IsInt() @Min(0) fixedCostCents?:number; @IsOptional() @IsInt() @Min(0) safetyMarginBps?:number; @IsOptional() @IsArray() @ValidateNested({each:true}) @Type(()=>QuoteStageDto) stages?:QuoteStageDto[]; }
export class CreateQuoteDto { @IsString() clientId!:string; @IsArray() @ValidateNested({each:true}) @Type(()=>QuoteItemDto) items:QuoteItemDto[]=[]; @IsOptional() @IsArray() @ValidateNested({each:true}) @Type(()=>QuoteProductItemDto) productItems?:QuoteProductItemDto[]; @IsOptional() @IsInt() @Min(0) discountBps?:number; @IsOptional() @IsInt() @Min(1) validityDays?:number; @IsOptional() @IsString() notes?:string; @IsOptional() @IsUrl({require_protocol:true}) paymentLinkUrl?:string; }
export class UpdateQuoteDto { @IsOptional() @IsArray() @ValidateNested({each:true}) @Type(()=>QuoteItemDto) items?: QuoteItemDto[]; @IsOptional() @IsArray() @ValidateNested({each:true}) @Type(()=>QuoteProductItemDto) productItems?: QuoteProductItemDto[]; @IsOptional() @IsInt() @Min(0) @Max(10000) discountBps?: number; @IsOptional() @IsInt() @Min(1) @Max(365) validityDays?: number; @IsOptional() @IsString() notes?: string; @IsOptional() @IsUrl({require_protocol:true}) paymentLinkUrl?: string; }
export class QuoteStatusDto { @IsIn(['draft','sent','rejected']) status!: string; }
export class PublicProposalDecisionDto { @IsIn(['approved','rejected']) decision!: string; @IsString() @MinLength(2) name!: string; }
