import {useCallback,useEffect,useState} from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import {Pressable,StyleSheet,View} from 'react-native';
import {Text} from '../../../i18n';
import {AsyncButton} from '../../../components/AsyncButton';
import {FormField} from '../../../components/FormField';
import {useFeedback} from '../../../components/Feedback';
import {theme} from '../../../theme';
import {ProductCategory,ProductUnit,productsApi} from '../../products/api/products.api';
import {Section} from '../components/SettingsPrimitives';

type CategoryForm={id:string;name:string;active:boolean};
type UnitForm={id:string;code:string;name:string;active:boolean;sortOrder:string};
const newCategory=():CategoryForm=>({id:'',name:'',active:true});
const newUnit=():UnitForm=>({id:'',code:'',name:'',active:true,sortOrder:'0'});
const message=(e:unknown)=>e instanceof Error?e.message:'Erro inesperado';

export function ProductParametersPanel(){
 const[categories,setCategories]=useState<ProductCategory[]>([]),[units,setUnits]=useState<ProductUnit[]>([]),[category,setCategory]=useState<CategoryForm>(newCategory()),[unit,setUnit]=useState<UnitForm>(newUnit()),[categoryError,setCategoryError]=useState(''),[unitErrors,setUnitErrors]=useState<{code?:string;name?:string}>({}),[busy,setBusy]=useState(false);
 const{notify}=useFeedback();
 const load=useCallback(async()=>{try{const[c,u]=await Promise.all([productsApi.categories(),productsApi.units()]);setCategories(c);setUnits(u)}catch(e){notify({tone:'error',title:'Não foi possível carregar as parametrizações',message:message(e)})}},[notify]);
 useEffect(()=>{void load()},[load]);
 async function saveCategory(){const name=category.name.trim();if(name.length<2){setCategoryError('Informe pelo menos 2 caracteres.');return}try{setBusy(true);category.id?await productsApi.updateCategory(category.id,{name,active:category.active}):await productsApi.createCategory(name,category.active);setCategory(newCategory());setCategoryError('');await load();notify({tone:'success',title:category.id?'Categoria atualizada':'Categoria cadastrada'})}catch(e){notify({tone:'error',title:'Não foi possível salvar a categoria',message:message(e)})}finally{setBusy(false)}}
 async function saveUnit(){const code=unit.code.trim().toLowerCase().replace(/\s+/g,'-');const name=unit.name.trim();const errors:{code?:string;name?:string}={};if(!code)errors.code='Informe a sigla/código da unidade.';if(name.length<2)errors.name='Informe o nome da unidade.';setUnitErrors(errors);if(Object.keys(errors).length)return;try{setBusy(true);const payload={code,name,active:unit.active,sortOrder:Math.max(0,Number(unit.sortOrder)||0)};unit.id?await productsApi.updateUnit(unit.id,payload):await productsApi.createUnit(payload);setUnit(newUnit());setUnitErrors({});await load();notify({tone:'success',title:unit.id?'Unidade atualizada':'Unidade cadastrada'})}catch(e){notify({tone:'error',title:'Não foi possível salvar a unidade',message:message(e)})}finally{setBusy(false)}}
 return <View style={local.gap}>
  <Section title="Categorias de produtos" subtitle="Cadastros usados no campo Categoria dos produtos. Categorias inativas permanecem no histórico, mas não ficam disponíveis para novos cadastros.">
   <View style={local.formRow}><FormField label="Nome da categoria" required error={categoryError} value={category.name} onChangeText={v=>{setCategory(f=>({...f,name:v}));setCategoryError('')}} containerStyle={local.grow}/><ActiveToggle active={category.active} onPress={()=>setCategory(f=>({...f,active:!f.active}))}/></View>
   <View style={local.formActions}>{category.id?<Pressable style={local.cancel} onPress={()=>{setCategory(newCategory());setCategoryError('')}}><Text style={local.cancelText}>Cancelar edição</Text></Pressable>:null}<AsyncButton busy={busy} label={category.id?'Salvar categoria':'+ Adicionar categoria'} onPress={saveCategory}/></View>
   <View style={local.list}>{categories.map(c=><ParameterRow key={c.id} title={c.name} meta="Categoria" active={c.active} onEdit={()=>setCategory({id:c.id,name:c.name,active:c.active})} onToggle={async()=>{try{setBusy(true);await productsApi.updateCategory(c.id,{name:c.name,active:!c.active});await load()}catch(e){notify({tone:'error',title:'Não foi possível alterar a categoria',message:message(e)})}finally{setBusy(false)}}}/>)}</View>
  </Section>
  <Section title="Unidades de produtos" subtitle="Defina as unidades disponíveis no cadastro de produtos, como un, kit, cx, pct, m ou kg. O produto passa a selecionar uma unidade cadastrada aqui.">
   <View style={local.formRow}><FormField label="Sigla / código" required error={unitErrors.code} value={unit.code} onChangeText={v=>{setUnit(f=>({...f,code:v.toLowerCase().replace(/\s/g,'')}));setUnitErrors(e=>({...e,code:undefined}))}} placeholder="Ex.: un" containerStyle={local.code}/><FormField label="Descrição" required error={unitErrors.name} value={unit.name} onChangeText={v=>{setUnit(f=>({...f,name:v}));setUnitErrors(e=>({...e,name:undefined}))}} placeholder="Ex.: Unidade" containerStyle={local.grow}/><FormField label="Ordem" value={unit.sortOrder} onChangeText={v=>setUnit(f=>({...f,sortOrder:v.replace(/\D/g,'')}))} keyboardType="number-pad" containerStyle={local.order}/><ActiveToggle active={unit.active} onPress={()=>setUnit(f=>({...f,active:!f.active}))}/></View>
   <View style={local.formActions}>{unit.id?<Pressable style={local.cancel} onPress={()=>{setUnit(newUnit());setUnitErrors({})}}><Text style={local.cancelText}>Cancelar edição</Text></Pressable>:null}<AsyncButton busy={busy} label={unit.id?'Salvar unidade':'+ Adicionar unidade'} onPress={saveUnit}/></View>
   <View style={local.list}>{units.map(u=><ParameterRow key={u.id} title={`${u.name} (${u.code})`} meta={`Ordem ${u.sortOrder}`} active={u.active} onEdit={()=>setUnit({id:u.id,code:u.code,name:u.name,active:u.active,sortOrder:String(u.sortOrder||0)})} onToggle={async()=>{try{setBusy(true);await productsApi.updateUnit(u.id,{code:u.code,name:u.name,active:!u.active,sortOrder:u.sortOrder});await load()}catch(e){notify({tone:'error',title:'Não foi possível alterar a unidade',message:message(e)})}finally{setBusy(false)}}}/>)}</View>
  </Section>
 </View>
}
function ActiveToggle({active,onPress}:{active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={local.active}><Ionicons name={active?'checkmark-circle':'ellipse-outline'} size={19} color={active?theme.green2:theme.muted}/><Text style={local.activeText}>{active?'Ativo':'Inativo'}</Text></Pressable>}
function ParameterRow({title,meta,active,onEdit,onToggle}:{title:string;meta:string;active:boolean;onEdit:()=>void;onToggle:()=>void}){return <View style={[local.row,!active&&local.inactive]}><View style={local.rowInfo}><Text style={local.title}>{title}</Text><Text style={local.meta}>{meta} · {active?'Ativo':'Inativo'}</Text></View><Pressable style={local.icon} onPress={onEdit}><Ionicons name="pencil-outline" size={16} color={theme.green2}/></Pressable><Pressable style={local.icon} onPress={onToggle}><Ionicons name={active?'pause-circle-outline':'play-circle-outline'} size={17} color={active?theme.muted:theme.green2}/></Pressable></View>}
const local=StyleSheet.create({gap:{gap:14},formRow:{flexDirection:'row',flexWrap:'wrap',gap:10,alignItems:'flex-start'},grow:{flex:1,minWidth:220},code:{width:150},order:{width:100},active:{minHeight:42,marginTop:17,paddingHorizontal:12,borderWidth:1,borderColor:theme.border,borderRadius:9,flexDirection:'row',alignItems:'center',gap:7},activeText:{fontSize:11,fontWeight:'800',color:theme.ink},formActions:{marginTop:10,flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:8,flexWrap:'wrap'},cancel:{paddingHorizontal:12,paddingVertical:9},cancelText:{fontSize:11,fontWeight:'800',color:theme.muted},list:{marginTop:16,gap:7},row:{minHeight:54,borderWidth:1,borderColor:theme.border,borderRadius:10,padding:10,flexDirection:'row',alignItems:'center',gap:7,backgroundColor:theme.white},inactive:{opacity:.65,backgroundColor:theme.cream},rowInfo:{flex:1},title:{fontSize:12,fontWeight:'800',color:theme.ink},meta:{fontSize:10,color:theme.muted,marginTop:3},icon:{width:34,height:34,borderWidth:1,borderColor:theme.border,borderRadius:8,alignItems:'center',justifyContent:'center',backgroundColor:theme.white}});
