import {api} from '../../../api';
export type OrderStatus='confirmed'|'preparing'|'ready'|'delivered'|'canceled';
export type PaymentStatus='pending'|'partial'|'paid'|'refunded';
export type DeliveryMethod='delivery'|'pickup';
export type OrderItem={id:string;productId:string;productName:string;sku:string;unit:string;quantity:number;unitPriceCents:number;unitCostCents:number;totalCents:number};
export type OrderPayment={id:string;amountCents:number;method?:string|null;notes?:string|null;paidAt:string;createdAt:string};
export type PaymentPlan='cash'|'installments';
export type Order={id:string;number:string;status:OrderStatus;paymentStatus:PaymentStatus;paymentPlan:PaymentPlan;installments:number;deliveryMethod:DeliveryMethod;notes?:string|null;totalCents:number;amountPaidCents:number;paymentDueAt?:string|null;confirmedAt:string;paidAt?:string|null;deliveredAt?:string|null;canceledAt?:string|null;createdAt:string;updatedAt:string;quote:{id:string;number:string;paymentLinkUrl?:string|null;client:{id:string;name:string;phone?:string|null;whatsapp?:string|null;email?:string|null;city?:string|null;state?:string|null}};items:OrderItem[];payments:OrderPayment[]};
export type OrderSummary={total:number;open:number;awaitingPayment:number;preparing:number;delivered:number;paidRevenueCents:number;receivableCents:number;overdueReceivableCents:number};
export const ordersApi={list:()=>api<Order[]>('/orders'),summary:()=>api<OrderSummary>('/orders/summary'),get:(id:string)=>api<Order>(`/orders/${id}`),update:(id:string,p:Partial<Pick<Order,'status'|'paymentPlan'|'installments'|'deliveryMethod'|'notes'|'paymentDueAt'>>)=>api<Order>(`/orders/${id}`,{method:'PATCH',body:JSON.stringify(p)}),addPayment:(id:string,p:{amountCents:number;method?:string;notes?:string;paidAt?:string})=>api<Order>(`/orders/${id}/payments`,{method:'POST',body:JSON.stringify(p)})};
