import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,StyleSheet,useWindowDimensions,View } from 'react-native';
import { useLocalSearchParams,router } from 'expo-router';
import { LanguageSwitch,Text,TextInput } from '../../../i18n';
import { ApiError,publicApi } from '../../../api';
import { theme } from '../../../theme';

type InviteInfo={name:string;tenantName:string;roleLabel:string;email:string;expiresAt?:string|null};
type AcceptedAccess={ok:true;email:string;name:string;tenantName:string;message?:string};
const errorMessage=(error:unknown)=>error instanceof ApiError||error instanceof Error?error.message:'Erro inesperado';

export default function AcceptInvite(){
  const {token}=useLocalSearchParams<{token:string}>();
  const wide=useWindowDimensions().width>=820;
  const[info,setInfo]=useState<InviteInfo>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[activated,setActivated]=useState<AcceptedAccess>();
  useEffect(()=>{if(!token)return;setLoading(true);publicApi<InviteInfo>(`/auth/invitations/${encodeURIComponent(String(token))}`).then(setInfo).catch((e:unknown)=>setError(errorMessage(e))).finally(()=>setLoading(false))},[token]);
  async function accept(){if(password.length<8)return setError('Use uma senha com pelo menos 8 caracteres.');if(password!==confirm)return setError('A confirmação da senha não confere.');try{setBusy(true);setError('');const result=await publicApi<AcceptedAccess>(`/auth/invitations/${encodeURIComponent(String(token))}/accept`,{method:'POST',body:JSON.stringify({password})});setActivated(result)}catch(e:unknown){setError(errorMessage(e))}finally{setBusy(false)}}
  return <View style={s.page}><View style={s.language}><LanguageSwitch compact/></View>{wide&&<View style={s.brandPanel}><View><View style={s.brandRow}><View style={s.logo}><Text style={s.logoText}>L</Text></View><Text style={s.brand}>LuviePro</Text></View><Text style={s.hero}>Seu acesso,{`\n`}do jeito certo.</Text><Text style={s.heroCopy}>Você recebeu um convite individual. Defina sua própria senha para entrar com segurança na empresa.</Text></View><Text style={s.security}>Convites têm validade limitada e só podem ser utilizados uma vez.</Text></View>}<View style={s.formPanel}><View style={s.card}>{activated?<><Text style={s.eyebrow}>PRIMEIRO ACESSO CONCLUÍDO</Text><Text style={s.title}>Acesso ativado</Text><Text style={s.subtitle}>Sua senha foi definida com sucesso para <Text style={s.strong}>{activated.tenantName}</Text>. Por segurança, faça o login com seu e-mail e a senha que acabou de criar.</Text><View style={s.info}><Text style={s.infoLabel}>E-MAIL DE ACESSO</Text><Text style={s.infoValue}>{activated.email}</Text></View><Pressable style={s.button} onPress={()=>router.replace('/')}><Text style={s.buttonText}>Ir para o login</Text></Pressable></>:loading?<View style={s.center}><ActivityIndicator color={theme.green2}/><Text style={s.loading}>Validando convite...</Text></View>:error&&!info?<><Text style={s.title}>Convite indisponível</Text><Text style={s.errorBox}>{error}</Text><Pressable style={s.secondary} onPress={()=>router.replace('/')}><Text style={s.secondaryText}>Voltar para o login</Text></Pressable></>:<><Text style={s.eyebrow}>CONVITE DE ACESSO</Text><Text style={s.title}>Olá, {info?.name}</Text><Text style={s.subtitle}>Você foi convidado para acessar <Text style={s.strong}>{info?.tenantName}</Text> como <Text style={s.strong}>{info?.roleLabel}</Text>.</Text><View style={s.info}><Text style={s.infoLabel}>E-MAIL</Text><Text style={s.infoValue}>{info?.email}</Text></View><Text style={s.label}>NOVA SENHA</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} style={s.input} placeholder="Mínimo de 8 caracteres"/><Text style={s.label}>CONFIRMAR SENHA</Text><TextInput secureTextEntry value={confirm} onChangeText={setConfirm} style={s.input} placeholder="Digite novamente"/>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={busy||password.length<8||password!==confirm} onPress={accept} style={[s.button,(busy||password.length<8||password!==confirm)&&{opacity:.5}]}>{busy?<ActivityIndicator color="white"/>:<Text style={s.buttonText}>Ativar meu acesso</Text>}</Pressable><Text style={s.expiry}>Este convite expira em {info?.expiresAt?new Date(info.expiresAt).toLocaleString('pt-BR'):'—'}.</Text></>}</View></View></View>
}
const s=StyleSheet.create({page:{flex:1,minHeight:'100%',backgroundColor:theme.g800,flexDirection:'row'},language:{position:'absolute',top:18,right:18,zIndex:20},brandPanel:{width:'42%',padding:48,justifyContent:'space-between',backgroundColor:theme.g800},brandRow:{flexDirection:'row',alignItems:'center',gap:12},logo:{width:42,height:42,borderRadius:12,backgroundColor:theme.gold,alignItems:'center',justifyContent:'center'},logoText:{fontFamily:'serif',fontSize:21,fontWeight:'900',color:theme.g900},brand:{fontFamily:'serif',fontSize:22,fontWeight:'800',color:'white'},hero:{fontFamily:'serif',fontSize:40,lineHeight:46,fontWeight:'800',color:'white',marginTop:72},heroCopy:{fontSize:15,lineHeight:23,color:'#B1CBB6',maxWidth:380,marginTop:18},security:{fontSize:12,color:'#91AD99'},formPanel:{flex:1,alignItems:'center',justifyContent:'center',padding:24,backgroundColor:theme.green2},card:{backgroundColor:'white',borderRadius:24,padding:30,maxWidth:430,width:'100%',shadowColor:'#000',shadowOpacity:.2,shadowRadius:26},center:{alignItems:'center',gap:12,paddingVertical:28},loading:{fontSize:13,color:theme.muted},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:theme.gold,marginBottom:8},title:{fontFamily:'serif',fontSize:26,fontWeight:'800',color:theme.g800},subtitle:{fontSize:13,lineHeight:20,color:theme.muted,marginTop:7,marginBottom:20},strong:{fontWeight:'800',color:theme.ink},info:{backgroundColor:theme.green50,borderRadius:10,padding:12,marginBottom:18},infoLabel:{fontSize:9,fontWeight:'900',letterSpacing:.8,color:theme.muted},infoValue:{fontSize:13,fontWeight:'700',color:theme.ink,marginTop:3},label:{fontSize:11,fontWeight:'800',letterSpacing:.7,color:theme.muted,marginBottom:6},input:{height:46,borderWidth:1,borderColor:theme.border,borderRadius:10,paddingHorizontal:12,fontSize:14,color:theme.ink,backgroundColor:'white',marginBottom:14},button:{height:46,borderRadius:10,backgroundColor:theme.green,alignItems:'center',justifyContent:'center',marginTop:4},buttonText:{color:'white',fontSize:13,fontWeight:'800'},secondary:{height:44,borderWidth:1,borderColor:theme.border,borderRadius:10,alignItems:'center',justifyContent:'center',marginTop:14},secondaryText:{fontSize:12,fontWeight:'800',color:theme.green2},error:{fontSize:12,color:theme.danger,marginBottom:10},errorBox:{fontSize:13,lineHeight:20,color:theme.danger,backgroundColor:'#FFF6F4',padding:12,borderRadius:10,marginTop:14},expiry:{fontSize:10,color:theme.muted,textAlign:'center',marginTop:12}});
