import {useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,useWindowDimensions,View} from 'react-native';
import {router,type Href} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {ApiError,api} from '../../../api';import {LanguageSwitch,Text,TextInput} from '../../../i18n';import {theme} from '../../../theme';
type ForgotPasswordResponse={devResetUrl?:string|null};
const errorMessage=(error:unknown)=>error instanceof ApiError||error instanceof Error?error.message:'Erro inesperado';

export default function ForgotPassword(){const{width}=useWindowDimensions();const compact=width<560;const[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[devUrl,setDevUrl]=useState(''),[error,setError]=useState('');async function submit(){try{setBusy(true);setError('');const result=await api<ForgotPasswordResponse>('/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});setDevUrl(result.devResetUrl??'');setDone(true)}catch(e:unknown){setError(errorMessage(e))}finally{setBusy(false)}}return <SafeAreaView style={s.page}><View style={s.language}><LanguageSwitch compact/></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[s.scroll,compact&&s.scrollCompact]}><View style={[s.card,compact&&s.cardCompact]}><Brand/><Text style={s.title}>{done?'Verifique seu e-mail':'Recuperar senha'}</Text><Text style={s.subtitle}>{done?'Se o endereço estiver cadastrado, você receberá um link válido por 60 minutos.':'Informe o e-mail usado no LuviePro para receber as instruções.'}</Text>{!done?<><Text style={s.label}>E-MAIL</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="seu@email.com" style={s.input}/>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={busy||!email.trim()} onPress={submit} style={[s.button,(busy||!email.trim())&&s.disabled]}>{busy?<ActivityIndicator color={theme.white}/>:<Text style={s.buttonText}>Enviar instruções</Text>}</Pressable></>:<>{!!devUrl&&<Pressable onPress={()=>router.push(devUrl.replace('http://localhost:8081','') as Href)} style={s.dev}><Text style={s.devTitle}>Ambiente local</Text><Text style={s.devText}>Abrir link de redefinição</Text></Pressable>}<Pressable onPress={()=>{setDone(false);setDevUrl('')}} style={s.secondary}><Text style={s.secondaryText}>Enviar novamente</Text></Pressable></>}<Pressable onPress={()=>router.replace('/')}><Text style={s.back}>Voltar para o login</Text></Pressable></View></ScrollView></SafeAreaView>}
function Brand(){return <View style={s.brand}><View style={s.logoBox}><Text style={s.logoLetter}>L</Text></View><Text style={s.logo}>LuviePro</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.g800},scroll:{flexGrow:1,alignItems:'center',justifyContent:'center',paddingHorizontal:22,paddingVertical:72},scrollCompact:{paddingHorizontal:16,paddingTop:82,paddingBottom:28},language:{position:'absolute',right:18,top:18},card:{width:'100%',maxWidth:460,backgroundColor:theme.white,borderRadius:22,padding:30,shadowColor:'#000',shadowOpacity:.2,shadowRadius:25},cardCompact:{maxWidth:'100%',borderRadius:18,padding:22},brand:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:28},logoBox:{width:38,height:38,borderRadius:11,backgroundColor:theme.gold,alignItems:'center',justifyContent:'center'},logoLetter:{fontFamily:'serif',fontSize:20,fontWeight:'900',color:theme.g900},logo:{fontFamily:'serif',fontSize:21,fontWeight:'800',color:theme.ink},title:{fontFamily:'serif',fontSize:25,fontWeight:'800',color:theme.ink},subtitle:{fontSize:13,lineHeight:19,color:theme.muted,marginTop:7,marginBottom:24},label:{fontSize:11,fontWeight:'900',letterSpacing:.7,color:theme.muted,marginBottom:7},input:{height:46,borderWidth:1,borderColor:theme.border,borderRadius:11,paddingHorizontal:12,color:theme.ink},button:{height:46,backgroundColor:theme.green,borderRadius:11,alignItems:'center',justifyContent:'center',marginTop:16},buttonText:{fontSize:13,fontWeight:'800',color:theme.white},disabled:{opacity:.5},error:{fontSize:12,color:theme.danger,marginTop:8},secondary:{height:44,borderWidth:1,borderColor:theme.border,borderRadius:10,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:12,fontWeight:'800',color:theme.green2},back:{fontSize:12,fontWeight:'800',color:theme.green2,textAlign:'center',marginTop:20},dev:{backgroundColor:theme.goldPale,borderRadius:11,padding:13,marginBottom:12},devTitle:{fontSize:11,fontWeight:'900',color:'#8A6D22'},devText:{fontSize:12,fontWeight:'800',color:theme.green2,marginTop:3}});
