import Ionicons from '@expo/vector-icons/Ionicons';
import {useCallback,useEffect,useState,type ReactNode} from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import {money,publicApi} from '../../api';
import { Text } from '../../i18n';
import { theme } from '../../theme';
import type { PlatformCompany, PlatformOverview as OverviewData, PlatformPayment, PlatformTab, PlatformUser } from './contracts';

const statusLabel=(value:string)=>({active:'Ativa',trial:'Teste',suspended:'Suspensa',cancelled:'Cancelada',replaced:'Substituída',approved:'Aprovado',pending:'Pendente',rejected:'Recusado',refunded:'Estornado',charged_back:'Contestado',error:'Erro'} as Record<string,string>)[value]??value;

type PlatformHealth={status:'ok'|'degraded';checks?:{postgres?:boolean;redis?:boolean};timestamp?:string;api?:boolean;version?:string;commit?:string;environment?:string;uptimeSeconds?:number;latencyMs?:number;checkedAt?:string};
export function PlatformOverview({data,companies,users,payments,onTab}:{data?:OverviewData;companies:PlatformCompany[];users:PlatformUser[];payments:PlatformPayment[];onTab:(tab:PlatformTab)=>void}) {
 const[health,setHealth]=useState<PlatformHealth>();const[healthLoading,setHealthLoading]=useState(true);
 const loadHealth=useCallback(async()=>{setHealthLoading(true);const started=Date.now();try{const[live,ready]=await Promise.all([publicApi<{status:'ok';version?:string;commit?:string;environment?:string;uptimeSeconds?:number}>('/health/live'),publicApi<PlatformHealth>('/health')]);setHealth({...ready,api:live.status==='ok',version:live.version,commit:live.commit,environment:live.environment,uptimeSeconds:live.uptimeSeconds,latencyMs:Date.now()-started,checkedAt:new Date().toISOString()})}catch{try{const live=await publicApi<{status:'ok';version?:string;commit?:string;environment?:string;uptimeSeconds?:number}>('/health/live');setHealth({status:'degraded',api:true,version:live.version,commit:live.commit,environment:live.environment,uptimeSeconds:live.uptimeSeconds,latencyMs:Date.now()-started,checkedAt:new Date().toISOString()})}catch{setHealth({status:'degraded',api:false,latencyMs:Date.now()-started,checkedAt:new Date().toISOString()})}}finally{setHealthLoading(false)}},[]);
 useEffect(()=>{void loadHealth()},[loadHealth]);
 const metrics=[
  ['business-outline','Empresas',data?.tenants??0,`${data?.activeTenants??0} ativas`],
  ['people-outline','Usuários',data?.users??0,'acessos ativos'],
  ['person-add-outline','Clientes',data?.clients??0,'na plataforma'],
  ['cash-outline','Receita mensal',money(data?.monthlyRevenueCents??0),'receita recorrente'],
  ['checkmark-done-outline','Pagamentos',payments.filter(payment=>payment.status==='approved').length,'confirmados'],
 ] as const;
 return <><View style={styles.metrics}>{metrics.map(([icon,label,value,subtitle])=><View key={label} style={styles.metric}><View style={styles.metricHead}><Icon name={icon}/><Text style={styles.muted}>{label}</Text></View><Text style={styles.metricValue}>{String(value)}</Text><Text style={styles.small}>{subtitle}</Text></View>)}</View><View style={styles.grid}><Panel title="Empresas recentes" action={()=>onTab('companies')}>{companies.slice(0,5).map(company=><SimpleRow key={company.id} icon="business-outline" title={company.name} sub={`${company.plan.toUpperCase()} · ${company._count?.users??0} usuário(s)`} badge={statusLabel(company.status)}/>)}</Panel><Panel title="Usuários recentes" action={()=>onTab('users')}>{users.slice(0,5).map(user=><SimpleRow key={user.id} icon="person-outline" title={user.name} sub={`${user.email} · ${user.tenant?.name??'Sem empresa'}`} badge={user.active?'Ativo':'Inativo'}/>)}</Panel><Panel title="Pagamentos recentes" action={()=>onTab('payments')}>{payments.length?payments.slice(0,5).map(payment=><SimpleRow key={payment.id} icon="card-outline" title={payment.tenant?.name??'Sem empresa'} sub={`${payment.plan.toUpperCase()} · ${money(payment.amountCents)}`} badge={statusLabel(payment.status)}/>):<Empty title="Nenhum pagamento registrado"/>}</Panel><Panel title="Saúde da plataforma"><View style={styles.health}><Icon name={health?.status==='ok'?'shield-checkmark-outline':'warning-outline'} large/><View style={styles.fill}><Text style={styles.strong}>{healthLoading?'Verificando ambiente…':health?.status==='ok'?'Ambiente saudável':'Atenção na infraestrutura'}</Text><Text style={styles.small}>{healthLoading?'Consultando API, PostgreSQL e Redis':health?.status==='ok'?'API, PostgreSQL e Redis operacionais':'Uma ou mais dependências não responderam ao health check'}</Text></View><Pressable onPress={()=>void loadHealth()} style={styles.refresh}><Ionicons name="refresh-outline" size={16} color={theme.green2}/></Pressable></View><SimpleRow icon="cloud-outline" title="API" sub={healthLoading?'Consultando serviço':health?.version?`v${health.version} · ${health.environment??'ambiente'}${health.latencyMs!=null?` · ${health.latencyMs} ms`:''}`:'Serviço principal'} badge={healthLoading?'Verificando':health?.api?'Online':'Atenção'}/><SimpleRow icon="server-outline" title="PostgreSQL" sub="Banco de dados principal" badge={healthLoading?'Verificando':health?.checks?.postgres?'Online':health?.status==='ok'?'Online':'Atenção'}/><SimpleRow icon="flash-outline" title="Redis" sub="Cache e serviços auxiliares" badge={healthLoading?'Verificando':health?.checks?.redis?'Online':health?.status==='ok'?'Online':'Atenção'}/>{health?.checkedAt?<Text style={styles.healthMeta}>Última verificação: {new Date(health.checkedAt).toLocaleString('pt-BR')}{health.commit&&health.commit!=='unknown'?` · commit ${health.commit.slice(0,8)}`:''}{health.uptimeSeconds!=null?` · uptime ${Math.floor(health.uptimeSeconds/60)} min`:''}</Text>:null}</Panel></View></>;
}

function Panel({title,action,children}:{title:string;action?:()=>void;children:ReactNode}){return <View style={styles.panel}><View style={styles.panelHead}><Text style={styles.panelTitle}>{title}</Text>{action?<Pressable onPress={action}><Text style={styles.link}>Gerenciar →</Text></Pressable>:null}</View>{children}</View>}
function SimpleRow({icon,title,sub,badge}:{icon:string;title:string;sub:string;badge:string}){return <View style={styles.simpleRow}><Icon name={icon}/><View style={styles.fill}><Text style={styles.strong}>{title}</Text><Text style={styles.small}>{sub}</Text></View><Badge label={badge}/></View>}
function Empty({title}:{title:string}){return <View style={styles.empty}><Ionicons name="wallet-outline" size={27} color={theme.gold}/><Text style={styles.panelTitle}>{title}</Text></View>}
function Badge({label}:{label:string}){const danger=['Inativo','Suspensa','Cancelada','Recusado','Erro'].includes(label),warning=['Pendente','Teste','Verificando','Atenção'].includes(label);return <View style={[styles.badge,danger&&styles.badgeDanger,warning&&styles.badgeWarning]}><Text style={[styles.badgeText,danger&&styles.badgeTextDanger]}>{label}</Text></View>}
function Icon({name,large=false}:{name:string;large?:boolean}){return <View style={[styles.icon,large&&styles.iconLarge]}><Ionicons name={name as never} size={large?24:18} color={theme.green2}/></View>}

const styles=StyleSheet.create({metrics:{flexDirection:'row',flexWrap:'wrap',gap:12,marginBottom:18},metric:{flex:1,minWidth:180,backgroundColor:'#fff',borderWidth:1,borderColor:theme.border,borderRadius:14,padding:16},metricHead:{flexDirection:'row',alignItems:'center',gap:9},metricValue:{fontFamily:'serif',fontSize:25,fontWeight:'800',color:theme.ink,marginTop:12},muted:{fontSize:12,color:theme.muted,marginTop:4},small:{fontSize:9.5,color:theme.muted,marginTop:3},strong:{fontSize:11,fontWeight:'800',color:theme.ink},grid:{flexDirection:'row',flexWrap:'wrap',gap:16},panel:{flex:1,minWidth:300,backgroundColor:'#fff',borderWidth:1,borderColor:theme.border,borderRadius:14,padding:18},panelHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingBottom:8},panelTitle:{fontFamily:'serif',fontSize:17,fontWeight:'800',color:theme.ink},link:{fontSize:10,fontWeight:'800',color:theme.green2},simpleRow:{minHeight:58,borderTopWidth:1,borderTopColor:theme.border,flexDirection:'row',alignItems:'center',gap:10},health:{flexDirection:'row',alignItems:'center',gap:11,paddingVertical:15},refresh:{width:34,height:34,borderRadius:17,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},fill:{flex:1},icon:{width:36,height:36,borderRadius:10,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},iconLarge:{width:48,height:48,borderRadius:14},badge:{alignSelf:'flex-start',borderRadius:20,paddingHorizontal:9,paddingVertical:5,backgroundColor:'#E7F6EC'},badgeWarning:{backgroundColor:'#FFF4D8'},badgeDanger:{backgroundColor:'#FBEAEA'},badgeText:{fontSize:9,fontWeight:'800',color:'#2F7450'},badgeTextDanger:{color:'#963737'},empty:{alignItems:'center',gap:8,paddingVertical:15},healthMeta:{fontSize:9.5,color:theme.muted,marginTop:10,paddingTop:10,borderTopWidth:1,borderTopColor:theme.border}});
