import Ionicons from '@expo/vector-icons/Ionicons';
import { Pressable, ScrollView,StyleSheet,View } from 'react-native';
import { Text } from '../../i18n';
import { theme } from '../../theme';
import type { PlatformTab } from './contracts';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export const PLATFORM_TABS=[
 {key:'overview',icon:'speedometer-outline',label:'Visão geral',subtitle:'Indicadores e saúde geral da operação'},
 {key:'companies',icon:'business-outline',label:'Empresas',subtitle:'Contas, planos e situação das empresas'},
 {key:'users',icon:'people-outline',label:'Usuários',subtitle:'Acessos e perfis de todos os clientes'},
 {key:'plans',icon:'layers-outline',label:'Planos',subtitle:'Preços e limites comerciais'},
 {key:'subs',icon:'repeat-outline',label:'Assinaturas',subtitle:'Ciclos contratados e vencimentos'},
 {key:'payments',icon:'card-outline',label:'Pagamentos',subtitle:'Conciliação financeira do Mercado Pago'},
] as const satisfies ReadonlyArray<{key:PlatformTab;icon:string;label:string;subtitle:string}>;

export function PlatformSidebar({compact,active,onSelect,onLogout}:{compact:boolean;active:PlatformTab;onSelect:(tab:PlatformTab)=>void;onLogout:()=>void|Promise<void>}) {
 const insets=useSafeAreaInsets();
 if(compact)return <View style={[styles.bottomBar,{paddingBottom:Math.max(6,insets.bottom)}]}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.bottomContent}>{PLATFORM_TABS.map(item=><Pressable accessibilityRole="button" accessibilityLabel={item.label} accessibilityState={{selected:active===item.key}} key={item.key} onPress={()=>onSelect(item.key)} style={[styles.bottomItem,active===item.key&&styles.bottomItemOn]}><Ionicons name={item.icon as never} size={20} color={active===item.key?theme.green2:theme.muted}/><Text numberOfLines={1} style={[styles.bottomText,active===item.key&&styles.bottomTextOn]}>{item.label}</Text></Pressable>)}</ScrollView></View>;
 return <View style={styles.side}><View style={styles.logo}><View style={styles.logoMark}><Text style={styles.logoLetter}>L</Text></View><View><Text style={styles.brand}>LuviePro</Text><Text style={styles.brandSub}>ADMINISTRAÇÃO SAAS</Text></View></View><Text style={styles.menuLabel}>PLATAFORMA</Text>{PLATFORM_TABS.map(item=><Pressable accessibilityRole="button" accessibilityState={{selected:active===item.key}} key={item.key} onPress={()=>onSelect(item.key)} style={[styles.nav,active===item.key&&styles.navOn]}><Ionicons name={item.icon as never} size={20} color={active===item.key?theme.gold:'#b9c8c0'}/><Text style={[styles.navText,active===item.key&&styles.navTextOn]}>{item.label}</Text></Pressable>)}<View style={styles.fill}/><View style={styles.onlineRow}><View style={styles.online}/><Text style={styles.onlineText}>Sistemas operacionais</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Sair da plataforma" onPress={onLogout} style={styles.nav}><Ionicons name="log-out-outline" size={20} color="#b9c8c0"/><Text style={styles.navText}>Sair</Text></Pressable></View>;
}

const styles=StyleSheet.create({bottomBar:{position:'absolute',left:0,right:0,bottom:0,zIndex:30,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:theme.border,shadowColor:'#000',shadowOpacity:.08,shadowRadius:14,shadowOffset:{width:0,height:-4},elevation:18},bottomContent:{minWidth:'100%',paddingHorizontal:6,paddingTop:6},bottomItem:{minWidth:72,minHeight:52,paddingHorizontal:7,borderRadius:10,alignItems:'center',justifyContent:'center',gap:3},bottomItemOn:{backgroundColor:theme.green50},bottomText:{maxWidth:82,fontSize:9,fontWeight:'700',color:theme.muted},bottomTextOn:{color:theme.green2,fontWeight:'900'},side:{width:250,backgroundColor:'#112F24',padding:18},sideSmall:{width:72,paddingHorizontal:10},logo:{height:70,flexDirection:'row',alignItems:'center',gap:11},logoMark:{width:40,height:40,borderRadius:11,backgroundColor:theme.gold,alignItems:'center',justifyContent:'center'},logoLetter:{fontFamily:'serif',fontSize:25,fontWeight:'900',color:'#112F24'},brand:{fontFamily:'serif',fontSize:19,fontWeight:'800',color:'#fff'},brandSub:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:'#86A397'},menuLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:'#708B7F',marginVertical:14},nav:{height:46,borderRadius:10,flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:13,marginBottom:4},navOn:{backgroundColor:'rgba(255,255,255,.11)'},navText:{fontSize:12,fontWeight:'700',color:'#B9C8C0'},navTextOn:{color:'#fff'},fill:{flex:1},onlineRow:{flexDirection:'row',alignItems:'center',gap:8,padding:13,borderTopWidth:1,borderTopColor:'rgba(255,255,255,.1)'},online:{width:7,height:7,borderRadius:7,backgroundColor:'#63D38C'},onlineText:{fontSize:10,color:'#B9C8C0'}});
