import {useEffect,useState} from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import {Pressable,StyleSheet,View} from 'react-native';
import {api} from '../../api';
import {AsyncState} from '../../components/AsyncState';
import {AsyncButton} from '../../components/AsyncButton';
import {Text} from '../../i18n';
import {theme} from '../../theme';
import {useFeedback} from '../../components/Feedback';

type MailStatus={provider:'smtp'|'resend';configured:boolean;from:string|null;host:string|null;port:number|null;secure:boolean|null;userConfigured:boolean;passwordConfigured:boolean;resendApiKeyConfigured:boolean};
type Verification={ok:boolean;reason?:string;validation?:'configuration'|'connection'};

export function PlatformEmailSettings(){
 const[data,setData]=useState<MailStatus>(),[verification,setVerification]=useState<Verification>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[verifying,setVerifying]=useState(false),[sending,setSending]=useState(false);const{notify}=useFeedback();
 const load=()=>{setLoading(true);setError('');api<MailStatus>('/platform/mail/status').then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:'Não foi possível consultar a configuração global de e-mail')).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const isResend=data?.provider==='resend';
 function help(){if(isResend)return 'Confira RESEND_API_KEY e RESEND_FROM. O remetente precisa ser aceito pelo Resend; para enviar a qualquer destinatário, use um domínio verificado.';return data?.host?.toLowerCase().includes('gmail')?'No Gmail, ative a verificação em duas etapas e use uma senha de app em SMTP_PASS.':'Confira servidor, porta, segurança, usuário e senha SMTP.'}
 async function verify(){try{setVerifying(true);const result=await api<Verification>('/platform/mail/verify',{method:'POST'});setVerification(result);notify({tone:result.ok?'success':'error',title:result.ok?(isResend?'Configuração Resend válida':'Conexão SMTP validada'):'Falha na configuração de e-mail',message:result.ok?(isResend?'A API Key e o remetente estão configurados. Use o envio de teste para validar a entrega.':'O servidor SMTP aceitou a autenticação.'):help()})}catch(e:unknown){notify({tone:'error',title:'Não foi possível validar o e-mail',message:e instanceof Error?e.message:'Erro inesperado'})}finally{setVerifying(false)}}
 async function test(){try{setSending(true);const result=await api<{sent:boolean;reason?:string}>('/platform/mail/test',{method:'POST'});notify({tone:result.sent?'success':'error',title:result.sent?'E-mail de teste enviado':'Falha no envio',message:result.sent?'Confira a caixa de entrada do administrador da plataforma.':result.reason==='not_configured'?'Configure as variáveis do provedor de e-mail no backend.':help()})}catch(e:unknown){notify({tone:'error',title:'Não foi possível testar o e-mail',message:e instanceof Error?e.message:'Erro inesperado'})}finally{setSending(false)}}
 if(loading||error)return <AsyncState loading={loading} error={error} onRetry={load}/>;
 if(!data)return <AsyncState loading={false} onRetry={load}/>;
 return <View style={s.wrap}>
   <View style={s.info}><Ionicons name="shield-checkmark-outline" size={22} color={theme.green2}/><View style={{flex:1}}><Text style={s.infoTitle}>Configuração global de e-mail</Text><Text style={s.muted}>Este provedor é utilizado por todas as empresas para primeiro acesso, recuperação de senha e notificações.</Text></View></View>
   <View style={[s.banner,verification?.ok&&s.ok]}><Ionicons name={verification?.ok?'checkmark-circle-outline':'alert-circle-outline'} size={22} color={verification?.ok?theme.green2:theme.gold}/><View style={{flex:1}}><Text style={s.bannerTitle}>{verification?.ok?'Provedor de e-mail configurado':data.configured?'E-mail configurado; envio ainda não testado':'E-mail global não configurado'}</Text><Text style={s.muted}>{verification?.ok?(isResend?'Resend selecionado. O envio de teste confirma a API Key, remetente e entrega.':'O backend autenticou com sucesso no servidor SMTP.'):'Use “Validar configuração” e depois envie um e-mail de teste.'}</Text></View><Pressable onPress={load}><Ionicons name="refresh-outline" size={20} color={theme.green2}/></Pressable></View>
   <View style={s.card}><Row label="Provedor" value={isResend?'Resend (HTTPS)':'SMTP'}/><Row label="Remetente" value={data.from??'Não configurado'}/>{isResend?<Row label="API Key Resend" value={data.resendApiKeyConfigured?'Configurada':'Não configurada'}/>:<><Row label="Servidor" value={data.host??'Não configurado'}/><Row label="Porta" value={data.port===null?'—':String(data.port)}/><Row label="Segurança" value={data.secure?'SSL/TLS':'STARTTLS / sem SSL direto'}/><Row label="Usuário SMTP" value={data.userConfigured?'Configurado':'Não configurado'}/><Row label="Senha SMTP" value={data.passwordConfigured?'Configurada':'Não configurada'}/></>}</View>
   <View style={s.help}><Text style={s.helpTitle}>Variáveis globais do backend</Text><Text style={s.code}>{isResend?`MAIL_PROVIDER=resend\nRESEND_API_KEY\nRESEND_FROM`:`MAIL_PROVIDER=smtp\nSMTP_HOST\nSMTP_PORT\nSMTP_SECURE\nSMTP_USER\nSMTP_PASS\nSMTP_FROM`}</Text><Text style={s.muted}>{isResend?'No Render Free, o LuviePro usa a API HTTPS do Resend e não depende das portas SMTP 465/587.':'SMTP continua disponível para desenvolvimento local ou ambientes sem bloqueio de porta.'}</Text></View>
   <View style={s.actions}><AsyncButton busy={verifying} disabled={sending} label="Validar configuração" onPress={verify}/><AsyncButton busy={sending} disabled={verifying} label="Enviar e-mail de teste para o administrador" onPress={test}/></View>
 </View>;
}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({wrap:{maxWidth:860,width:'100%'},info:{backgroundColor:theme.green50,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:16,flexDirection:'row',gap:11,alignItems:'flex-start',marginBottom:14},infoTitle:{fontSize:13,fontWeight:'900',color:theme.ink},banner:{borderWidth:1,borderColor:theme.goldLight,backgroundColor:theme.goldPale,borderRadius:13,padding:14,flexDirection:'row',gap:10,alignItems:'center',marginBottom:14},ok:{backgroundColor:theme.green50,borderColor:theme.border},bannerTitle:{fontSize:13,fontWeight:'900',color:theme.ink},muted:{fontSize:11,lineHeight:17,color:theme.muted,marginTop:3},card:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,overflow:'hidden',marginBottom:14},row:{padding:13,borderBottomWidth:1,borderBottomColor:theme.border,flexDirection:'row',justifyContent:'space-between',gap:16},label:{fontSize:11,fontWeight:'800',color:theme.muted},value:{fontSize:12,fontWeight:'800',color:theme.ink,textAlign:'right',flex:1},help:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:15,marginBottom:14},helpTitle:{fontSize:13,fontWeight:'900',color:theme.ink},code:{fontFamily:'monospace',fontSize:12,lineHeight:19,color:theme.green2,marginVertical:10},actions:{alignSelf:'flex-start',minWidth:300,gap:8}});
