import {useEffect,useState} from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import {Pressable,StyleSheet,View} from 'react-native';
import {api} from '../../api';
import {AsyncState} from '../../components/AsyncState';
import {AsyncButton} from '../../components/AsyncButton';
import {Text} from '../../i18n';
import {theme} from '../../theme';
import {useFeedback} from '../../components/Feedback';

type SmtpStatus={configured:boolean;host:string|null;port:number;secure:boolean;from:string|null;userConfigured:boolean;passwordConfigured:boolean};
type Verification={ok:boolean;reason?:string};

export function PlatformEmailSettings(){
 const[data,setData]=useState<SmtpStatus>(),[verification,setVerification]=useState<Verification>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[verifying,setVerifying]=useState(false),[sending,setSending]=useState(false);const{notify}=useFeedback();
 const load=()=>{setLoading(true);setError('');api<SmtpStatus>('/platform/mail/status').then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:'Não foi possível consultar o SMTP global')).finally(()=>setLoading(false))};
 useEffect(load,[]);
 function gmailHelp(){return data?.host?.toLowerCase().includes('gmail')?'No Gmail, ative a verificação em duas etapas e use uma senha de app de 16 caracteres em SMTP_PASS. Não use a senha normal da conta.':'Confira servidor, porta, segurança, usuário e senha SMTP.'}
 async function verify(){try{setVerifying(true);const result=await api<Verification>('/platform/mail/verify',{method:'POST'});setVerification(result);notify({tone:result.ok?'success':'error',title:result.ok?'Conexão SMTP validada':'Falha na conexão SMTP',message:result.ok?'O servidor SMTP aceitou a autenticação.':gmailHelp()})}catch(e:unknown){notify({tone:'error',title:'Não foi possível validar o SMTP',message:e instanceof Error?e.message:'Erro inesperado'})}finally{setVerifying(false)}}
 async function test(){try{setSending(true);const result=await api<{sent:boolean;reason?:string}>('/platform/mail/test',{method:'POST'});notify({tone:result.sent?'success':'error',title:result.sent?'E-mail de teste enviado':'Falha no envio',message:result.sent?'Confira a caixa de entrada do administrador da plataforma.':result.reason==='not_configured'?'Configure as variáveis SMTP no backend.':gmailHelp()})}catch(e:unknown){notify({tone:'error',title:'Não foi possível testar o SMTP',message:e instanceof Error?e.message:'Erro inesperado'})}finally{setSending(false)}}
 if(loading||error)return <AsyncState loading={loading} error={error} onRetry={load}/>;
 if(!data)return <AsyncState loading={false} onRetry={load}/>;
 return <View style={s.wrap}>
   <View style={s.info}><Ionicons name="shield-checkmark-outline" size={22} color={theme.green2}/><View style={{flex:1}}><Text style={s.infoTitle}>Configuração global da plataforma</Text><Text style={s.muted}>Este SMTP é utilizado por todas as empresas para primeiro acesso, recuperação de senha e notificações. Empresas e usuários não possuem credenciais SMTP próprias.</Text></View></View>
   <View style={[s.banner,verification?.ok&&s.ok]}><Ionicons name={verification?.ok?'checkmark-circle-outline':'alert-circle-outline'} size={22} color={verification?.ok?theme.green2:theme.gold}/><View style={{flex:1}}><Text style={s.bannerTitle}>{verification?.ok?'SMTP global conectado':data.configured?'SMTP configurado; conexão ainda não validada':'SMTP global não configurado'}</Text><Text style={s.muted}>{verification?.ok?'O backend autenticou com sucesso no servidor de e-mail.':verification?.reason?gmailHelp():'Use “Validar conexão” para testar o servidor sem enviar mensagem.'}</Text></View><Pressable onPress={load}><Ionicons name="refresh-outline" size={20} color={theme.green2}/></Pressable></View>
   <View style={s.card}><Row label="Servidor" value={data.host??'Não configurado'}/><Row label="Porta" value={String(data.port)}/><Row label="Segurança" value={data.secure?'SSL/TLS':'STARTTLS / sem SSL direto'}/><Row label="Remetente" value={data.from??'Não configurado'}/><Row label="Usuário SMTP" value={data.userConfigured?'Configurado':'Não configurado'}/><Row label="Senha SMTP" value={data.passwordConfigured?'Configurada':'Não configurada'}/></View>
   <View style={s.help}><Text style={s.helpTitle}>Variáveis globais do backend</Text><Text style={s.code}>SMTP_HOST{`\n`}SMTP_PORT{`\n`}SMTP_SECURE{`\n`}SMTP_USER{`\n`}SMTP_PASS{`\n`}SMTP_FROM</Text><Text style={s.muted}>As credenciais ficam somente no ambiente do backend/Render. A senha SMTP nunca é retornada pela API nem exibida no painel.</Text>{data.host?.toLowerCase().includes('gmail')?<Text style={s.gmail}>Gmail: use smtp.gmail.com, porta 587, SMTP_SECURE=false e uma senha de app de 16 caracteres.</Text>:null}</View>
   <View style={s.actions}><AsyncButton busy={verifying} disabled={sending} label="Validar conexão SMTP" onPress={verify}/><AsyncButton busy={sending} disabled={verifying} label="Enviar e-mail de teste para o administrador" onPress={test}/></View>
 </View>;
}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({wrap:{maxWidth:860,width:'100%'},info:{backgroundColor:theme.green50,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:16,flexDirection:'row',gap:11,alignItems:'flex-start',marginBottom:14},infoTitle:{fontSize:13,fontWeight:'900',color:theme.ink},banner:{borderWidth:1,borderColor:theme.goldLight,backgroundColor:theme.goldPale,borderRadius:13,padding:14,flexDirection:'row',gap:10,alignItems:'center',marginBottom:14},ok:{backgroundColor:theme.green50,borderColor:theme.border},bannerTitle:{fontSize:13,fontWeight:'900',color:theme.ink},muted:{fontSize:11,lineHeight:17,color:theme.muted,marginTop:3},gmail:{fontSize:11,lineHeight:17,color:theme.green2,fontWeight:'800',marginTop:10},card:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,overflow:'hidden',marginBottom:14},row:{padding:13,borderBottomWidth:1,borderBottomColor:theme.border,flexDirection:'row',justifyContent:'space-between',gap:16},label:{fontSize:11,fontWeight:'800',color:theme.muted},value:{fontSize:12,fontWeight:'800',color:theme.ink,textAlign:'right',flex:1},help:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:14,padding:15,marginBottom:14},helpTitle:{fontSize:13,fontWeight:'900',color:theme.ink},code:{fontFamily:'monospace',fontSize:12,lineHeight:19,color:theme.green2,marginVertical:10},actions:{alignSelf:'flex-start',minWidth:300,gap:8}});

