import { useState } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Image,Platform,Pressable,View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Text } from '../../../i18n';
import { api,apiForm } from '../../../api';
import { feedbackAlert as Alert,useFeedback } from '../../../components/Feedback';
import { theme } from '../../../theme';
import type { TenantSettings } from '../settings.types';
import { errorMessage } from '../settings.utils';
import { s } from '../settings.styles';

export function LogoUpload({value,enabled,onChanged}:{value?:string;enabled:boolean;onChanged:(value:string|null)=>void}){const[busy,setBusy]=useState(false);const{confirm}=useFeedback();async function pick(){try{if(Platform.OS!=='web'){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert('Permissão necessária','Autorize o acesso às fotos para selecionar o logo.')}const result=await ImagePicker.launchImageLibraryAsync({allowsEditing:true,quality:.9});if(result.canceled)return;const asset=result.assets[0];const form=new FormData();const file=asset.file??({uri:asset.uri,name:asset.fileName||'logo.jpg',type:asset.mimeType||'image/jpeg'} as unknown as Blob);form.append('file',file);setBusy(true);const tenant=await apiForm<TenantSettings>('/account/logo',form);onChanged(tenant.logoUrl??null);Alert.alert('Logo atualizado','A nova imagem será usada nas próximas propostas e PDFs.')}catch(e:unknown){Alert.alert('Não foi possível enviar o logo',errorMessage(e))}finally{setBusy(false)}}async function remove(){if(!(await confirm({title:'Remover logo?',message:'A proposta voltará a usar apenas o nome da empresa até que um novo logo seja enviado.',confirmLabel:'Remover logo',danger:true})))return;try{setBusy(true);const tenant=await api<TenantSettings>('/account/logo/remove',{method:'POST'});onChanged(tenant.logoUrl??null);Alert.alert('Logo removido')}catch(e:unknown){Alert.alert('Não foi possível remover o logo',errorMessage(e))}finally{setBusy(false)}}return <View style={s.logoCard}><View style={s.logoPreview}>{value?<Image source={{uri:value}} style={s.logoImage} resizeMode="contain"/>:<View style={s.logoEmpty}><Ionicons name="image-outline" size={28} color={theme.muted}/><Text style={s.logoEmptyText}>Nenhum logo enviado</Text></View>}</View><View style={s.logoInfo}><Text style={s.logoTitle}>Logo da empresa</Text><Text style={s.logoHelp}>PNG, JPG ou WebP · máximo 2 MB. Prefira fundo transparente e formato horizontal.</Text><View style={s.logoActions}><Pressable disabled={!enabled||busy} onPress={pick} style={[s.smallButton,(!enabled||busy)&&{opacity:.45}]}><Ionicons name="cloud-upload-outline" size={15} color={theme.green2}/><Text style={s.smallButtonText}>{busy?'Enviando...':value?'Trocar logo':'Enviar logo'}</Text></Pressable>{value?<Pressable disabled={busy} onPress={remove} style={[s.smallButton,busy&&{opacity:.45}]}><Ionicons name="trash-outline" size={14} color={theme.danger}/><Text style={[s.smallButtonText,{color:theme.danger}]}>Remover</Text></Pressable>:null}</View></View></View>}
