import {useCallback,useState} from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import {Pressable,StyleSheet,View} from 'react-native';
import {useFocusEffect} from 'expo-router';
import {ApiError,api} from '../../../api';
import {Text} from '../../../i18n';
import {FormField} from '../../../components/FormField';
import {theme} from '../../../theme';
import {AppShell} from '../../../components/AppShell';
import {AsyncState} from '../../../components/AsyncState';
import {FormModal} from '../../../components/FormModal';
import {HeaderAction} from '../../../components/HeaderAction';
import {useFeedback} from '../../../components/Feedback';

type ProjectStatus={id:string;name:string;color:string;active:boolean;position:number;_count?:{projects?:number}};
const errorMessage=(error:unknown)=>error instanceof ApiError||error instanceof Error?error.message:'Erro inesperado';
export default function ProjectStatusesScreen(){
  const{notify,confirm}=useFeedback();const[list,setList]=useState<ProjectStatus[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[editing,setEditing]=useState<ProjectStatus|null>(null),[name,setName]=useState(''),[color,setColor]=useState('#2F6B4F'),[busy,setBusy]=useState(false),[nameError,setNameError]=useState('');
  const load=useCallback(()=>{setLoading(true);api<ProjectStatus[]>('/project-statuses').then(setList).catch((e:unknown)=>notify({tone:'error',title:'Erro ao carregar status',message:errorMessage(e)})).finally(()=>setLoading(false))},[notify]);useFocusEffect(load);
  const start=(item?:ProjectStatus)=>{setNameError('');setEditing(item??null);setName(item?.name??'');setColor(item?.color??'#2F6B4F');setOpen(true)};
  async function save(){if(name.trim().length<2){setNameError('Informe um nome com pelo menos 2 caracteres.');return}setNameError('');try{setBusy(true);await api(editing?`/project-statuses/${editing.id}`:'/project-statuses',{method:editing?'PATCH':'POST',body:JSON.stringify({name:name.trim(),color})});setOpen(false);load();notify({tone:'success',title:'Status salvo',message:'O Kanban foi atualizado.'})}catch(e:unknown){notify({tone:'error',title:'Não foi possível salvar',message:errorMessage(e)})}finally{setBusy(false)}}
  async function toggle(item:ProjectStatus){try{await api(`/project-statuses/${item.id}`,{method:'PATCH',body:JSON.stringify({active:!item.active})});load()}catch(e:unknown){notify({tone:'error',title:'Não foi possível alterar',message:errorMessage(e)})}}
  async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=list.length)return;const current=list[index],other=list[target];const optimistic=[...list];optimistic[index]=other;optimistic[target]=current;setList(optimistic);try{await Promise.all([api(`/project-statuses/${current.id}`,{method:'PATCH',body:JSON.stringify({position:other.position})}),api(`/project-statuses/${other.id}`,{method:'PATCH',body:JSON.stringify({position:current.position})})]);load()}catch(e:unknown){setList(list);notify({tone:'error',title:'Não foi possível reordenar',message:errorMessage(e)})}}
  async function remove(item:ProjectStatus){if(!(await confirm({title:'Excluir status?',message:'A exclusão só será permitida se não houver projetos neste status.',confirmLabel:'Excluir',danger:true})))return;try{await api(`/project-statuses/${item.id}`,{method:'DELETE'});load()}catch(e:unknown){notify({tone:'error',title:'Não foi possível excluir',message:errorMessage(e)})}}
  return <AppShell title="Status dos projetos" subtitle="Configure as colunas exibidas no Kanban." action={<HeaderAction label="Novo status" icon="add-circle-outline" onPress={()=>start()}/>}>
    {loading?<AsyncState loading/>:<View style={s.list}>{list.map((item,index)=><View key={item.id} style={[s.row,!item.active&&s.inactive]}><View style={s.order}><Pressable disabled={index===0} accessibilityLabel="Mover para cima" onPress={()=>move(index,-1)} style={[s.orderButton,index===0&&s.disabled]}><Ionicons name="chevron-up" size={16} color={theme.green2}/></Pressable><Pressable disabled={index===list.length-1} accessibilityLabel="Mover para baixo" onPress={()=>move(index,1)} style={[s.orderButton,index===list.length-1&&s.disabled]}><Ionicons name="chevron-down" size={16} color={theme.green2}/></Pressable></View><View style={[s.color,{backgroundColor:item.color}]}/><View style={s.info}><Text style={s.name}>{item.name}</Text><Text style={s.meta}>Coluna {index+1} · {item.active?'Ativo':'Desativado'}</Text></View><Pressable accessibilityLabel="Editar status" onPress={()=>start(item)} style={s.icon}><Ionicons name="pencil-outline" size={18} color={theme.green2}/></Pressable><Pressable accessibilityLabel={item.active?'Desativar status':'Ativar status'} onPress={()=>toggle(item)} style={s.icon}><Ionicons name={item.active?'pause-circle-outline':'play-circle-outline'} size={19} color={theme.gold}/></Pressable><Pressable accessibilityLabel="Excluir status" onPress={()=>remove(item)} style={s.icon}><Ionicons name="trash-outline" size={18} color={theme.danger}/></Pressable></View>)}</View>}
    <FormModal visible={open} title={editing?'Editar status':'Novo status'} subtitle="Defina o nome e a cor da coluna." onClose={()=>setOpen(false)} footer={<><Pressable onPress={()=>setOpen(false)} style={s.cancel}><Text style={s.cancelText}>Cancelar</Text></Pressable><Pressable disabled={busy} onPress={save} style={[s.submit,busy&&{opacity:.55}]}><Text style={s.submitText}>{busy?'Salvando...':'Salvar status'}</Text></Pressable></>}><FormField label="Nome do status" required error={nameError} value={name} onChangeText={v=>{setName(v);setNameError('')}} placeholder="Ex.: Aguardando cliente"/><Text style={s.label}>COR</Text><Text style={s.colorHelp}>Escolha uma cor para identificar este status no Kanban.</Text><View style={s.colors}>{['#C9A84C','#D97706','#E67E22','#A04A45','#C2415D','#8A5B6B','#7C3AED','#5B5BD6','#3D6F91','#0E7490','#0F766E','#2F6B4F','#6F8C78','#4D7C0F','#64748B','#374151'].map(value=><Pressable accessibilityLabel={`Selecionar cor ${value}`} key={value} onPress={()=>setColor(value)} style={[s.swatch,{backgroundColor:value},color===value&&s.swatchOn]}><Ionicons name="checkmark" size={15} color={color===value?theme.white:'transparent'}/></Pressable>)}</View></FormModal>
  </AppShell>;
}
const s=StyleSheet.create({list:{gap:10,maxWidth:820},row:{backgroundColor:theme.white,borderWidth:1,borderColor:theme.border,borderRadius:13,padding:14,flexDirection:'row',alignItems:'center',gap:11},inactive:{opacity:.55},order:{gap:2},orderButton:{width:28,height:22,borderRadius:6,backgroundColor:theme.green50,alignItems:'center',justifyContent:'center'},disabled:{opacity:.25},color:{width:12,height:42,borderRadius:6},info:{flex:1},name:{fontSize:14,fontWeight:'800',color:theme.ink},meta:{fontSize:11,color:theme.muted,marginTop:4},icon:{width:36,height:36,borderRadius:9,backgroundColor:theme.cream,alignItems:'center',justifyContent:'center'},label:{fontSize:11,fontWeight:'800',letterSpacing:.6,color:theme.muted,marginBottom:6},colorHelp:{fontSize:11,color:theme.muted,marginBottom:10},input:{borderWidth:1,borderColor:theme.border,borderRadius:10,paddingHorizontal:12,paddingVertical:11,color:theme.ink,marginBottom:16},colors:{flexDirection:'row',gap:10,flexWrap:'wrap'},swatch:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'},swatchOn:{borderWidth:3,borderColor:theme.ink},cancel:{borderWidth:1,borderColor:theme.border,borderRadius:9,paddingHorizontal:15,paddingVertical:10},cancelText:{fontSize:12,fontWeight:'800',color:theme.muted},submit:{backgroundColor:theme.gold,borderRadius:9,paddingHorizontal:16,paddingVertical:10},submitText:{fontSize:12,fontWeight:'800',color:theme.g900}});
